"""Star formation history models: PSD kernels, GP generation, mean SFH, registry."""

from tengri.components.stellar.sfh._prior_sampling import (
    DEFAULT_AGE_GRID_YR,
    sample_sfh_prior,
)
from tengri.components.stellar.sfh.chemical_evolution import (
    chem_evol_metallicity_on_ssp_grid,
    closed_box_metallicity,
    closed_box_metallicity_anchored,
)
from tengri.components.stellar.sfh.dense_basis import (
    dense_basis,
    dense_basis_pure,
    dense_basis_pure_sfh,
    dense_basis_sfh,
)
from tengri.components.stellar.sfh.gp_sfh import (
    compute_sqrt_power_drw as compute_sqrt_power_drw,
    generate_gp_fourier as generate_gp_fourier,
    gp_from_xi as gp_from_xi,
)
from tengri.components.stellar.sfh.mean_sfh import (
    AGEMAX_YR,
    constant,
    constant_sfh,
    constant_then_exponential,
    constant_then_exponential_sfh,
    declining_exponential,
    declining_exponential_sfh,
    delayed_exponential,
    delayed_exponential_sfh,
    delayed_tau,
    double_powerlaw,
    dpl,
    exponential,
    exponential_sfh,
    gaussian,
    gaussian_sfh,
    lnorm,
    lognormal,
    lognormal_sfh,
    norm,
    powerlaw,
    powerlaw_sfh,
    psb_wild2020,
    skewnormal,
    skewnormal_sfh,
    snorm,
    snorm_burst,
    snorm_burst_sfh,
    snorm_trunc_burst,
    snorm_trunc_burst_sfh,
    spline,
    spline_sfh,
    triweight_burst,
    truncated_skewnormal,
    truncated_skewnormal_sfh,
    tsnorm,
    tsnorm_burst,
)
from tengri.components.stellar.sfh.met_registry import MET_REGISTRY, resolve_met
from tengri.components.stellar.sfh.metallicity_history import (
    metallicity_bins_continuity_on_ssp_grid,
    metallicity_bins_on_ssp_grid,
    psb_two_step_metallicity,
    tabulated_metallicity_on_ssp_grid,
    two_step_metallicity,
)
from tengri.components.stellar.sfh.nonparametric import (
    bursty_continuity_prior_logp,
    continuity,
    continuity_flex,
    continuity_flex_prior_logp,
    continuity_flex_sfh,
    continuity_prior_logp,
    continuity_sfh,
    dirichlet,
    dirichlet_sfh,
    make_agebins_from_zred,
    psb_continuity,
    psb_continuity_sfh,
)
from tengri.components.stellar.sfh.psd_models import (
    psd_drw as psd_drw,
    psd_extended_regulator as psd_extended_regulator,
    psd_matern as psd_matern,
)
from tengri.components.stellar.sfh.registry import (
    FIELD_MODEL_REGISTRY,
    SFH_REGISTRY,
    compute_field_gp,
    resolve_sfh,
)

# New short names are canonical; the `_sfh`-suffixed variants remain
# accessible as `deprecated_alias`-wrapped functions in the source
# modules (mean_sfh.py, dense_basis.py, nonparametric.py) until v1.0.
# See docs/dev/api_migration_v0.x.md.
__all__ = [
    "AGEMAX_YR",
    "DEFAULT_AGE_GRID_YR",
    "FIELD_MODEL_REGISTRY",
    "MET_REGISTRY",
    "SFH_REGISTRY",
    "bursty_continuity_prior_logp",
    "chem_evol_metallicity_on_ssp_grid",
    "closed_box_metallicity",
    "closed_box_metallicity_anchored",
    "compute_field_gp",
    "compute_sqrt_power_drw",
    "constant",
    "constant_sfh",
    "constant_then_exponential",
    "constant_then_exponential_sfh",
    "continuity",
    "continuity_flex",
    "continuity_flex_prior_logp",
    "continuity_flex_sfh",
    "continuity_prior_logp",
    "continuity_sfh",
    "declining_exponential",
    "declining_exponential_sfh",
    "delayed_exponential",
    "delayed_exponential_sfh",
    "delayed_tau",
    "dense_basis",
    "dense_basis_pure",
    "dense_basis_pure_sfh",
    "dense_basis_sfh",
    "dirichlet",
    "dirichlet_sfh",
    "double_powerlaw",
    "dpl",
    "exponential",
    "exponential_sfh",
    "gaussian",
    "gaussian_sfh",
    "generate_gp_fourier",
    "gp_from_xi",
    "lnorm",
    "lognormal",
    "lognormal_sfh",
    "make_agebins_from_zred",
    "metallicity_bins_continuity_on_ssp_grid",
    "metallicity_bins_on_ssp_grid",
    "norm",
    "powerlaw",
    "powerlaw_sfh",
    "psb_continuity",
    "psb_continuity_sfh",
    "psb_two_step_metallicity",
    "psb_wild2020",
    "psd_drw",
    "psd_extended_regulator",
    "psd_matern",
    "resolve_met",
    "resolve_sfh",
    "sample_sfh_prior",
    "skewnormal",
    "skewnormal_sfh",
    "snorm",
    "snorm_burst",
    "snorm_burst_sfh",
    "snorm_trunc_burst",
    "snorm_trunc_burst_sfh",
    "spline",
    "spline_sfh",
    "tabulated_metallicity_on_ssp_grid",
    "triweight_burst",
    "truncated_skewnormal",
    "truncated_skewnormal_sfh",
    "tsnorm",
    "tsnorm_burst",
    "two_step_metallicity",
]


def __dir__() -> list[str]:
    """Curated tab-completion list — only the names in ``__all__``."""
    return list(__all__)
