# SPDX-License-Identifier: BSD-3-Clause
"""Radio SED models: synchrotron + free-free + AGN jets.

Predicts radio emission (mm–cm wavelengths) from three physical components:

1. **Star-forming synchrotron** (supernova remnants): scaled via FIR–radio
   correlation (FIRRC) with optional mass and redshift evolution
2. **Thermal free-free** (HII regions): bremsstrahlung, temperature-dependent
3. **AGN radio** (jets/lobes): parameterized by radio-loudness R

All functions are pure JAX, JIT-compatible, and fully differentiable.

**SFR→radio conversion modes** (select via sfr_mode parameter):

- ``"bell2003"``: Fixed FIRRC q_IR = 2.64 (Bell 2003). Default, no evolution.
- ``"delvecchio2021"``: Mass + redshift-dependent FIRRC at 1.4 GHz (Delvecchio+2021).
  Correlation params exposed as arguments for hierarchical priors.
- ``"mccheyne2022"``: Mass + redshift-dependent FIRRC at 150 MHz (McCheyne+2022).
  Same architecture as Delvecchio2021.

**Synchrotron suppression**: Low-mass galaxies have reduced non-thermal fraction
(Bell 2003), encoded via the suppression function that scales luminosity by
n(L) = 0.9 × (L/L*)^0.3 below threshold L* = 3e28 erg/s/Hz.

**Radio frequency range**: λ > 1 mm (ν < 300 GHz). SED is zero shortward of
this limit; radio-only modes skip optical/IR computation entirely.
"""

import math

import jax.numpy as jnp

from tengri.utils.physics_constants import C_AA as _C_AA, L_SUN as _L_SUN
from tengri.utils.scale import pow10 as _pow10

# Bell (2003) ApJ 586, 794 Eq. 3: characteristic luminosity L* at 1.4 GHz.
# L* ≈ 3e28 erg/s/Hz corresponds to the M_V = -21 galaxy threshold.
_L_STAR_SYNCH: float = 3.0e28  # erg/s/Hz at 1.4 GHz
_L0_SYNCH = _L_STAR_SYNCH  # alias used in tests and external references

# Wavelength boundary separating radio from IR (1 mm = 1e7 Angstrom = 300 GHz)
_RADIO_WAVE_MIN_AA: float = 1.0e7

# Murphy+2011 Eq. 11 free-free calibration constant [erg/s/Hz per (M☉/yr) at 1 GHz, Te=1e4 K]
# Derivation: SFR/(M☉/yr) = 4.6e-28 × (Te/1e4)^{-0.45} × (ν/GHz)^{0.1} × L_ν[erg/s/Hz]
# → L_ν[erg/s/Hz] = SFR × (Te/1e4)^{0.45} × (ν/GHz)^{-0.1} / 4.6e-28
# At 1.4 GHz, Te=1e4: 2.174e27 × (1.4)^{-0.1} ≈ 2.10e27 erg/s/Hz per M☉/yr
_C_FF: float = 1.0 / 4.6e-28  # ≈ 2.174e27

# Kennicutt+1998 IR-SFR calibration: L_IR [erg/s] → SFR [M☉/yr]
_SFR_IR_KENNICUTT: float = 1.73e10 * _L_SUN  # ≈ 6.62e43 erg/s

# log10 of the FIRRC / free-free divisors: used by the float32-safe branches
# (#1206) that form the (representable) radio luminosity directly from
# ``log10(L_IR)`` so the ~1e43 erg/s linear ``L_IR`` never materializes (it
# overflows float32 max, 3.4e38, poisoning ``inf / finite → inf``).
_LOG10_FIRRC_CONST: float = math.log10(3.75e12)  # bell/delvecchio/mccheyne norm
_LOG10_SFR_IR_KENNICUTT: float = math.log10(_SFR_IR_KENNICUTT)  # free-free


def _synchrotron_suppression(L_ref: jnp.ndarray) -> jnp.ndarray:
    r"""Apply Bell (2003) non-thermal fraction correction to synchrotron luminosity.

    Corrects for the fact that low-mass, low-SFR galaxies have reduced synchrotron
    efficiency due to cosmic-ray energy loss. The non-thermal fraction n(L)
    transitions from ~0.9 (high-L, unaffected) to lower values below a critical
    luminosity L* (Bell 2003, Eq. 3).

    Parameters
    ----------
    L_ref : array or float
        Synchrotron luminosity density at reference frequency. [erg/s/Hz]

    Returns
    -------
    array or float
        Suppression-corrected luminosity: n(L) × L_ref. [erg/s/Hz]

    Notes
    -----
    **Suppression formula** (Bell 2003, ApJ 586, 794, Eq. 3):

        .. math::

            n(L) = \begin{cases}
                0.9 & \text{if } L \geq L_* \\
                0.9 \, \left(\frac{L}{L_*}\right)^{0.3} & \text{if } L < L_*
            \end{cases}

        where L* = 3 × 10^28 erg/s/Hz at 1.4 GHz (M_V = −21 threshold).

        The exponent 0.3 (gentle power-law) reflects the mild luminosity
        dependence of cosmic-ray losses in low-mass systems.

    **Physical mechanism**: Synchrotron radiation is generated by relativistic
    electrons in magnetic fields. In low-SFR galaxies, electrons escape
    (Klein et al. 1984; Chi et al. 1990; Price et al. 1992) before cooling
    via synchrotron, reducing the radio-to-IR ratio from the usual ~0.9 to
    lower values. High-L galaxies (massive, vigorous SF) retain sufficient
    magnetic fields and confinement to avoid suppression.

    **Application**: Correction is applied at the reference frequency before
    power-law spectral extrapolation, so the spectral shape (α_1.4GHz) is
    preserved; only the normalization is adjusted.
    """
    L_safe = jnp.where(L_ref > 0.0, L_ref, 1.0e-40)
    n = jnp.where(
        L_safe >= _L_STAR_SYNCH,
        0.9,
        0.9 * (L_safe / _L_STAR_SYNCH) ** 0.3,
    )
    return n * L_ref


def radio_sfr_bell2003(
    wavelength: jnp.ndarray,
    L_ir: float,
    q_ir: float = 2.64,
    alpha_sf: float = 0.8,
    nu_ref: float = 1.4e9,
    *,
    log_L_ir: float | None = None,
) -> jnp.ndarray:
    """Star-forming synchrotron via fixed scalar FIRRC (Bell 2003).

    This is the original Bell+2003 model with a constant q_IR.  It is
    Equivalent to the former ``radio_star_forming`` function and available
    as the ``sfr_mode="bell2003"`` option in ``radio_total``.

    .. math::

        L_\\nu(\\text{radio}) = \\frac{L_{\\rm IR}}{3.75 \\times 10^{12}
        \\times 10^{q_{\\rm IR}}} \\left(\\frac{\\nu}{\\nu_{\\rm ref}}
        \\right)^{-\\alpha}

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        Total infrared luminosity (8-1000 μm) [erg/s].
    q_ir : float
        FIR-radio correlation parameter. Default 2.64 (Bell 2003, z=0).
    alpha_sf : float
        Synchrotron spectral index (S_ν ∝ ν^{-α}). Default 0.8.
    nu_ref : float
        Reference frequency [Hz]. Default 1.4 GHz.

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.
    """
    nu = _C_AA / wavelength
    if log_L_ir is None:
        L_ref = L_ir / (3.75e12 * 10.0**q_ir)  # erg/s/Hz at nu_ref
    else:
        # float32-safe (#1206): the ~1e28 erg/s/Hz radio luminosity is fully
        # representable: only the linear ``L_IR`` (~1e43) overflows. Form the
        # quotient straight from ``log10(L_IR)`` so ``L_IR`` never materializes.
        L_ref = _pow10(log_L_ir - _LOG10_FIRRC_CONST - q_ir)
    L_nu = L_ref * (nu / nu_ref) ** (-alpha_sf)
    return jnp.where(wavelength > _RADIO_WAVE_MIN_AA, L_nu, 0.0)


# Backward-compatible alias
radio_star_forming = radio_sfr_bell2003


def radio_sfr_delvecchio2021(
    wavelength: jnp.ndarray,
    L_ir: float,
    log_mstar: float,
    redshift: float,
    q0: float = 2.743,
    mass_slope: float = 0.234,
    z_slope: float = -0.025,
    alpha_sf: float = 0.7,
    nu_ref: float = 1.4e9,
    apply_suppression: bool = True,
    *,
    log_L_ir: float | None = None,
) -> jnp.ndarray:
    """Star-forming synchrotron via mass- and redshift-dependent FIRRC at 1.4 GHz.

    Implements the UV+FIR FIRRC from Delvecchio+2021 (Eq. 4 in SEMPER,
    arXiv:2503.20525), calibrated on >400 000 SFGs in COSMOS at 0.1 < z < 4:

    .. math::

        q(M_\\star, z) = q_0 \\, (1+z)^{z_{\\rm slope}}
        - (\\log M_\\star/M_\\odot - 10) \\times m_{\\rm slope}

    The three FIRRC parameters (``q0``, ``mass_slope``, ``z_slope``) are
    exposed as function arguments so they can be promoted to hierarchical
    prior hyperparameters in ``PopulationFitter`` without modifying this
    code.  Their defaults are the Delvecchio+2021 best-fit values.

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        Total infrared luminosity (8-1000 μm) [erg/s].
    log_mstar : float
        log10(M★ / M⊙). Typical range [8, 12].
    redshift : float
        Galaxy redshift. Valid range [0.1, 4] per Delvecchio+2021.
    q0 : float
        FIRRC normalization at log(M★)=10, z=0. Default 2.743.
        Hierarchical prior suggestion: Uniform(2.4, 3.1).
    mass_slope : float
        ∂q / ∂log(M★). Default 0.234 (negative: massive → lower q → more radio).
        Hierarchical prior suggestion: Uniform(0.0, 0.5).
    z_slope : float
        Power-law exponent on (1+z). Default -0.025 (slight decline with z).
        Hierarchical prior suggestion: Uniform(-0.2, 0.05).
    alpha_sf : float
        Synchrotron spectral index. Default 0.7 (consensus: Novak+2017, SEMPER).
    nu_ref : float
        Reference frequency [Hz]. Default 1.4 GHz (calibration frequency).
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression for low-SFR galaxies.
        Default True.

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.

    q decreases with increasing M★ (radio-brighter per unit IR for massive
    galaxies), consistent with stronger magnetic fields and denser ISM.
    The z_slope = -0.025 implies much more modest redshift evolution than the
    older Delhaize+2017 value of -0.15.
    """
    nu = _C_AA / wavelength

    # Mass- and redshift-dependent q_IR (Delvecchio+2021 UV+FIR, SEMPER Eq. 4)
    q_ir = q0 * (1.0 + redshift) ** z_slope - (log_mstar - 10.0) * mass_slope

    # L at 1.4 GHz reference from FIRRC definition. float32-safe (#1206): form
    # from log10(L_IR) when supplied so the ~1e43 linear L_IR never materializes.
    if log_L_ir is None:
        L_ref = L_ir / (3.75e12 * 10.0**q_ir)  # erg/s/Hz
    else:
        L_ref = _pow10(log_L_ir - _LOG10_FIRRC_CONST - q_ir)

    # Optional Bell+2003 synchrotron suppression (low-SFR galaxies)
    L_ref = jnp.where(apply_suppression, _synchrotron_suppression(L_ref), L_ref)

    L_nu = L_ref * (nu / nu_ref) ** (-alpha_sf)
    return jnp.where(wavelength > _RADIO_WAVE_MIN_AA, L_nu, 0.0)


def radio_sfr_mccheyne2022(
    wavelength: jnp.ndarray,
    L_ir: float,
    log_mstar: float,
    redshift: float,
    q0: float = 1.98,
    mass_slope: float = -0.22,
    z_slope: float = 0.02,
    alpha_sf: float = 0.7,
    nu_ref: float = 1.5e8,
    apply_suppression: bool = True,
    *,
    log_L_ir: float | None = None,
) -> jnp.ndarray:
    """Star-forming synchrotron via mass- and redshift-dependent FIRRC at 150 MHz.

    Implements the FIRRC from McCheyne+2022 (Eq. 5 in SEMPER, arXiv:2503.20525),
    derived from LOFAR 150 MHz observations of a mass-complete sample in
    ELAIS-N1 at z < 1:

    .. math::

        q(z, M_\\star) = q_0 \\, (1+z)^{z_{\\rm slope}}
        + m_{\\rm slope} \\times (\\log M_\\star/M_\\odot - 10)

    This relation is natively calibrated at 150 MHz and is preferred over
    spectral-index rescaling from 1.4 GHz for low-frequency data. For z > 1,
    the Delvecchio+2021 model (rescaled to 150 MHz) is better constrained.

    The three FIRRC parameters (``q0``, ``mass_slope``, ``z_slope``) are
    exposed as hierarchical prior parameters; their defaults are the
    McCheyne+2022 best-fit values.

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        Total infrared luminosity (8-1000 μm) [erg/s].
    log_mstar : float
        log10(M★ / M⊙). Typical range [10.05, 11.4] per McCheyne+2022.
    redshift : float
        Galaxy redshift. Valid range [0, 1] per McCheyne+2022.
    q0 : float
        FIRRC normalization at log(M★)=10, z=0. Default 1.98.
        Hierarchical prior suggestion: Uniform(1.5, 2.5).
    mass_slope : float
        ∂q / ∂log(M★). Default -0.22 (negative sign convention differs from
        Delvecchio: here higher M★ → lower q directly via negative coefficient).
        Hierarchical prior suggestion: Uniform(-0.5, 0.0).
    z_slope : float
        Power-law exponent on (1+z). Default 0.02 (nearly no z evolution).
        Hierarchical prior suggestion: Uniform(-0.1, 0.2).
    alpha_sf : float
        Synchrotron spectral index. Default 0.7.
    nu_ref : float
        Reference frequency [Hz]. Default 150 MHz (calibration frequency).
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression. Default True.

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.

    McCheyne+2022 reports a steeper mass dependence than Delvecchio+2021.
    The discrepancy is reconciled when using α = -0.59 instead of -0.7 for
    spectral index conversion between 1.4 GHz and 150 MHz.
    """
    nu = _C_AA / wavelength

    # Mass- and redshift-dependent q at 150 MHz (McCheyne+2022, SEMPER Eq. 5)
    q_ir = q0 * (1.0 + redshift) ** z_slope + mass_slope * (log_mstar - 10.0)

    # L at 150 MHz reference from FIRRC definition. float32-safe (#1206): form
    # from log10(L_IR) when supplied so the ~1e43 linear L_IR never materializes.
    if log_L_ir is None:
        L_ref = L_ir / (3.75e12 * 10.0**q_ir)  # erg/s/Hz
    else:
        L_ref = _pow10(log_L_ir - _LOG10_FIRRC_CONST - q_ir)

    # Optional Bell+2003 synchrotron suppression
    L_ref = jnp.where(apply_suppression, _synchrotron_suppression(L_ref), L_ref)

    L_nu = L_ref * (nu / nu_ref) ** (-alpha_sf)
    return jnp.where(wavelength > _RADIO_WAVE_MIN_AA, L_nu, 0.0)


def radio_freefree(
    wavelength: jnp.ndarray,
    L_ir: float,
    T_e: float = 1e4,
    alpha_ff: float = -0.1,
    *,
    log_L_ir: float | None = None,
) -> jnp.ndarray:
    """Thermal free-free (bremsstrahlung) emission from HII regions.

    Traces instantaneous SFR via the Kennicutt+1998 IR calibration and the
    Murphy+2011 radio-SFR relation (Eq. 11).  At 1.4 GHz a typical star-forming
    galaxy contributes ~5–15% of its total radio flux from free-free, depending
    on the FIRRC calibration used for the synchrotron component.

    .. math::

        L_\\nu^{\\rm ff} = C_{\\rm ff} \\, (T_e / 10^4\\,{\\rm K})^{0.45}
        \\left(\\frac{\\nu}{\\rm GHz}\\right)^{\\alpha_{\\rm ff}}
        \\frac{L_{\\rm IR}}{L_{\\rm IR,\\odot}}

    where :math:`C_{\\rm ff} = 1 / (4.6 \\times 10^{-28} \\, L_\\odot)
    \\approx 5.68 \\times 10^{-7}` erg/s/Hz per M☉/yr at 1 GHz and
    :math:`L_{\\rm IR,\\odot} = 1.73 \\times 10^{10}` Lsun (Kennicutt+1998).

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        Total infrared luminosity (8-1000 μm) [erg/s].
    T_e : float
        Electron temperature [K]. Default 1e4.
        Prior suggestion: LogUniform(5e3, 2e4).
    alpha_ff : float
        Free-free spectral index (L_ν ∝ ν^{α_ff}). Default −0.1 (nearly flat).
        Prior suggestion: Uniform(−0.15, 0.0).

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.

    Calibration check: at 1.4 GHz, Te=1e4 K, L_IR=1e10 Lsun (SFR≈0.58 M☉/yr):
    L_ff ≈ 5.49e-7 × 0.58 ≈ 3.2e-7 Lsun/Hz (Murphy+2011 Table 1 consistent).

    References
    ----------

    - Murphy et al. 2011, ApJ, 737, 67 (Eq. 11)
    - Condon 1992, ARA&A, 30, 575
    - Kennicutt 1998, ARA&A, 36, 189

    """
    nu = _C_AA / wavelength  # Hz
    nu_ghz = nu / 1.0e9  # GHz
    # float32-safe (#1206): form the SFR straight from log10(L_IR) when supplied
    # so the ~1e43 linear L_IR (inf in float32) never materializes.
    if log_L_ir is None:
        sfr = L_ir / _SFR_IR_KENNICUTT  # M☉/yr
    else:
        sfr = _pow10(log_L_ir - _LOG10_SFR_IR_KENNICUTT)  # M☉/yr
    # Murphy+2011 Eq. 11 inverted; (T_e/1e4)^0.45 factor from ionized gas physics
    L_nu = _C_FF * (T_e / 1.0e4) ** 0.45 * nu_ghz**alpha_ff * sfr
    return jnp.where(wavelength > _RADIO_WAVE_MIN_AA, L_nu, 0.0)


def _dispatch_sfr(
    wavelength: jnp.ndarray,
    L_ir: float,
    sfr_mode: str,
    q_ir: float,
    alpha_sf: float,
    log_mstar: float,
    redshift: float,
    q0: float | None,
    mass_slope: float | None,
    z_slope: float | None,
    apply_suppression: bool,
    log_L_ir: float | None = None,
) -> jnp.ndarray:
    """Dispatch SFR synchrotron component by mode (private helper).

    Eliminates duplicated ``if/elif sfr_mode`` blocks in ``radio_total`` and
    ``radio_total_dpl``.  Only the FIRRC normalization (Layer 1) differs between
    modes; the spectral shape machinery (Layer 3) is shared inside each wrapper.

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        IR luminosity [erg/s].
    sfr_mode : str
        One of ``"none"``, ``"bell2003"``, ``"delvecchio2021"``,
        ``"mccheyne2022"``. Default ``"bell2003"``.
    q_ir : float
        Fixed q_IR (bell2003 mode only) [dimensionless].
    alpha_sf : float
        Synchrotron spectral index [dimensionless].
    log_mstar : float
        log10(M★/M⊙) [dex].
    redshift : float
        Galaxy redshift [dimensionless].
    q0 : float or None
        FIRRC normalization override; None uses mode default.
    mass_slope : float or None
        Mass slope override; None uses mode default.
    z_slope : float or None
        Redshift slope override; None uses mode default.
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression.

    Returns
    -------
    array, shape (n_wave,)
        L_nu [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.
    """
    if sfr_mode == "none":
        return jnp.zeros_like(wavelength)
    elif sfr_mode == "bell2003":
        return radio_sfr_bell2003(wavelength, L_ir, q_ir, alpha_sf, log_L_ir=log_L_ir)
    elif sfr_mode == "delvecchio2021":
        kw = {}
        if q0 is not None:
            kw["q0"] = q0
        if mass_slope is not None:
            kw["mass_slope"] = mass_slope
        if z_slope is not None:
            kw["z_slope"] = z_slope
        return radio_sfr_delvecchio2021(
            wavelength,
            L_ir,
            log_mstar,
            redshift,
            apply_suppression=apply_suppression,
            log_L_ir=log_L_ir,
            **kw,
        )
    elif sfr_mode == "mccheyne2022":
        kw = {}
        if q0 is not None:
            kw["q0"] = q0
        if mass_slope is not None:
            kw["mass_slope"] = mass_slope
        if z_slope is not None:
            kw["z_slope"] = z_slope
        return radio_sfr_mccheyne2022(
            wavelength,
            L_ir,
            log_mstar,
            redshift,
            apply_suppression=apply_suppression,
            log_L_ir=log_L_ir,
            **kw,
        )
    else:
        raise ValueError(
            f"Unknown sfr_mode {sfr_mode!r}. "
            "Choose 'none', 'bell2003', 'delvecchio2021', or 'mccheyne2022'."
        )


def radio_agn(
    wavelength: jnp.ndarray,
    L_agn_bol: float,
    radio_loudness: float = 0.0,
    alpha_agn: float = 0.7,
    nu_ref: float = 1.4e9,
    l_bband: float = 0.0,
    log_nu_cut: float = 13.0,
    *,
    log_L_agn_bol: float | None = None,
) -> jnp.ndarray:
    r"""Radio emission from AGN jets/lobes (single power law with aging cutoff).

    .. math::

        L_\nu(\mathrm{radio}) = R\, L_{5\,\mathrm{GHz}}\,
            \left(\frac{\nu}{5\,\mathrm{GHz}}\right)^{-\alpha}
            \exp\!\left(-\frac{\nu}{\nu_{\mathrm{cut}}}\right)

    The radio-loudness parameter R = log10(L_5GHz / L_B) where L_B is
    the B-band luminosity. R > 1 = radio-loud, R < 1 = radio-quiet.

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_agn_bol : float
        AGN bolometric luminosity [erg/s].
    radio_loudness : float
        log10(L_5GHz / L_B). Default 0 (radio-quiet). Range: -2 to 5.
    alpha_agn : float
        AGN radio spectral index. Default 0.7.
    nu_ref : float
        Reference frequency [Hz]. Default 1.4 GHz.
    l_bband : float
        AGN intrinsic disc B-band (4400 A) monochromatic luminosity [erg/s/Hz].
        When > 0, used directly instead of deriving from L_agn_bol bolometric
        correction. Default 0.0 (uses L_bol correction).
    log_nu_cut : float
        log10 of the synchrotron-aging cutoff frequency [Hz]. Default 13.0
        (10 THz), matching AGNfitter-rX's SPL jet ``exp(-nu/1e13)``.

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.

    The high-frequency rolloff is governed by the physical synchrotron-aging
    cutoff (``log_nu_cut``, default 10 THz), NOT by an arbitrary wavelength
    floor: an AGN jet extends well into the sub-mm/IR (AGNfitter-rX carries it
    to 10^15 Hz; 10^18.5 Hz for blazars). Only the star-formation radio
    (:func:`radio_sfr_bell2003`) keeps the 1 mm floor, since it is tied to the
    dust FIR and must not double-count there. Matches the AGNfitter-rX
    ``AGN_RAD`` nRADdata==1 SPL convention.
    """
    nu = _C_AA / wavelength

    # Monochromatic luminosity density at B-band (4400 A) in erg/s/Hz.
    # When l_bband is provided (disc-derived), use it directly; else derive from
    # L_bol via bolometric correction. L_bol = BC_B * nu_B * L_nu(4400) =>
    # L_nu = L_bol / (BC_B * nu_B). BC_B ~ 5.15 (Hopkins+2007, Table 1),
    # nu_B = c / 4400 A = 6.818e14 Hz.
    _NU_B = 6.818e14  # Hz
    _BC_B = 5.15  # Hopkins+2007 bolometric correction at 4400 A
    # float32-safe (#1206): form the bolometric-correction fallback from
    # log10(L_agn_bol) when supplied so the ~1e46 linear L_agn_bol never
    # materializes. This also matters when ``l_bband > 0`` selects the other
    # branch: ``jnp.where`` still evaluates both, and a linear ``inf`` in the
    # dead branch turns the reverse pass into ``0 * inf = nan``.
    if log_L_agn_bol is None:
        L_B_fallback = L_agn_bol / (_BC_B * _NU_B)
    else:
        L_B_fallback = _pow10(log_L_agn_bol - math.log10(_BC_B * _NU_B))
    L_B = jnp.where(l_bband > 0.0, l_bband, L_B_fallback)  # erg/s/Hz

    # L_5GHz from radio-loudness definition
    L_5GHz = L_B * 10.0**radio_loudness  # erg/s/Hz

    # Power-law from 5 GHz with a synchrotron-aging exponential cutoff. The
    # cutoff (not a hard wavelength floor) is what physically truncates the
    # jet at high frequency, so the jet extends smoothly into the sub-mm
    # instead of dropping to zero at 300 GHz (1 mm).
    nu_5GHz = 5.0e9
    nu_cut = 10.0**log_nu_cut
    return L_5GHz * (nu / nu_5GHz) ** (-alpha_agn) * jnp.exp(-nu / nu_cut)


def radio_agn_dpl(
    wavelength: jnp.ndarray,
    L_agn_bol: float,
    radio_loudness: float = 0.0,
    alpha1: float = -0.75,
    alpha2: float = -0.1,
    log_nu_t: float = 10.0,
    log_nu_cut: float = 13.0,
    nu_ref: float = 5.0e9,
    l_bband: float = 0.0,
    *,
    log_L_agn_bol: float | None = None,
) -> jnp.ndarray:
    """Double power-law AGN radio emission (AGNfitter-rx).

    Implements the broken power-law model from Martinez-Ramirez+2024 (Eq. 9-10)
    with an optically-thick low-frequency regime, an optically-thin steep
    high-frequency regime, and a synchrotron aging exponential cutoff.

    .. math::

        L_\\nu = L_{5\\mathrm{GHz}} \\left(\\frac{\\nu}{\\nu_t}\\right)^{\\alpha_1}
        \\left[1 - \\exp\\left(-\\left(\\frac{\\nu_t}{\\nu}\\right)^{\\alpha_1 - \\alpha_2}
        \\right)\\right] \\exp\\left(-\\frac{\\nu}{\\nu_{\\mathrm{cut}}}\\right)

    Parameters
    ----------
    wavelength : array (n_wave,)
        Wavelength in Angstrom.
    L_agn_bol : float
        AGN bolometric luminosity in erg/s.
    radio_loudness : float
        log10(L_5GHz / L_B). Default 0 (radio-quiet). Range: [-2, 5].
    alpha1 : float
        Optically thin (steep) spectral slope. Default -0.75. Range: [-2, 0].
    alpha2 : float
        Optically thick (flat/inverted) spectral slope. Default -0.1.
        Range: [-1, 1].
    log_nu_t : float
        log10(transition frequency / Hz). Default 10.0. Range: [7, 13].
    log_nu_cut : float
        log10(synchrotron aging cutoff frequency / Hz). Default 13.0.
    nu_ref : float
        Reference frequency for L_5GHz normalization. Default 5 GHz.
    l_bband : float
        AGN intrinsic disc B-band (4400 A) monochromatic luminosity [erg/s/Hz].
        When > 0, used directly instead of deriving from L_agn_bol bolometric
        correction. Default 0.0 (uses L_bol correction).

    Returns
    -------
    array (n_wave,)
        L_nu in erg/s/Hz.

    Notes
    -----
    At frequencies well below nu_t the spectrum flattens to ~nu^alpha2
    (self-absorbed synchrotron). Above nu_t the spectrum steepens to ~nu^alpha1
    (optically thin synchrotron). The exponential cutoff at nu_cut models
    synchrotron aging losses.
    """
    nu = _C_AA / wavelength  # Hz

    # B-band luminosity density (same as radio_agn). When l_bband is provided
    # (disc-derived), use it directly; else derive from L_bol bolometric correction.
    _NU_B = 6.818e14  # Hz
    _BC_B = 5.15  # Hopkins+2007
    # float32-safe (#1206): see radio_agn; form the fallback from
    # log10(L_agn_bol) so the ~1e46 linear L_agn_bol never materializes, and so
    # the dead ``jnp.where`` branch is finite (avoiding 0 * inf = nan in grad).
    if log_L_agn_bol is None:
        L_B_fallback = L_agn_bol / (_BC_B * _NU_B)
    else:
        L_B_fallback = _pow10(log_L_agn_bol - math.log10(_BC_B * _NU_B))
    L_B = jnp.where(l_bband > 0.0, l_bband, L_B_fallback)  # erg/s/Hz

    # L_5GHz from radio-loudness definition
    L_5GHz = L_B * 10.0**radio_loudness  # erg/s/Hz

    nu_t = 10.0**log_nu_t
    nu_cut = 10.0**log_nu_cut

    # Double power-law (Martinez-Ramirez+2024 Eq. 9-10)
    def _dpl_shape(freq):
        """Compute double power-law spectral shape with turnover and cutoff."""
        ratio = freq / nu_t
        thick_thin = jnp.power(ratio, alpha1)
        turnover = 1.0 - jnp.exp(-jnp.power(nu_t / freq, alpha1 - alpha2))
        cutoff = jnp.exp(-freq / nu_cut)
        return thick_thin * turnover * cutoff

    shape = _dpl_shape(nu)
    shape_ref = _dpl_shape(nu_ref)
    # Guard against shape_ref ~ 0 (should not happen for physical params)
    shape_ref_safe = jnp.where(shape_ref > 0.0, shape_ref, 1.0)
    L_nu = L_5GHz * shape / shape_ref_safe

    # No 1 mm hard floor for the AGN jet: the synchrotron-aging exponential
    # cutoff (nu_cut in _dpl_shape) is the physical high-frequency truncation,
    # so the jet extends smoothly into the sub-mm/IR instead of dropping to
    # zero at 300 GHz. AGNfitter-rX carries this jet to 10^15 Hz.
    return L_nu


def radio_total_terms(
    wavelength: jnp.ndarray,
    L_ir: float = 0.0,
    L_agn_bol: float = 0.0,
    q_ir: float = 2.64,
    alpha_sf: float = 0.8,
    radio_loudness: float = 0.0,
    alpha_agn: float = 0.7,
    sfr_mode: str = "bell2003",
    log_mstar: float = 10.0,
    redshift: float = 0.0,
    q0: float | None = None,
    mass_slope: float | None = None,
    z_slope: float | None = None,
    apply_suppression: bool = True,
    include_freefree: bool = True,
    T_e: float = 1e4,
    alpha_ff: float = -0.1,
    l_bband: float = 0.0,
    log_L_ir: float | None = None,
    log_L_agn_bol: float | None = None,
    **_kwargs,
) -> dict[str, jnp.ndarray]:
    """Decompose radio emission into additive terms for precomputation.

    Returns the three additive components of total radio emission separately:
    star-forming synchrotron, thermal free-free, and AGN power-law. Each term
    is rank-1 in wavelength (a scalar amplitude times a fixed spectral shape
    given shape parameters), enabling build-time precomputation of their
    individual filter integrals. At runtime, the cost collapses to three
    scalar multiplications per passband.

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        Total infrared luminosity (8–1000 μm) [erg/s] for star-forming and
        free-free components.
    L_agn_bol : float
        AGN bolometric luminosity [erg/s] for AGN component.
    q_ir : float
        FIR-radio correlation parameter (bell2003 mode only) [dimensionless].
        Default 2.64.
    alpha_sf : float
        Synchrotron spectral index [dimensionless]. Default 0.8.
    radio_loudness : float
        AGN radio-loudness log10(L_5GHz / L_B) [dimensionless]. Default 0.0.
    alpha_agn : float
        AGN radio spectral index [dimensionless]. Default 0.7.
    sfr_mode : str
        Star formation radio physics model. One of:

        - ``"bell2003"`` (default): fixed q_IR, no mass/z dependence.
        - ``"delvecchio2021"``: mass+z dependent FIRRC at 1.4 GHz.
        - ``"mccheyne2022"``: mass+z dependent FIRRC at 150 MHz.

    log_mstar : float
        log10(M★ / M⊙). Used by delvecchio2021 and mccheyne2022 modes.
        Default 10.0.
    redshift : float
        Galaxy redshift. Used by delvecchio2021 and mccheyne2022 modes.
        Default 0.0.
    q0 : float or None
        FIRRC normalization override; None uses the mode's literature default.
    mass_slope : float or None
        Mass slope override; None uses the mode's literature default.
    z_slope : float or None
        Redshift slope override; None uses the mode's literature default.
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression for low-SFR galaxies
        (delvecchio2021/mccheyne2022 modes). Default True.
    include_freefree : bool
        Include thermal free-free (bremsstrahlung) component. Default True.
    T_e : float
        Electron temperature [K] for free-free component. Default 1e4.
    alpha_ff : float
        Free-free spectral index (L_ν ∝ ν^{α}) [dimensionless].
        Default -0.1.
    l_bband : float
        AGN intrinsic disc B-band (4400 A) monochromatic luminosity
        [erg/s/Hz]. When > 0, used directly in radio_agn instead of deriving
        from L_agn_bol bolometric correction. Default 0.0 (uses L_bol
        correction).

    Returns
    -------
    dict[str, ndarray]
        Dictionary with three keys:

        - ``"sf"`` : array, shape (n_wave,); star-forming synchrotron [erg/s/Hz]
        - ``"ff"`` : array, shape (n_wave,); thermal free-free [erg/s/Hz]
        - ``"agn"`` : array, shape (n_wave,); AGN radio [erg/s/Hz]

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function. **Grad/vmap compatible**: yes.

    Each term is rank-1 in wavelength: a scalar amplitude times a fixed
    spectral shape (parameterized by fixed shape parameters like α or T_e).
    This factorization enables build-time computation of ∫ term(λ) × R_filter(λ) dλ
    for each filter R and term, collapsing runtime cost to one scalar per
    filter per component. Combined with WavePrecomp, this eliminates the
    dominant wavelength-loop bottleneck.

    When ``include_freefree=False``, the ``"ff"`` key contains an all-zero array
    (shape-matched to wavelength) to maintain array structure for summing.
    """
    sf = _dispatch_sfr(
        wavelength,
        L_ir,
        sfr_mode,
        q_ir,
        alpha_sf,
        log_mstar,
        redshift,
        q0,
        mass_slope,
        z_slope,
        apply_suppression,
        log_L_ir=log_L_ir,
    )
    agn = radio_agn(
        wavelength,
        L_agn_bol,
        radio_loudness,
        alpha_agn,
        l_bband=l_bband,
        log_L_agn_bol=log_L_agn_bol,
    )
    ff = (
        radio_freefree(wavelength, L_ir, T_e, alpha_ff, log_L_ir=log_L_ir)
        if include_freefree
        else jnp.zeros_like(wavelength)
    )
    return {"sf": sf, "ff": ff, "agn": agn}


def radio_total(
    wavelength: jnp.ndarray,
    L_ir: float = 0.0,
    L_agn_bol: float = 0.0,
    q_ir: float = 2.64,
    alpha_sf: float = 0.8,
    radio_loudness: float = 0.0,
    alpha_agn: float = 0.7,
    sfr_mode: str = "bell2003",
    log_mstar: float = 10.0,
    redshift: float = 0.0,
    q0: float | None = None,
    mass_slope: float | None = None,
    z_slope: float | None = None,
    apply_suppression: bool = True,
    include_freefree: bool = True,
    T_e: float = 1e4,
    alpha_ff: float = -0.1,
    l_bband: float = 0.0,
    **_kwargs,
) -> jnp.ndarray:
    """Total radio emission (star-forming synchrotron + optional free-free + AGN power-law).

    Parameters
    ----------
    wavelength : array (n_wave,)
        Wavelength in Angstrom.
    L_ir : float
        Total IR luminosity (erg/s) for SF component.
    L_agn_bol : float
        AGN bolometric luminosity (erg/s) for AGN component.
    q_ir : float
        FIR-radio correlation parameter (bell2003 mode only).
    alpha_sf : float
        SF synchrotron spectral index. Default 0.8 in bell2003 mode; the
        Delvecchio/McCheyne modes default to 0.7 internally.
    radio_loudness : float
        AGN radio-loudness log10(L_5GHz/L_B).
    alpha_agn : float
        AGN radio spectral index.
    sfr_mode : str
        Which SFR physics model to use. One of:

        - ``"bell2003"`` (default): fixed q_IR, no mass/z dependence.
        - ``"delvecchio2021"``: mass+z dependent FIRRC at 1.4 GHz.
        - ``"mccheyne2022"``: mass+z dependent FIRRC at 150 MHz.

    log_mstar : float
        log10(M★/M⊙). Used by delvecchio2021 and mccheyne2022 modes.
    redshift : float
        Galaxy redshift. Used by delvecchio2021 and mccheyne2022 modes.
    q0 : float or None
        FIRRC normalization override. None uses the mode's literature default.
    mass_slope : float or None
        Mass slope override. None uses the mode's literature default.
    z_slope : float or None
        Redshift slope override. None uses the mode's literature default.
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression (delvecchio/mccheyne modes).
    include_freefree : bool
        Add thermal free-free component (Murphy+2011). Default False.
    T_e : float
        Electron temperature [K] for free-free component. Default 1e4.
    alpha_ff : float
        Free-free spectral index (L_ν ∝ ν^{α}). Default -0.1.
    l_bband : float
        AGN intrinsic disc B-band (4400 A) monochromatic luminosity [erg/s/Hz].
        When > 0, used directly in radio_agn instead of deriving from L_agn_bol
        bolometric correction. Default 0.0 (uses L_bol correction).

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.
    """
    t = radio_total_terms(
        wavelength,
        L_ir,
        L_agn_bol,
        q_ir,
        alpha_sf,
        radio_loudness,
        alpha_agn,
        sfr_mode,
        log_mstar,
        redshift,
        q0,
        mass_slope,
        z_slope,
        apply_suppression,
        include_freefree,
        T_e,
        alpha_ff,
        l_bband,
    )
    return t["sf"] + t["ff"] + t["agn"]


def radio_total_dpl_terms(
    wavelength: jnp.ndarray,
    L_ir: float = 0.0,
    L_agn_bol: float = 0.0,
    q_ir: float = 2.64,
    alpha_sf: float = 0.8,
    radio_loudness: float = 0.0,
    alpha1: float = -0.75,
    alpha2: float = -0.1,
    log_nu_t: float = 10.0,
    log_nu_cut: float = 13.0,
    sfr_mode: str = "bell2003",
    log_mstar: float = 10.0,
    redshift: float = 0.0,
    q0: float | None = None,
    mass_slope: float | None = None,
    z_slope: float | None = None,
    apply_suppression: bool = True,
    include_freefree: bool = True,
    T_e: float = 1e4,
    alpha_ff: float = -0.1,
    l_bband: float = 0.0,
    log_L_ir: float | None = None,
    log_L_agn_bol: float | None = None,
    **_kwargs,
) -> dict[str, jnp.ndarray]:
    """Decompose AGN double power-law radio emission into additive terms.

    Returns the three additive components of total radio emission with an
    AGNfitter-rx double power-law AGN model separately: star-forming
    synchrotron, thermal free-free, and AGN double power-law. Each term is
    rank-1 in wavelength (a scalar amplitude times a fixed spectral shape given
    shape parameters), enabling build-time precomputation of their individual
    filter integrals.

    Parameters
    ----------
    wavelength : array, shape (n_wave,)
        Wavelength [Angstrom].
    L_ir : float
        Total infrared luminosity (8–1000 μm) [erg/s] for star-forming and
        free-free components.
    L_agn_bol : float
        AGN bolometric luminosity [erg/s] for AGN component.
    q_ir : float
        FIR-radio correlation parameter (bell2003 mode only) [dimensionless].
        Default 2.64.
    alpha_sf : float
        Synchrotron spectral index [dimensionless]. Default 0.8.
    radio_loudness : float
        AGN radio-loudness log10(L_5GHz / L_B) [dimensionless]. Default 0.0.
    alpha1 : float
        AGN optically thin (steep) spectral slope [dimensionless].
        Default -0.75.
    alpha2 : float
        AGN optically thick (flat/inverted) spectral slope [dimensionless].
        Default -0.1.
    log_nu_t : float
        log10(AGN spectral break frequency / Hz) [dimensionless].
        Default 10.0.
    log_nu_cut : float
        log10(synchrotron aging cutoff frequency / Hz) [dimensionless].
        Default 13.0.
    sfr_mode : str
        Star formation radio physics model. One of:

        - ``"bell2003"`` (default): fixed q_IR, no mass/z dependence.
        - ``"delvecchio2021"``: mass+z dependent FIRRC at 1.4 GHz.
        - ``"mccheyne2022"``: mass+z dependent FIRRC at 150 MHz.

    log_mstar : float
        log10(M★ / M⊙). Used by delvecchio2021 and mccheyne2022 modes.
        Default 10.0.
    redshift : float
        Galaxy redshift. Used by delvecchio2021 and mccheyne2022 modes.
        Default 0.0.
    q0 : float or None
        FIRRC normalization override; None uses the mode's literature default.
    mass_slope : float or None
        Mass slope override; None uses the mode's literature default.
    z_slope : float or None
        Redshift slope override; None uses the mode's literature default.
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression for low-SFR galaxies
        (delvecchio2021/mccheyne2022 modes). Default True.
    include_freefree : bool
        Include thermal free-free (bremsstrahlung) component. Default True.
    T_e : float
        Electron temperature [K] for free-free component. Default 1e4.
    alpha_ff : float
        Free-free spectral index (L_ν ∝ ν^{α}) [dimensionless].
        Default -0.1.
    l_bband : float
        AGN intrinsic disc B-band (4400 A) monochromatic luminosity
        [erg/s/Hz]. When > 0, used directly in radio_agn_dpl instead of
        deriving from L_agn_bol bolometric correction. Default 0.0 (uses
        L_bol correction).

    Returns
    -------
    dict[str, ndarray]
        Dictionary with three keys:

        - ``"sf"`` : array, shape (n_wave,); star-forming synchrotron [erg/s/Hz]
        - ``"ff"`` : array, shape (n_wave,); thermal free-free [erg/s/Hz]
        - ``"agn"`` : array, shape (n_wave,); AGN double power-law [erg/s/Hz]

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function. **Grad/vmap compatible**: yes.

    Each term is rank-1 in wavelength: a scalar amplitude times a fixed
    spectral shape (parameterized by fixed shape parameters). This enables
    build-time computation of ∫ term(λ) × R_filter(λ) dλ for each filter R
    and term, collapsing runtime cost to one scalar per filter per component.

    When ``include_freefree=False``, the ``"ff"`` key contains an all-zero array
    (shape-matched to wavelength) to maintain array structure for summing.
    """
    sf = _dispatch_sfr(
        wavelength,
        L_ir,
        sfr_mode,
        q_ir,
        alpha_sf,
        log_mstar,
        redshift,
        q0,
        mass_slope,
        z_slope,
        apply_suppression,
        log_L_ir=log_L_ir,
    )
    agn = radio_agn_dpl(
        wavelength,
        L_agn_bol,
        radio_loudness,
        alpha1,
        alpha2,
        log_nu_t,
        log_nu_cut,
        l_bband=l_bband,
        log_L_agn_bol=log_L_agn_bol,
    )
    ff = (
        radio_freefree(wavelength, L_ir, T_e, alpha_ff, log_L_ir=log_L_ir)
        if include_freefree
        else jnp.zeros_like(wavelength)
    )
    return {"sf": sf, "ff": ff, "agn": agn}


def radio_total_dpl(
    wavelength: jnp.ndarray,
    L_ir: float = 0.0,
    L_agn_bol: float = 0.0,
    q_ir: float = 2.64,
    alpha_sf: float = 0.8,
    radio_loudness: float = 0.0,
    alpha1: float = -0.75,
    alpha2: float = -0.1,
    log_nu_t: float = 10.0,
    log_nu_cut: float = 13.0,
    sfr_mode: str = "bell2003",
    log_mstar: float = 10.0,
    redshift: float = 0.0,
    q0: float | None = None,
    mass_slope: float | None = None,
    z_slope: float | None = None,
    apply_suppression: bool = True,
    include_freefree: bool = True,
    T_e: float = 1e4,
    alpha_ff: float = -0.1,
    l_bband: float = 0.0,
    **_kwargs,
) -> jnp.ndarray:
    """Total radio emission: star-forming + optional free-free + AGN double power-law.

    Combines the SFR component (dispatched by ``sfr_mode``) with the optional
    thermal free-free component and the AGNfitter-rx double power-law AGN component.

    Parameters
    ----------
    wavelength : array (n_wave,)
        Wavelength in Angstrom.
    L_ir : float
        Total IR luminosity (erg/s) for SF component.
    L_agn_bol : float
        AGN bolometric luminosity (erg/s) for AGN component.
    q_ir : float
        FIR-radio correlation parameter (bell2003 mode only).
    alpha_sf : float
        SF synchrotron spectral index.
    radio_loudness : float
        AGN radio-loudness log10(L_5GHz/L_B).
    alpha1 : float
        Optically thin spectral slope.
    alpha2 : float
        Optically thick spectral slope.
    log_nu_t : float
        log10(transition frequency / Hz).
    log_nu_cut : float
        log10(synchrotron aging cutoff frequency / Hz).
    sfr_mode : str
        SFR physics model. See ``radio_total`` for options.
    log_mstar : float
        log10(M★/M⊙). Used by delvecchio2021 and mccheyne2022 modes.
    redshift : float
        Galaxy redshift. Used by delvecchio2021 and mccheyne2022 modes.
    q0 : float or None
        FIRRC normalization override.
    mass_slope : float or None
        Mass slope override.
    z_slope : float or None
        Redshift slope override.
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression.
    include_freefree : bool
        Add thermal free-free component (Murphy+2011). Default False.
    T_e : float
        Electron temperature [K] for free-free component. Default 1e4.
    alpha_ff : float
        Free-free spectral index. Default -0.1.
    l_bband : float
        AGN intrinsic disc B-band (4400 A) monochromatic luminosity [erg/s/Hz].
        When > 0, used directly in radio_agn_dpl instead of deriving from
        L_agn_bol bolometric correction. Default 0.0 (uses L_bol correction).

    Returns
    -------
    ndarray, shape (n_wave,)
        Spectral luminosity density [erg/s/Hz].

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.
    """
    t = radio_total_dpl_terms(
        wavelength,
        L_ir,
        L_agn_bol,
        q_ir,
        alpha_sf,
        radio_loudness,
        alpha1,
        alpha2,
        log_nu_t,
        log_nu_cut,
        sfr_mode,
        log_mstar,
        redshift,
        q0,
        mass_slope,
        z_slope,
        apply_suppression,
        include_freefree,
        T_e,
        alpha_ff,
        l_bband,
    )
    return t["sf"] + t["ff"] + t["agn"]


def compute_radio_components(
    wavelength: jnp.ndarray,
    L_ir: float = 0.0,
    L_agn_bol: float = 0.0,
    q_ir: float = 2.64,
    alpha_sf: float = 0.8,
    radio_loudness: float = 0.0,
    alpha_agn: float = 0.7,
    sfr_mode: str = "bell2003",
    log_mstar: float = 10.0,
    redshift: float = 0.0,
    q0: float | None = None,
    mass_slope: float | None = None,
    z_slope: float | None = None,
    apply_suppression: bool = True,
    include_freefree: bool = True,
    T_e: float = 1e4,
    alpha_ff: float = -0.1,
    **_kwargs,
) -> dict:
    """Decompose total radio emission into physical components.

    Returns a dict with individual component SEDs and their sum. Useful for
    visualizing the relative contribution of synchrotron, free-free, and AGN,
    and for computing thermal fractions (f_ff = freefree / total).

    Parameters
    ----------
    wavelength : array (n_wave,)
        Wavelength in Angstrom.
    L_ir : float
        IR luminosity (erg/s).
    L_agn_bol : float
        AGN bolometric luminosity (erg/s).
    q_ir : float
        FIR-radio q_IR (bell2003 mode only).
    alpha_sf : float
        Synchrotron spectral index.
    radio_loudness : float
        AGN radio-loudness log10(L_5GHz/L_B).
    alpha_agn : float
        AGN spectral index.
    sfr_mode : str
        SFR physics mode. See ``radio_total`` for options.
    log_mstar : float
        log10(M★/M⊙).
    redshift : float
        Galaxy redshift.
    q0, mass_slope, z_slope : float or None
        FIRRC parameter overrides.
    apply_suppression : bool
        Apply Bell+2003 synchrotron suppression.
    include_freefree : bool
        Include free-free component. Default True (diagnostic function).
    T_e : float
        Electron temperature for free-free. Default 1e4 K.
    alpha_ff : float
        Free-free spectral index. Default -0.1.

    Returns
    -------
    dict with keys:
        ``"synchrotron"`` : array (n_wave,); SFR synchrotron L_nu [erg/s/Hz]
        ``"freefree"`` : array (n_wave,): thermal free-free L_nu [erg/s/Hz]
        ``"agn"`` : array (n_wave,); AGN radio L_nu [erg/s/Hz]
        ``"total"`` : array (n_wave,): sum of above [erg/s/Hz]

    Notes
    -----
    **JIT-compatible**: yes, pure JAX function.
    """
    synchrotron = _dispatch_sfr(
        wavelength,
        L_ir,
        sfr_mode,
        q_ir,
        alpha_sf,
        log_mstar,
        redshift,
        q0,
        mass_slope,
        z_slope,
        apply_suppression,
    )
    agn = radio_agn(wavelength, L_agn_bol, radio_loudness, alpha_agn)
    ff = (
        radio_freefree(wavelength, L_ir, T_e, alpha_ff)
        if include_freefree
        else jnp.zeros_like(wavelength)
    )
    total = synchrotron + ff + agn
    return {"synchrotron": synchrotron, "freefree": ff, "agn": agn, "total": total}
