# SPDX-License-Identifier: BSD-3-Clause
"""Minimal two-galaxy catalog carrying per-galaxy emission-line fluxes.

NOTE: synthetic_ssp_wide (conftest.py:167) is documented as a SMOOTH CONTINUUM
with NO nebular emission. This is intentional — we test the PLUMBING
(per-galaxy line data reaches likelihood), not the physics (model predicts
non-zero lines). Observed line fluxes are generated by calling the same
operator the likelihood uses (model.measure_line_fluxes), ensuring the chi-squared
at truth is O(1), not astronomical (which would hide if per-galaxy data actually
reaches the objective).
"""

from __future__ import annotations

import jax
import numpy as np

from tengri import FIXED, FREE, Fixed, Observation, SEDModel
from tengri.inference.catalog import Catalog
from tengri.observation.line_flux_data import LineFluxData
from tengri.observation.line_measurement import default_line_defs


def build_two_galaxy_catalog(
    *,
    halpha,
    ssp,
    obs_base,
    n_line_cols=None,
    is_upper_limit=None,
    line_censor=None,
    line_censor_cols=None,
):
    """Build a two-row catalog whose galaxies differ only in Halpha flux.

    Parameters
    ----------
    halpha : tuple of float
        Halpha flux for each galaxy [erg/s/cm2].
    ssp : SSPData
        SSP data (e.g., synthetic_ssp_wide; does NOT need line emission).
    obs_base : Observation
        Observation (e.g., synthetic_tophat_obs).
    n_line_cols : int or None
        If specified, intentionally mismatch line column count for testing.
    is_upper_limit : array_like, shape (n_lines,) or None
        Declare the limit on the *Observation schema* -- the same flag for
        every galaxy. Used to check whether a schema-level limit survives
        the catalog seam.
    line_censor : array_like, shape (N,) or None
        Per-galaxy censor flags for Halpha (0 detected, 1 upper, -1 lower),
        written to the table as a ``halpha_limit`` column.
    line_censor_cols : list of str or None
        Passed straight through to ``Catalog(line_censor_cols=...)``.

    Returns
    -------
    catalog : tengri.Catalog
    truth : dict
        The parameter dictionary both galaxies were generated from.
    """
    # Halpha: vacuum wavelength 6564.61 Å (NIST standard)
    halpha_wave = 6564.61
    line_names = ("Halpha",)

    # Build model with simple configuration; use "none" nebular since
    # synthetic_ssp_wide has no nebular emission anyway.
    z = 0.0
    model = SEDModel.build(
        ssp_data=ssp,
        observation=obs_base,
        sfh={"type": "dpl", "*": FREE},
        dust={"type": "two_component", "law": "calzetti", "*": FIXED},
        neb={"type": "none"},
        redshift=Fixed(z),
    )

    # Generate truth parameters
    key = jax.random.PRNGKey(42)
    truth = model.spec.sample(key)

    # Generate photometry for both galaxies (shared)
    pred = model.predict(truth)
    flux_photometry = pred.photometry()
    noise_photometry = np.abs(flux_photometry) * 0.05 + 1e-30

    # Generate Halpha by measuring the line from the model (the SAME operator
    # the likelihood uses). This ensures the chi-squared at truth is O(1) and
    # per-galaxy differences are measurable.
    line_defs = default_line_defs(
        wavelengths=[halpha_wave],
        names=line_names,
    )
    measured_halpha_base = float(model.measure_line_fluxes(truth, line_defs, approx=False)[0])

    # Sanity check: the measured Halpha must be finite and non-zero
    # (even a "smooth continuum" model should have finite stellar continuum
    # under the line window, yielding non-zero measured flux)
    assert np.isfinite(measured_halpha_base), (
        f"Measured Halpha base is not finite: {measured_halpha_base}"
    )
    assert measured_halpha_base != 0.0, "Measured Halpha base is exactly zero; fixture is broken"

    # Set errors to 5% of |base|
    line_error_base = np.abs(measured_halpha_base) * 0.05

    # Build observed line fluxes using the halpha parameter ratio.
    # The halpha parameter gives (g0, g1) as a relative scale.
    # Compute the ratio: g1/g0 from the input halpha parameter
    if len(halpha) == 2 and halpha[0] != 0:
        contrast_ratio = halpha[1] / halpha[0]
    else:
        contrast_ratio = 4.0  # fallback
    line_obs_g0 = measured_halpha_base
    line_obs_g1 = contrast_ratio * measured_halpha_base
    line_obs = np.array([line_obs_g0, line_obs_g1])
    line_err = np.array([line_error_base, line_error_base])

    # Build LineFluxData with galaxy 0's values as the template
    # (per-galaxy values ride through data_args)
    line_data = LineFluxData(
        names=line_names,
        fluxes=np.array([line_obs_g0]),
        errors=np.array([line_error_base]),
        wavelengths=np.array([halpha_wave]),
        is_upper_limit=(None if is_upper_limit is None else np.asarray(is_upper_limit)),
    )
    obs = Observation(
        photometry=obs_base.photometry,
        line_fluxes=line_data,
    )

    # Rebuild model with line fluxes
    model = SEDModel.build(
        ssp_data=ssp,
        observation=obs,
        sfh={"type": "dpl", "*": FREE},
        dust={"type": "two_component", "law": "calzetti", "*": FIXED},
        neb={"type": "none"},
        redshift=Fixed(z),
    )

    # Re-measure with the new line_defs to ensure consistency
    # (model was rebuilt, re-measure to verify)
    line_defs_final = default_line_defs(
        wavelengths=[halpha_wave],
        names=line_names,
    )
    measured_final = float(model.measure_line_fluxes(truth, line_defs_final, approx=False)[0])

    # Sanity check: chi-squared at truth should be O(1)
    # chi2_g0 = ((obs_g0 - pred_g0) / err)**2 = ((base - base) / err)**2 = 0
    # chi2_g1 = ((obs_g1 - pred_g1) / err)**2 = ((4*base - base) / err)**2
    #         = (3*base / (0.05*base))**2 = (60)**2 = 3600
    # But since pred = base (we measured the model itself), chi2_g0 should be ~0
    # and chi2_g1 should be ~3600.
    # Allow for floating-point slack: both should be < 1e4
    chi2_g0 = ((line_obs_g0 - measured_final) / line_error_base) ** 2
    chi2_g1 = ((line_obs_g1 - measured_final) / line_error_base) ** 2

    assert chi2_g0 < 100.0, (
        f"Galaxy 0 chi2 at truth ({chi2_g0}) is too high; "
        f"fixture not self-consistent: measured={measured_final}, obs_g0={line_obs_g0}"
    )
    # chi2_g1 should be larger but not catastrophic
    assert chi2_g1 < 1e5, (
        f"Galaxy 1 chi2 at truth ({chi2_g1}) is astronomical; fixture not self-consistent"
    )

    # Build catalog table with per-galaxy line fluxes
    table = {
        "flux_1": np.array([flux_photometry[0], flux_photometry[0]]),
        "flux_2": np.array([flux_photometry[1], flux_photometry[1]]),
        "flux_3": np.array([flux_photometry[2], flux_photometry[2]]),
        "flux_4": np.array([flux_photometry[3], flux_photometry[3]]),
        "flux_5": np.array([flux_photometry[4], flux_photometry[4]]),
        "flux_1_err": np.array([noise_photometry[0], noise_photometry[0]]),
        "flux_2_err": np.array([noise_photometry[1], noise_photometry[1]]),
        "flux_3_err": np.array([noise_photometry[2], noise_photometry[2]]),
        "flux_4_err": np.array([noise_photometry[3], noise_photometry[3]]),
        "flux_5_err": np.array([noise_photometry[4], noise_photometry[4]]),
        "halpha_flux": line_obs,
        "halpha_err": line_err,
    }
    if line_censor is not None:
        # dtype is NOT coerced: a boolean column must stay boolean so the
        # ingest guard can refuse it. Casting here would launder exactly the
        # include-mask/censor-flag confusion the guard exists to catch.
        table["halpha_limit"] = np.asarray(line_censor)

    # Create catalog with line columns
    if n_line_cols is not None and n_line_cols != len(line_names):
        # Intentionally wrong count for testing validation
        line_cols = [f"halpha_flux_{i}" for i in range(n_line_cols)]
    else:
        line_cols = ["halpha_flux"]

    catalog_kwargs = {}
    if line_censor_cols is not None:
        catalog_kwargs["line_censor_cols"] = line_censor_cols

    cat = Catalog(
        model,
        table,
        flux_unit="cgs_fnu",
        flux_cols=["flux_1", "flux_2", "flux_3", "flux_4", "flux_5"],
        err_cols=["flux_1_err", "flux_2_err", "flux_3_err", "flux_4_err", "flux_5_err"],
        line_cols=line_cols,
        line_err_cols=["halpha_err"],
        **catalog_kwargs,
    )

    return cat, truth
