# SPDX-License-Identifier: BSD-3-Clause
"""Contract: an SFH parameter's short key is its name minus the *whole* type prefix.

The nested-dict grammar lets a user write ``sfh={'type': 'dpl', 'tau_gyr': ...}``
instead of the full ``sfh_dpl_tau_gyr``. The short key is derived by stripping
the group prefix, and the derivation used to split at the **first** underscore
after ``sfh_``. That is only correct when the type's public prefix is a single
token. Several registered types spell theirs with two or three::

    sfh_declining_exp_tau_gyr   -> 'exp_tau_gyr'        (wanted 'tau_gyr')
    sfh_snorm_burst_burst_sfr   -> 'burst_burst_sfr'    (wanted 'burst_sfr')
    sfh_delayed_bq_age_bq_gyr   -> 'bq_age_bq_gyr'      (wanted 'age_bq_gyr')
    sfh_top_hat_t_start_gyr     -> 'hat_t_start_gyr'    (wanted 't_start_gyr')
    sfh_gaussian_burst_sigma_gyr-> 'burst_sigma_gyr'    (wanted 'sigma_gyr')

so the documented short spelling was rejected outright ("Unknown key
'tau_gyr' in group 'sfh'"), and the "Did you mean" line steered the user to
the mangled name instead. Six of the twenty-odd registered SFH types were
unreachable by their own short keys.

These tests pin three things:

1. a hand-written table of ``full name -> short key`` for the multi-token
   types **and** for the single-token abbreviations that already worked
   (``sfh_dir_``, ``sfh_cont_``, ``sfh_field_``, ``sfh_dpl_``) — the
   abbreviations are the regression risk of any prefix-stripping rewrite,
   and ``sfh_field_psd_sigma`` in particular must stay ``'psd_sigma'``
   rather than becoming ``'sigma'``;
2. short -> full round-trips through the *real* grammar (``parse_groups`` and
   its inverse ``parameters_to_groups``) for every parameter of every
   forward-modelable SFH type;
3. the public build path: the short key actually changes the SFH.
"""

import numpy as np
import pytest

from tengri import DEFAULT, FREE, Fixed, SEDModel, builders
from tengri.components.stellar.sfh.registry import SFH_REGISTRY
from tengri.parameters.groups import (
    _extract_short_name,
    _valid_sfh_types,
    parameters_to_groups,
    parse_groups,
)

pytestmark = pytest.mark.contract


# ── 1. hand-written expectations ───────────────────────────────────
#
# Written out by hand from the registry's *published* parameter names
# (``tengri.describe(<type>)`` prints them), NOT derived from the stripping
# rule under test: a table generated by the implementation would agree with
# any implementation, including the broken one.
EXPECTED_SHORT_NAMES = [
    # multi-token type prefixes -- the defect
    ("declining_exp", "sfh_declining_exp_log_total_mass", "log_total_mass"),
    ("declining_exp", "sfh_declining_exp_tau_gyr", "tau_gyr"),
    ("declining_exp", "sfh_declining_exp_age_gyr", "age_gyr"),
    ("snorm_burst", "sfh_snorm_burst_log_total_mass", "log_total_mass"),
    ("snorm_burst", "sfh_snorm_burst_burst_sfr", "burst_sfr"),
    ("snorm_burst", "sfh_snorm_burst_burst_age_gyr", "burst_age_gyr"),
    ("snorm_burst", "sfh_snorm_burst_skew", "skew"),
    ("tsnorm_burst", "sfh_tsnorm_burst_trunc", "trunc"),
    ("tsnorm_burst", "sfh_tsnorm_burst_burst_sfr", "burst_sfr"),
    ("delayed_bq", "sfh_delayed_bq_age_bq_gyr", "age_bq_gyr"),
    ("delayed_bq", "sfh_delayed_bq_age_main_gyr", "age_main_gyr"),
    ("delayed_bq", "sfh_delayed_bq_r_sfr", "r_sfr"),
    ("top_hat", "sfh_top_hat_t_start_gyr", "t_start_gyr"),
    ("top_hat", "sfh_top_hat_smooth_width_gyr", "smooth_width_gyr"),
    ("gaussian_burst", "sfh_gaussian_burst_sigma_gyr", "sigma_gyr"),
    ("gaussian_burst", "sfh_gaussian_burst_t_peak_gyr", "t_peak_gyr"),
    # single-token prefixes that already worked and must keep working
    ("field", "sfh_field_psd_sigma", "psd_sigma"),
    ("field", "sfh_field_psd_tau_myr", "psd_tau_myr"),
    ("dirichlet", "sfh_dir_z_0", "z_0"),
    ("dirichlet", "sfh_dir_log_total_mass", "log_total_mass"),
    ("continuity", "sfh_cont_ratio_3", "ratio_3"),
    ("const_exp", "sfh_cexp_quench_gyr", "quench_gyr"),
    ("psb_suess2022", "sfh_psb2022_ratio_old_1", "ratio_old_1"),
    ("dense_basis", "sfh_db_tx_frac_0", "tx_frac_0"),
    ("dpl", "sfh_dpl_alpha", "alpha"),
    ("dpl", "sfh_dpl_log_total_mass", "log_total_mass"),
    ("delayed", "sfh_delayed_tau_gyr", "tau_gyr"),
    ("snorm", "sfh_snorm_skew", "skew"),
    ("tsnorm", "sfh_tsnorm_trunc", "trunc"),
    ("burst", "sfh_burst_log_fburst", "log_fburst"),
    ("sfh2exp", "sfh_sfh2exp_burst_age_gyr", "burst_age_gyr"),
]


@pytest.mark.parametrize(("sfh_type", "full", "short"), EXPECTED_SHORT_NAMES)
def test_short_name_strips_the_whole_type_prefix(sfh_type, full, short):
    """``_extract_short_name`` drops the full ``sfh_<type>_`` prefix, no more, no less."""
    assert full in SFH_REGISTRY[sfh_type].params, (
        f"{full!r} is no longer a declared parameter of {sfh_type!r}; "
        "this table transcribes the registry and must be updated with it"
    )
    # ``_short_names_for_group`` calls with an empty dict, so the derivation
    # has to work from the parameter name alone.
    assert _extract_short_name(full, {}) == short
    # ...and must not change when the group dict names the type.
    assert _extract_short_name(full, {"type": sfh_type}) == short


def test_no_two_parameters_of_one_type_collapse_to_the_same_short_key():
    """A collision would make one of the two silently unreachable."""
    collisions = {}
    for name in sorted(SFH_REGISTRY):
        params = tuple(SFH_REGISTRY[name].params)
        shorts = [_extract_short_name(p, {}) for p in params]
        if len(set(shorts)) != len(shorts):
            collisions[name] = shorts
    assert not collisions, collisions


# ── 2. short -> full through the real grammar ──────────────────────
#
# ``burst`` and ``field`` are composable components, not standalone SFHs
# ("At least one additive (smooth) SFH component required"), so they are
# exercised composed with ``dpl``.
_COMPOSE_WITH_DPL = frozenset({"burst", "field"})


def _sfh_types_the_builder_accepts():
    """Registered SFH types that ``parse_groups`` will actually build."""
    return sorted(t for t in _valid_sfh_types() if SFH_REGISTRY[t].params)


def _sfh_type_value(sfh_type):
    return ["dpl", sfh_type] if sfh_type in _COMPOSE_WITH_DPL else sfh_type


@pytest.mark.parametrize("sfh_type", _sfh_types_the_builder_accepts())
def test_every_short_key_resolves_back_to_its_full_parameter(sfh_type):
    """Writing every parameter by its short key sets every full parameter.

    The inverse direction is ``parse_groups`` itself: it walks the declared
    full names and looks each one up in the user's group dict by its short
    spelling. Provenance records which lookups hit, so an unresolved short
    key shows up as ``registry_default`` rather than ``user_*``.
    """
    params = tuple(SFH_REGISTRY[sfh_type].params)
    group = {"type": _sfh_type_value(sfh_type), "all_params": Fixed(DEFAULT)}
    for full in params:
        group[_extract_short_name(full, {})] = Fixed(DEFAULT)

    spec = parse_groups(sfh=group, redshift=Fixed(0.05))
    provenance = spec._group_provenance

    unresolved = {
        full: provenance.get(full)
        for full in params
        if not str(provenance.get(full)).startswith("user")
    }
    assert not unresolved, (
        f"short keys for {sfh_type!r} did not reach these parameters: {unresolved}"
    )


@pytest.mark.parametrize("sfh_type", _sfh_types_the_builder_accepts())
def test_parameters_to_groups_round_trips_through_parse_groups(sfh_type):
    """full -> short (emitter) -> full (parser) reproduces the same Parameters."""
    forward = parse_groups(
        sfh={"type": _sfh_type_value(sfh_type), "all_params": FREE},
        redshift=Fixed(0.05),
    )
    groups = parameters_to_groups(forward)
    back = parse_groups(**groups)

    assert set(back.free_params) == set(forward.free_params)
    for name in forward.all_params:
        assert repr(back.get_distribution(name)) == repr(forward.get_distribution(name)), name


@pytest.mark.parametrize("sfh_type", _sfh_types_the_builder_accepts())
def test_builder_factory_kwargs_are_the_keys_the_parser_accepts(sfh_type):
    """``builders.sfh.<type>`` must emit keys ``parse_groups`` recognizes.

    The factory signatures are generated from the same registry, so a
    divergent short-name rule on either side makes every factory call for the
    affected type raise -- either a ``TypeError`` on the kwarg or an "Unknown
    key" ``ValueError`` one step later.
    """
    factory = getattr(builders.sfh, sfh_type)
    kwargs = {
        _extract_short_name(full, {}): Fixed(DEFAULT) for full in SFH_REGISTRY[sfh_type].params
    }
    group = factory(all_params=Fixed(DEFAULT), **kwargs)
    if sfh_type in _COMPOSE_WITH_DPL:
        group = {**group, "type": _sfh_type_value(sfh_type)}

    spec = parse_groups(sfh=group, redshift=Fixed(0.05))
    provenance = spec._group_provenance
    unresolved = [
        full
        for full in SFH_REGISTRY[sfh_type].params
        if not str(provenance.get(full)).startswith("user")
    ]
    assert not unresolved, unresolved


# ── 3. the public build path ───────────────────────────────────────

# (type, short key, non-default value, a second value used for the default build)
PUBLIC_CASES = [
    ("declining_exp", "tau_gyr", 0.3),
    ("snorm_burst", "burst_sfr", 12.0),
    ("delayed_bq", "age_bq_gyr", 0.9),
]


def _sfr_history(ssp, sfh_group):
    model = SEDModel.build(ssp_data=ssp, sfh=sfh_group, redshift=Fixed(0.05))
    return np.asarray(model.predict_state({}).derived["sfr_history"])


@pytest.mark.parametrize(("sfh_type", "short", "value"), PUBLIC_CASES)
def test_short_key_reaches_the_forward_model(ssp_data_fsps, sfh_type, short, value):
    """``SEDModel.build(sfh={'type': t, <short>: ...})`` builds and changes the SFH."""
    base = _sfr_history(ssp_data_fsps, {"type": sfh_type, "all_params": Fixed(DEFAULT)})
    got = _sfr_history(
        ssp_data_fsps,
        {"type": sfh_type, "all_params": Fixed(DEFAULT), short: Fixed(value)},
    )
    frac = np.max(np.abs(got - base) / np.maximum(np.abs(base), 1e-30))
    assert frac > 0.01, (
        f"sfh={{'type': {sfh_type!r}, {short!r}: Fixed({value})}} produced an SFH "
        f"within {frac:.3g} of the default build -- the short key was ignored"
    )
