# SPDX-License-Identifier: BSD-3-Clause
"""Pin ``data/dale2014_templates.h5`` to the official Wyoming source.

The historical template file shipped pre-#415 was generated from a
now-missing intermediate (`dale2014_templates.npz`) and its per-α shapes
diverged from Dale's official distribution by 6 — 1000× at sub-mm
wavelengths. The file is now regenerated by
``scripts/regenerate_dale2014_from_official.py`` directly from

    https://physics.uwyo.edu/~ddale/research/seds/spectra.SFAGN.tar.gz

These tests pin a handful of canonical (α, λ) → L_ν values so any future
regeneration that drifts from the official source is caught at CI time.
"""

from __future__ import annotations

import pathlib

import h5py
import numpy as np
import pytest

pytestmark = pytest.mark.contract


TEMPLATE_PATH = pathlib.Path(__file__).parents[2] / "data" / "dale2014_templates.h5"

# Reference values are the L_ν templates after normalisation to ∫dν=1,
# read off the regenerated file at the listed (α=2.0, λ) points. They
# correspond directly to ``10**col / ν`` from spectra.0.00AGN.dat / ∫dν,
# so the figures below are paper-traceable up to the per-template
# bolometric normalisation.
_ALPHA_2P0_REFERENCE: tuple[tuple[float, float], ...] = (
    (1.0000e05, 2.003867e-15),  # 10 μm, MIR PAH region
    (9.0000e05, 1.586395e-13),  # 90 μm, near the FIR peak
    (5.1800e06, 9.202349e-15),  # 518 μm, sub-mm
    (1.1000e07, 6.252614e-16),  # 1.1 mm, FIR — radio crossover
)


@pytest.fixture(scope="module")
def template_arrays() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if not TEMPLATE_PATH.is_file():
        pytest.skip(f"Dale2014 template file not present at {TEMPLATE_PATH}")
    with h5py.File(TEMPLATE_PATH) as f:
        wave = np.asarray(f["wavelength_aa"][:])
        alpha = np.asarray(f["alpha_grid"][:])
        spectra = np.asarray(f["templates_sf"][:])
    return wave, alpha, spectra


def test_grid_shape(template_arrays):
    """Wyoming source ships 64 α templates on 1496 wavelength points."""
    wave, alpha, spectra = template_arrays
    assert wave.shape == (1496,)
    assert alpha.shape == (64,)
    assert spectra.shape == (64, 1496)


def test_alpha_grid_uniform_step(template_arrays):
    """α grid is uniform 0.0625 → 4.0000 in 0.0625 steps (paper-fixed)."""
    _, alpha, _ = template_arrays
    np.testing.assert_allclose(alpha[0], 0.0625)
    np.testing.assert_allclose(alpha[-1], 4.0)
    np.testing.assert_allclose(np.diff(alpha), 0.0625, atol=1e-10)


def test_wavelength_range(template_arrays):
    """Wavelength grid spans the canonical Dale support: 360 nm → 225 m."""
    wave, _, _ = template_arrays
    np.testing.assert_allclose(wave[0], 3600.0)
    # Last point is the radio extension; just check we're past the FIR.
    assert wave[-1] > 1e9


def test_alpha_2p0_canonical_lnu_values(template_arrays):
    """L_ν at α=2.0 must match the Wyoming-source-derived reference.

    A 0.5 % tolerance lets future regenerations vary trapezoid round-off
    without masking shape regressions. Any drift larger than that means
    either the source file changed upstream or the conversion logic in
    ``scripts/regenerate_dale2014_from_official.py`` was modified — both
    deserve human review.
    """
    wave, alpha, spectra = template_arrays
    ia = int(np.argmin(np.abs(alpha - 2.0)))
    assert abs(alpha[ia] - 2.0) < 1e-10
    for lam, expected in _ALPHA_2P0_REFERENCE:
        iw = int(np.argmin(np.abs(wave - lam)))
        observed = float(spectra[ia, iw])
        np.testing.assert_allclose(
            observed,
            expected,
            rtol=5e-3,
            err_msg=(
                f"Dale2014 α=2.0 template drift at λ={lam:.3e} Å "
                f"(observed {observed:.6e} vs Wyoming reference {expected:.6e})."
            ),
        )


def test_each_alpha_integrates_to_unity(template_arrays):
    """Every template must obey ∫L_ν dν = 1 — energy balance contract."""
    wave, alpha, spectra = template_arrays
    c_aa = 2.998e18  # Å/s (matches tengri runtime)
    nu = c_aa / wave
    order = np.argsort(nu)
    nu_sorted = nu[order]
    for i, a in enumerate(alpha):
        integral = float(np.trapezoid(spectra[i, order], nu_sorted))
        np.testing.assert_allclose(
            integral,
            1.0,
            rtol=2e-3,
            err_msg=(
                f"α={a} template integrates to {integral:.6f}, not 1.0; "
                "tengri's runtime path multiplies by L_absorbed and assumes "
                "this is exactly unity."
            ),
        )


def test_file_provenance_attrs(template_arrays):
    """HDF5 attributes must record the official Wyoming source URL."""
    with h5py.File(TEMPLATE_PATH) as f:
        source = f.attrs.get("source", "")
    assert "physics.uwyo.edu" in str(source), (
        f"Dale2014 template file does not declare its Wyoming-source provenance "
        f"(source attr = {source!r}). Regenerate via "
        f"`python scripts/regenerate_dale2014_from_official.py`."
    )
