# SPDX-License-Identifier: BSD-3-Clause
"""Contract tests for dust IR emission models with CIGALE parity.

Each new CIGALE-derived knob is checked for three things:

1. its default reproduces the prior (back-compatible) output;
2. changing it demonstrably moves the SED in the CIGALE-predicted direction
   (a guard against silently-unwired "no-op" parameters);
3. it is JAX ``grad`` / ``jit`` safe.

Tests run against the shipped template files (``data/*.h5``) generated by
``scripts/regenerate_*_from_cigale.py``; they skip if a file is absent.

References
----------
.. [1] Jones, A.P. et al. 2017, A&A, 602, A46 (THEMIS).
.. [2] Dale, D.A. et al. 2014, ApJ 784, 83 (Dale2014).
.. [3] Schreiber, C. et al. 2016, A&A, 609, A30 (Schreiber2016).
"""

from __future__ import annotations

import os

import jax
import jax.numpy as jnp
import numpy as np
import pytest

jax.config.update("jax_enable_x64", True)

pytestmark = pytest.mark.contract

# Wavelength grid inside the dust-IR template coverage (~1 µm to 3 mm).
WAVE = jnp.geomspace(1e4, 3e7, 400)
NU = 2.998e18 / WAVE
ORDER = jnp.argsort(NU)


def _bolometric(sed):
    """Frequency-integrated luminosity (sorted, sign-safe)."""
    return float(jnp.abs(jnp.trapezoid(sed[ORDER], NU[ORDER])))


def _require(path):
    if not os.path.exists(path):
        pytest.skip(f"template file {path} not available")
    return path


# NOTE: THEMIS radiation-field slope (dust_alpha) is intentionally not tested
# / not exposed — tengri ships the FSPS/DustEM THEMIS templates (alpha=2.0
# only, PR #574); an alpha axis needs CIGALE-sourced data (follow-up).


# ── Dale2014: AGN fraction (additive AGN power source) ────────────


class TestDale2014FracAGN:
    """Dale2014 SF + quasar mixing: SED = L*SF + L*f/(1-f)*QSO."""

    def _fn(self):
        from tengri.components.dust.emission_templates import create_dale2014_from_grid

        return create_dale2014_from_grid(_require("data/dale2014_templates_cigale.h5"))

    def test_default_fracagn_zero_is_sf_only(self):
        fn = self._fn()
        sf = fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.0)
        assert jnp.all(jnp.isfinite(sf))
        assert jnp.any(sf > 0)

    def test_fracagn_additive_increases_total_ir(self):
        """AGN is a separate power source: total IR grows with frac_agn."""
        fn = self._fn()
        l0 = _bolometric(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.0))
        l5 = _bolometric(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.5))
        assert l5 > l0 * 1.2, "frac_agn does not add AGN dust power"

    def test_fracagn_jit_and_grad(self):
        fn = self._fn()

        @jax.jit
        def total(f):
            return jnp.sum(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=f))

        assert jnp.isfinite(total(0.3))
        assert jnp.isfinite(jax.grad(total)(0.3))


# ── Schreiber2016: tabulated continuum + PAH ──────────────────────


class TestSchreiber2016Tabulated:
    """Tabulated Schreiber+2016 templates (tdust, fpah), CIGALE-faithful."""

    def _component(self):
        from tengri.components.dust.emission_templates import load_schreiber2016_templates
        from tengri.components.dust.schreiber2016_ir import Schreiber2016IRSEDComponent

        comp = Schreiber2016IRSEDComponent()
        data = load_schreiber2016_templates(_require("data/schreiber2016_templates.h5"))
        object.__setattr__(comp, "data", data)
        return comp

    def _sed(self, comp, tdust, fpah):
        sed_out, _ = comp.predict(
            {"tdust": tdust, "fpah": fpah}, jnp.zeros_like(WAVE), WAVE, L_ir=1.0
        )
        return sed_out

    def test_default_finite_positive(self):
        sed = self._sed(self._component(), 25.0, 0.05)
        assert jnp.all(jnp.isfinite(sed))
        assert jnp.any(sed > 0)

    def test_tdust_shifts_peak(self):
        comp = self._component()
        cold = self._sed(comp, 20.0, 0.05)
        hot = self._sed(comp, 50.0, 0.05)
        # Hotter dust peaks at shorter wavelength.
        lam_cold = float(WAVE[jnp.argmax(cold)])
        lam_hot = float(WAVE[jnp.argmax(hot)])
        assert lam_hot < lam_cold

    def test_fpah_changes_sed(self):
        comp = self._component()
        s0 = self._sed(comp, 30.0, 0.0)
        s5 = self._sed(comp, 30.0, 0.5)
        # Relative metric: the SED is tiny in absolute erg/s/Hz, so a plain
        # allclose (atol=1e-8) would falsely call them equal.
        rel = float(jnp.max(jnp.abs(s0 - s5)) / (jnp.max(jnp.abs(s0)) + 1e-300))
        assert rel > 1e-2, f"fpah is a no-op (max frac change {rel:.2e})"

    def test_fpah_jit_and_grad(self):
        comp = self._component()

        @jax.jit
        def total(fpah):
            return jnp.sum(self._sed(comp, 30.0, fpah))

        assert jnp.isfinite(total(0.1))
        assert jnp.isfinite(jax.grad(total)(0.1))


# ── Modified blackbody: epsilon_mbb luminosity fraction ───────────


class TestModifiedBlackbodyEpsilon:
    """CIGALE mbb epsilon_mbb: fraction of L_dust carried by the MBB."""

    def _component(self):
        from tengri.components.dust.modified_blackbody_ir import ModifiedBlackbodySED

        return ModifiedBlackbodySED()

    def _sed(self, comp, epsilon):
        sed_out, _ = comp.predict(
            {"T": 35.0, "beta_ir": 1.8, "epsilon_mbb": epsilon},
            jnp.zeros_like(WAVE),
            WAVE,
            L_ir=1.0,
        )
        return sed_out

    def test_epsilon_default_one_full_luminosity(self):
        sed = self._sed(self._component(), 1.0)
        assert jnp.all(jnp.isfinite(sed))
        assert jnp.any(sed > 0)

    def test_epsilon_scales_luminosity_linearly(self):
        comp = self._component()
        full = _bolometric(self._sed(comp, 1.0))
        half = _bolometric(self._sed(comp, 0.5))
        assert np.isclose(half, 0.5 * full, rtol=1e-3)

    def test_epsilon_jit_and_grad(self):
        comp = self._component()

        @jax.jit
        def total(eps):
            return jnp.sum(self._sed(comp, eps))

        assert jnp.isfinite(total(0.5))
        assert jnp.isfinite(jax.grad(total)(0.5))
