# SPDX-License-Identifier: BSD-3-Clause
"""Contract tests for #337 — bin_edges_gyr plumbing through the nested-dict grammar.

PR #324 registered ``prospector_beta`` as a faithful continuity-shape SFH
with the published Leja+2019 ``StudentT(0, 0.3, df=2)`` prior. The
defining feature of Prospector-β (Wang+2024, arXiv:2401.12198) is
**redshift-dependent bin edges** generated by
``make_agebins_from_zred(zred)``. Until this PR, the nested-dict
grammar silently dropped the ``bin_edges_gyr`` key — ``prospector_beta``
was reachable by name but couldn't actually be invoked with the
redshift-aware edges that are the whole point of the model.

This PR adds the plumbing: ``_translate_sfh`` forwards
``sfh['bin_edges_gyr']`` to a top-level ``Parameters`` kwarg, which is
popped into ``spec.bin_edges_gyr`` and threaded through
``SEDModel._init_sfh`` to ``resolve_sfh(..., bin_edges_gyr=...)``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

import tengri
from tengri.parameters.groups import Fixed, parse_groups

pytestmark = pytest.mark.contract

_DATA_DIR = Path(__file__).resolve().parents[2] / "data"
_SSP_FILE = _DATA_DIR / "ssp_prsc_miles_chabrier_wNE_logGasU-3.0_logGasZ0.0.h5"


@pytest.fixture(scope="module")
def ssp():
    if not _SSP_FILE.is_file():
        pytest.skip(f"SSP file not present: {_SSP_FILE}")
    return tengri.load_ssp()


@pytest.fixture(scope="module")
def edges_z2():
    """Canonical edges for a z=2 source."""
    return tengri.make_agebins_from_zred(zred=2.0)


class TestGrammarPlumbing:
    """``sfh={'type': 'prospector_beta', 'bin_edges_gyr': edges}`` reaches Parameters."""

    def test_grammar_accepts_bin_edges_gyr(self, edges_z2):
        params = parse_groups(
            sfh={"type": "prospector_beta", "*": tengri.FIXED, "bin_edges_gyr": edges_z2},
            redshift=Fixed(2.0),
        )
        np.testing.assert_array_equal(params.bin_edges_gyr, edges_z2)

    def test_default_is_none(self):
        """When ``bin_edges_gyr`` is not supplied the registry default is used."""
        params = parse_groups(
            sfh={"type": "prospector_beta", "*": tengri.FIXED},
            redshift=Fixed(2.0),
        )
        assert params.bin_edges_gyr is None

    def test_legacy_kwarg_path_works(self, edges_z2):
        """Expert escape hatch — direct ``Parameters(...)`` accepts the kwarg too."""
        from tengri import Parameters

        spec = Parameters(
            mean_sfh_type="prospector_beta",
            bin_edges_gyr=edges_z2,
            redshift=Fixed(2.0),
        )
        np.testing.assert_array_equal(spec.bin_edges_gyr, edges_z2)

    def test_bin_edges_gyr_is_recognised_neb_key(self, edges_z2):
        """No raise = key is accepted by the unknown-key validator."""
        parse_groups(
            sfh={"type": "prospector_beta", "*": tengri.FIXED, "bin_edges_gyr": edges_z2},
            redshift=Fixed(2.0),
        )


class TestForwardPassPropagation:
    """``SEDModel.build`` actually wires the edges into the SFH function."""

    def test_build_uses_supplied_edges(self, ssp, edges_z2):
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = tengri.SEDModel.build(
                ssp,
                sfh={"type": "prospector_beta", "*": tengri.FIXED, "bin_edges_gyr": edges_z2},
                dust={"type": "two_component", "*": tengri.FIXED},
                redshift=tengri.Fixed(2.0),
            )
        # Edges live on the spec…
        np.testing.assert_array_equal(model.spec.bin_edges_gyr, edges_z2)
        # …and the closure SEDModel built actually points at the
        # resolve_sfh that received them (no exception is the contract).

    def test_default_edges_when_unspecified(self, ssp):
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = tengri.SEDModel.build(
                ssp,
                sfh={"type": "prospector_beta", "*": tengri.FIXED},
                dust={"type": "two_component", "*": tengri.FIXED},
                redshift=tengri.Fixed(2.0),
            )
        assert model.spec.bin_edges_gyr is None


class TestOtherNonparametricSfhs:
    """The same path must work for the other ``_NONPARAM_NAMES`` entries."""

    @pytest.mark.parametrize(
        "sfh_type",
        ["continuity", "continuity_flex", "dirichlet", "bursty_continuity"],
    )
    def test_continuity_family_accepts_edges(self, sfh_type):
        """All non-parametric variants accept the override at the grammar layer."""
        edges = np.array([0.0, 0.03, 0.1, 0.5, 1.0, 3.0, 10.0, 13.6])
        params = parse_groups(
            sfh={"type": sfh_type, "*": tengri.FIXED, "bin_edges_gyr": edges},
            redshift=Fixed(0.5),
        )
        np.testing.assert_array_equal(params.bin_edges_gyr, edges)
