# SPDX-License-Identifier: BSD-3-Clause
"""Contract tests for #337 — bin_edges_gyr plumbing through the nested-dict grammar.

The defining feature of redshift-aware non-parametric SFHs (Wang+2024
Prospector-β, arXiv:2401.12198) is **redshift-dependent bin edges**
generated by ``make_agebins_from_zred(zred)``. Until #324/#337 the
nested-dict grammar silently dropped the ``bin_edges_gyr`` key, so a
binned SFH was reachable by name but couldn't be invoked with the
redshift-aware edges that are the whole point of the model.

This PR adds the plumbing: ``_translate_sfh`` forwards
``sfh['bin_edges_gyr']`` to a top-level ``Parameters`` kwarg, which is
popped into ``spec.bin_edges_gyr`` and threaded through
``SEDModel._init_sfh`` to ``resolve_sfh(..., bin_edges_gyr=...)``.

These tests exercise the plumbing via ``continuity_flex`` — a
DSPS-validated non-parametric SFH (see ``_SUPPORTED_SFH`` in
``components/stellar/component.py``). ``prospector_beta``, the original
motivating model, is registered but **not yet validated against the
DSPS forward path** (``UNVALIDATED_SFH_TYPES``), so the grammar now
rejects it; that gating is asserted in
``tests/contract/test_gated_sfh_and_pah_alias.py``.
"""

from __future__ import annotations

import numpy as np
import pytest

import tengri
from tengri.parameters.groups import Fixed, parse_groups

pytestmark = pytest.mark.contract

# A DSPS-validated non-parametric SFH that accepts redshift-aware bin edges.
_SFH = "continuity_flex"


@pytest.fixture(scope="module")
def ssp(synthetic_ssp_wide):
    # #613: the forward-pass plumbing checks only read spec attributes, so the
    # shared synthetic SSP lets them run on CI instead of skipping on missing data.
    return synthetic_ssp_wide


@pytest.fixture(scope="module")
def edges_z2():
    """Canonical edges for a z=2 source."""
    return tengri.make_agebins_from_zred(zred=2.0)


class TestGrammarPlumbing:
    """``sfh={'type': 'continuity_flex', 'bin_edges_gyr': edges}`` reaches Parameters."""

    def test_grammar_accepts_bin_edges_gyr(self, edges_z2):
        params = parse_groups(
            sfh={"type": _SFH, "all_params": tengri.FIXED, "bin_edges_gyr": edges_z2},
            redshift=Fixed(2.0),
        )
        np.testing.assert_array_equal(params.bin_edges_gyr, edges_z2)

    def test_default_is_none(self):
        """When ``bin_edges_gyr`` is not supplied the registry default is used."""
        params = parse_groups(
            sfh={"type": _SFH, "all_params": tengri.FIXED},
            redshift=Fixed(2.0),
        )
        assert params.bin_edges_gyr is None

    def test_legacy_kwarg_path_works(self, edges_z2):
        """Expert escape hatch — direct ``Parameters(...)`` accepts the kwarg too."""
        from tengri import Parameters

        spec = Parameters(
            mean_sfh_type=_SFH,
            bin_edges_gyr=edges_z2,
            redshift=Fixed(2.0),
        )
        np.testing.assert_array_equal(spec.bin_edges_gyr, edges_z2)

    def test_bin_edges_gyr_is_recognized_neb_key(self, edges_z2):
        """No raise = key is accepted by the unknown-key validator."""
        parse_groups(
            sfh={"type": _SFH, "all_params": tengri.FIXED, "bin_edges_gyr": edges_z2},
            redshift=Fixed(2.0),
        )


class TestForwardPassPropagation:
    """``SEDModel.build`` actually wires the edges into the SFH function."""

    def test_build_uses_supplied_edges(self, ssp, edges_z2):
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = tengri.SEDModel.build(
                ssp,
                sfh={"type": _SFH, "all_params": tengri.FIXED, "bin_edges_gyr": edges_z2},
                dust_attenuation={
                    "law": "power_law",
                    "type": "two_component",
                    "all_params": tengri.FIXED,
                },
                redshift=tengri.Fixed(2.0),
            )
        # Edges live on the spec…
        np.testing.assert_array_equal(model.spec.bin_edges_gyr, edges_z2)
        # …and the closure SEDModel built actually points at the
        # resolve_sfh that received them (no exception is the contract).

    def test_default_edges_when_unspecified(self, ssp):
        import warnings

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = tengri.SEDModel.build(
                ssp,
                sfh={"type": _SFH, "all_params": tengri.FIXED},
                dust_attenuation={
                    "law": "power_law",
                    "type": "two_component",
                    "all_params": tengri.FIXED,
                },
                redshift=tengri.Fixed(2.0),
            )
        assert model.spec.bin_edges_gyr is None


class TestOtherNonparametricSfhs:
    """The same path must work for every DSPS-validated non-parametric variant."""

    @pytest.mark.parametrize(
        "sfh_type",
        ["continuity", "continuity_flex", "dirichlet"],
    )
    def test_continuity_family_accepts_edges(self, sfh_type):
        """All validated non-parametric variants accept the override at the grammar layer."""
        edges = np.array([0.0, 0.03, 0.1, 0.5, 1.0, 3.0, 10.0, 13.6])
        params = parse_groups(
            sfh={"type": sfh_type, "all_params": tengri.FIXED, "bin_edges_gyr": edges},
            redshift=Fixed(0.5),
        )
        np.testing.assert_array_equal(params.bin_edges_gyr, edges)
