# SPDX-License-Identifier: BSD-3-Clause
"""Contract tests for dust IR emission models with CIGALE parity.

Each new CIGALE-derived knob is checked for three things:

1. its default reproduces the prior (back-compatible) output;
2. changing it demonstrably moves the SED in the CIGALE-predicted direction
   (a guard against silently-unwired "no-op" parameters);
3. it is JAX ``grad`` / ``jit`` safe.

Tests run against the shipped template files (``data/*.h5``) generated by
``scripts/regenerate_*_from_cigale.py``; they skip if a file is absent.

References
----------
.. [1] Jones, A.P. et al. 2017, A&A, 602, A46 (THEMIS).
.. [2] Dale, D.A. et al. 2014, ApJ 784, 83 (Dale2014).
.. [3] Schreiber, C. et al. 2016, A&A, 609, A30 (Schreiber2016).
"""

from __future__ import annotations

import functools
import os

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from tests._grad_parity import assert_grad_matches_fd

pytestmark = pytest.mark.contract

# Wavelength grid inside the dust-IR template coverage (~1 µm to 3 mm).
WAVE = jnp.geomspace(1e4, 3e7, 400)
NU = 2.998e18 / WAVE
ORDER = jnp.argsort(NU)


def _bolometric(sed):
    """Frequency-integrated luminosity (sorted, sign-safe)."""
    return float(jnp.abs(jnp.trapezoid(sed[ORDER], NU[ORDER])))


def _require(path):
    if not os.path.exists(path):
        pytest.skip(f"template file {path} not available")
    return path


# ── shared template loaders ───────────────────────────────────────
#
# Each test used to rebuild its own loader. The loaders are pure functions of a
# path, so one entry serves the module -- which matters most for the
# parametrized gradient test below, where six cases would otherwise open the
# same three HDF5 grids six times.
#
# This is a redundancy fix, not a speed fix, and the distinction is worth
# recording because the first measurement suggested otherwise. The file was
# timed at 54 s before the change and 4.4 s after, but re-running the *original*
# under the same conditions also gives 4.4 s: the 54 s was a cold JAX compile
# cache, not repeated loading. Measured 2026-08-16, serial, warm cache: old
# 4.45 s, new 4.41 s. No speedup is claimed.
#
# ``pytest.skip`` raises, and ``lru_cache`` does not cache exceptions, so a
# missing grid still skips every test that needs it rather than being memoized
# into a false pass.


@functools.lru_cache(maxsize=1)
def _themis_engine():
    from tengri.components.dust.emission_templates import create_themis_from_grid

    return create_themis_from_grid(_require("data/themis_templates.h5"))


@functools.lru_cache(maxsize=1)
def _dale2014_engine():
    from tengri.components.dust.emission_templates import create_dale2014_from_grid

    return create_dale2014_from_grid(_require("data/dale2014_templates_cigale.h5"))


@functools.lru_cache(maxsize=1)
def _schreiber2016_component():
    from tengri.components.dust.emission_templates import load_schreiber2016_templates
    from tengri.components.dust.schreiber2016_ir import Schreiber2016IRSEDComponent

    comp = Schreiber2016IRSEDComponent()
    data = load_schreiber2016_templates(_require("data/schreiber2016_templates.h5"))
    object.__setattr__(comp, "data", data)
    return comp


# ── THEMIS: radiation-field slope alpha (FSPS-anchored hybrid grid) ──


class TestTHEMISAlphaAxis:
    """THEMIS alpha axis: FSPS template re-shaped by CIGALE's DustEM alpha grid.

    The alpha=2.0 default is anchored to the FSPS power-law bit-for-bit
    (``scripts/build_themis_alpha_axis.py``), so it reproduces the baseline;
    other alpha values must move the SED.
    """

    def _fn(self):
        return _themis_engine()

    def _sed(self, fn, alpha):
        return fn(WAVE, 1.0, dust_qhac=0.17, dust_umin=2.0, dust_gamma_dl=0.1, dust_alpha=alpha)

    def test_alpha_changes_fir_shape(self):
        fn = self._fn()
        s1, s3 = self._sed(fn, 1.0), self._sed(fn, 3.0)
        assert jnp.all(jnp.isfinite(s1)) and jnp.any(s1 > 0)
        rel = float(jnp.max(jnp.abs(s1 - s3)) / (jnp.max(jnp.abs(s1)) + 1e-300))
        assert rel > 1e-2, f"dust_alpha is a no-op (max frac change {rel:.2e})"


# ── Dale2014: AGN fraction (additive AGN power source) ────────────


class TestDale2014FracAGN:
    """Dale2014 SF + quasar mixing: SED = L*SF + L*f/(1-f)*QSO."""

    def _fn(self):
        return _dale2014_engine()

    def test_fracagn_additive_increases_total_ir(self):
        """AGN is a separate power source: total IR grows with frac_agn."""
        fn = self._fn()
        sf = fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.0)
        assert jnp.all(jnp.isfinite(sf)) and jnp.any(sf > 0)
        l0 = _bolometric(sf)
        l5 = _bolometric(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.5))
        assert l5 > l0 * 1.2, "frac_agn does not add AGN dust power"

    def test_qso_template_keeps_cigale_full_grid_norm(self):
        """Regression (#717): the QSO template carries CIGALE's *full-grid*
        unit normalization, so its L_nu integral over the (truncated) dust grid
        is ~0.54 — NOT 1.0. ~46% of a unit quasar is the UV/optical disc
        continuum below the dust grid's blue edge (~360 nm). Forcing it to unit
        over the truncated grid (the old bug) inflated its IR share to ~0.78.
        """
        from tengri.components.dust.emission_templates import load_dale2014_lnu_grid

        t = load_dale2014_lnu_grid(_require("data/dale2014_templates_cigale.h5"))
        qso = np.asarray(t["templates_qso"])
        wave = np.asarray(t["wavelength_aa"])
        nu = 2.998e18 / wave
        order = np.argsort(nu)
        integ = abs(np.trapezoid(qso[order], nu[order]))
        assert 0.4 < integ < 0.7, (
            f"QSO L_nu integral = {integ:.3f}; expected ~0.54 (CIGALE full-grid "
            "norm, truncated to the dust grid). A value near 1.0 means the "
            "truncate-then-renormalize-to-unit bug returned (#717)."
        )

    def test_fracagn_energy_partition_matches_cigale(self):
        """Regression (#717): with the QSO carrying ~0.42 of its energy in the
        IR (per unit L_AGN), the total IR grows as ``1 + 0.42 f/(1-f)`` — the
        f=0.6/f=0 IR ratio is ~1.63, matching CIGALE's ``L*model_sb +
        L_AGN*model_quasar``. The old truncate-then-renormalize bug put ~0.78
        in the IR, so the ratio jumped to ~2.2 (tengri ran 1.43x high vs
        CIGALE at f=0.6 in the §6 reproduction knobs panel).
        """
        fn = self._fn()
        l0 = _bolometric(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.0))
        l6 = _bolometric(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=0.6))
        ratio = l6 / l0
        assert 1.45 < ratio < 1.85, (
            f"fracAGN energy partition off (f=0.6/f=0 IR = {ratio:.3f}; CIGALE "
            "~1.63). A value near 2.2 means the QSO normalization bug returned "
            "(#717)."
        )

    # NOTE: the former ``test_closure_and_component_are_identical`` compared the
    # ``dale2014`` engine closure against the ``dale2014_ir`` component. The
    # component was an exact duplicate of the closure (#717 shared one loader +
    # mixing) and was deleted in #738 (Phase 2b); the engine closure is now the
    # single source, so there is no second implementation to compare against.


# ── Schreiber2016: tabulated continuum + PAH ──────────────────────


class TestSchreiber2016Tabulated:
    """Tabulated Schreiber+2016 templates (tdust, fpah), matching CIGALE."""

    def _component(self):
        return _schreiber2016_component()

    def _sed(self, comp, tdust, fpah):
        # Canonical stripped param names (#849): T / f_pah.
        sed_out, _ = comp.predict(
            {"T": tdust, "f_pah": fpah}, jnp.zeros_like(WAVE), WAVE, L_ir=1.0
        )
        return sed_out

    def test_tdust_shifts_peak(self):
        comp = self._component()
        cold = self._sed(comp, 20.0, 0.05)
        hot = self._sed(comp, 50.0, 0.05)
        assert jnp.all(jnp.isfinite(cold)) and jnp.any(cold > 0)
        # Hotter dust peaks at shorter wavelength.
        lam_cold = float(WAVE[jnp.argmax(cold)])
        lam_hot = float(WAVE[jnp.argmax(hot)])
        assert lam_hot < lam_cold

    def test_fpah_changes_sed(self):
        comp = self._component()
        s0 = self._sed(comp, 30.0, 0.0)
        s5 = self._sed(comp, 30.0, 0.5)
        # Relative metric: the SED is tiny in absolute erg/s/Hz, so a plain
        # allclose (atol=1e-8) would falsely call them equal.
        rel = float(jnp.max(jnp.abs(s0 - s5)) / (jnp.max(jnp.abs(s0)) + 1e-300))
        assert rel > 1e-2, f"fpah is a no-op (max frac change {rel:.2e})"


# ── Schreiber+2018: T / f_pah knobs are wired (no silent drop) ────


class TestSchreiber2018NotNoOp:
    """Regression for the #849 silent-drop fix: the schreiber2018 component
    passed the old ``dust_tdust`` / ``dust_fpah`` kwarg names to a loader whose
    signature is ``dust_T`` / ``dust_f_pah``, so both knobs landed in
    ``**_kwargs`` and were silently ignored. After the canonical rename the
    component passes ``dust_T=`` / ``dust_f_pah=`` and the knobs move the SED."""

    def _component(self):
        from tengri._data_setup import find_data_str
        from tengri.components.sed_model_component import _REGISTRY

        # Gate on the grid file DIRECTLY (not preload — which is lazy and does
        # not raise on a missing grid; a first predict without the grid leaves
        # the schreiber2018 lazy loader in an inconsistent state that pollutes
        # later tests). Skip before touching the loader when the grid is absent.
        if find_data_str("schreiber2018_templates.h5") is None:
            pytest.skip("schreiber2018 template grid not available")
        return _REGISTRY["schreiber2018"]()

    def _sed(self, comp, T, f_pah):
        sed, _ = comp.predict({"T": T, "f_pah": f_pah}, jnp.zeros_like(WAVE), WAVE, L_ir=1e44)
        return sed

    def test_temperature_shifts_peak(self):
        comp = self._component()
        cold = self._sed(comp, 25.0, 0.05)
        hot = self._sed(comp, 60.0, 0.05)
        rel = float(jnp.max(jnp.abs(cold - hot)) / (jnp.max(jnp.abs(cold)) + 1e-300))
        assert rel > 1e-2, f"dust_T is a silent no-op (max frac change {rel:.2e})"
        # Hotter dust peaks bluewards.
        assert float(WAVE[jnp.argmax(hot)]) < float(WAVE[jnp.argmax(cold)])

    def test_fpah_changes_sed(self):
        comp = self._component()
        s0 = self._sed(comp, 30.0, 0.0)
        s5 = self._sed(comp, 30.0, 0.5)
        rel = float(jnp.max(jnp.abs(s0 - s5)) / (jnp.max(jnp.abs(s0)) + 1e-300))
        assert rel > 1e-2, f"dust_f_pah is a silent no-op (max frac change {rel:.2e})"


# ── Modified blackbody: epsilon_mbb luminosity fraction ───────────


class TestModifiedBlackbodyEpsilon:
    """CIGALE mbb epsilon_mbb: fraction of L_dust carried by the MBB.

    Direction B (#738): the ``modified_blackbody_ir`` component was an exact
    duplicate of the engine ``modified_blackbody`` model (the component literally
    called it) — so the parity is asserted on the canonical engine model directly.
    """

    def _sed(self, epsilon):
        from tengri.components.dust.emission.emission import DUST_EMISSION_MODELS

        return DUST_EMISSION_MODELS["modified_blackbody"](
            WAVE,
            1.0,
            dust_T=35.0,
            dust_beta_ir=1.8,
            dust_epsilon_mbb=epsilon,
        )

    def test_epsilon_scales_luminosity_linearly(self):
        sed = self._sed(1.0)
        assert jnp.all(jnp.isfinite(sed)) and jnp.any(sed > 0)
        full = _bolometric(sed)
        half = _bolometric(self._sed(0.5))
        assert np.isclose(half, 0.5 * full, rtol=1e-3)


# ── every knob is *differentiable*, not merely finite ─────────────
#
# This replaces four near-identical ``test_*_jit_and_grad`` tests that each
# asserted only::
#
#     assert jnp.isfinite(jax.grad(total)(x))
#
# Zero is finite. Every axis below is a template-grid axis or a mixing
# fraction, and the ordinary way each of them breaks -- a nearest-neighbor
# lookup instead of an interpolation, an integer cast, a stray
# ``stop_gradient`` -- leaves the forward value moving (so the no-op tests
# above still pass) and the gradient exactly 0.0 (so the finiteness assertion
# still passes) while the knob is unfittable by every sampler in the package.
#
# Measured 2026-08-16: all six axes are live, and off-node the analytic
# gradient matches a central difference to <= 4e-6 relative.


def _obj_themis_alpha():
    fn = _themis_engine()
    return lambda alpha: jnp.sum(
        fn(WAVE, 1.0, dust_qhac=0.17, dust_umin=2.0, dust_gamma_dl=0.1, dust_alpha=alpha)
    )


def _obj_dale_alpha():
    fn = _dale2014_engine()
    return lambda alpha: jnp.sum(fn(WAVE, 1.0, dust_alpha_dale=alpha, dust_frac_agn=0.3))


def _obj_dale_frac_agn():
    fn = _dale2014_engine()
    return lambda frac: jnp.sum(fn(WAVE, 1.0, dust_alpha_dale=2.0, dust_frac_agn=frac))


def _obj_schreiber2016_fpah():
    comp = _schreiber2016_component()

    def total(f_pah):
        sed, _ = comp.predict({"T": 30.0, "f_pah": f_pah}, jnp.zeros_like(WAVE), WAVE, L_ir=1.0)
        return jnp.sum(sed)

    return total


def _obj_schreiber2016_tdust():
    comp = _schreiber2016_component()

    def total(tdust):
        sed, _ = comp.predict({"T": tdust, "f_pah": 0.05}, jnp.zeros_like(WAVE), WAVE, L_ir=1.0)
        return jnp.sum(sed)

    return total


def _obj_mbb_epsilon():
    from tengri.components.dust.emission.emission import DUST_EMISSION_MODELS

    return lambda eps: jnp.sum(
        DUST_EMISSION_MODELS["modified_blackbody"](
            WAVE, 1.0, dust_T=35.0, dust_beta_ir=1.8, dust_epsilon_mbb=eps
        )
    )


#: axis -> (objective builder, evaluation point).
#:
#: The points sit *strictly inside* a template cell, and that is not a detail.
#: THEMIS interpolates on an alpha grid of pitch 0.1 and Dale2014 on one of
#: pitch 0.0625, so the round numbers an author reaches for first -- 1.0, 1.5,
#: 2.0, 2.5, 3.0 -- are all exactly nodes. At a node a piecewise interpolant
#: has two different one-sided slopes, ``jax.grad`` returns one of them and a
#: central difference returns their average, and the two disagree by up to 41%
#: for reasons that have nothing to do with correctness. Sampling 0.03 off-node
#: drops that disagreement to 1e-6.
_GRAD_AXES = {
    "dale2014_dust_alpha_dale": (_obj_dale_alpha, 1.53),
    "dale2014_dust_frac_agn": (_obj_dale_frac_agn, 0.41),
    "mbb_dust_epsilon_mbb": (_obj_mbb_epsilon, 0.37),
    "schreiber2016_f_pah": (_obj_schreiber2016_fpah, 0.23),
    "schreiber2016_tdust": (_obj_schreiber2016_tdust, 31.3),
    "themis_dust_alpha": (_obj_themis_alpha, 1.77),
}


@pytest.mark.parametrize("axis", sorted(_GRAD_AXES))
def test_knob_is_differentiable_not_merely_finite(axis):
    """The gradient is finite, non-zero, and equal to a finite difference."""
    build, x = _GRAD_AXES[axis]
    total = jax.jit(build())

    value = float(total(x))
    assert np.isfinite(value) and value != 0.0

    # atol=0.0 deliberately. These objectives sum an SED in erg/s/Hz and land
    # near 1e-11, so the helper's default absolute floor of 1e-8 sits three
    # orders of magnitude *above* every gradient here and would accept a
    # zeroed one. Its computed finite-difference noise floor (~1e-22 at this
    # scale) is the honest floor and still applies.
    grad = float(assert_grad_matches_fd(total, x, rtol=1e-3, atol=0.0))

    # Dimensionless logarithmic sensitivity: the fractional change in the
    # summed SED per fractional change in the knob. Measured range across
    # these six axes is 0.07 to 5.9, so 1e-3 is a floor against a dead
    # gradient rather than a claim about how sensitive the model ought to be.
    sensitivity = abs(x * grad / value)
    assert sensitivity > 1e-3, (
        f"{axis} has a finite but effectively dead gradient at x={x}: "
        f"d ln(sum SED) / d ln x = {sensitivity:.3e}. A knob that moves the "
        f"SED but cannot be differentiated is unfittable by MAP, VI and NUTS "
        f"alike."
    )


#: knob -> (objective builder, lower bound, upper bound). Both of these are
#: fractions of a luminosity, and both are clamped to [0, 1].
_CLAMPED_FRACTIONS = {
    "mbb_dust_epsilon_mbb": (_obj_mbb_epsilon, 0.0, 1.0),
    "schreiber2016_f_pah": (_obj_schreiber2016_fpah, 0.0, 1.0),
}


@pytest.mark.parametrize("knob", sorted(_CLAMPED_FRACTIONS))
def test_bounded_fraction_is_hard_clamped_and_its_gradient_dies_at_the_bound(knob):
    """Outside [0, 1] these knobs are frozen and carry no gradient at all.

    Nothing else in the suite can see this: every existing test evaluates
    strictly inside the interval. The behavior matters because a sampler
    working in an unconstrained space can and does propose values outside the
    bound, and there it receives a bit-identical likelihood and an exactly
    zero gradient -- no signal pointing back into the valid range.

    Measured 2026-08-16: the value outside is bit-identical to the value at
    the bound, the gradient outside is exactly +/-0.0, and the gradient *at*
    the bound is exactly half the interior slope. That last number is not a
    coincidence: ``jnp.where``-style clamping differentiates to the average of
    the live one-sided slope and the dead one.
    """
    build, lo, hi = _CLAMPED_FRACTIONS[knob]
    total = jax.jit(build())
    grad = jax.jit(jax.grad(total))

    interior = float(grad(0.5))
    assert interior != 0.0, f"{knob} is dead in the middle of its own range"

    for bound, outside in ((lo, lo - 0.1), (hi, hi + 0.1)):
        assert float(total(outside)) == float(total(bound)), (
            f"{knob} is not hard-clamped at {bound}: the model extrapolates "
            f"past the bound instead of freezing there."
        )
        assert float(grad(outside)) == 0.0, (
            f"{knob} carries a non-zero gradient at {outside}, outside its "
            f"clamped range -- the forward value is frozen there, so any "
            f"gradient is spurious."
        )
        assert float(grad(bound)) == pytest.approx(0.5 * interior, rel=1e-2), (
            f"{knob} gradient at the bound {bound} is {float(grad(bound)):.6e}, "
            f"not half the interior slope {interior:.6e}. The clamp's "
            f"differentiation convention changed."
        )
