# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
# ---

# %% [markdown]
# # The kitchen-sink mock, and its recovery
#
# One z=1 galaxy carrying nearly every block the framework implements --
# continuity star formation history, two-component dust with Draine & Li
# emission, photoionized nebular, a QSOgen accretion disc behind a SKIRTOR
# torus, a disc-corona X-ray component and star-forming plus AGN radio --
# observed jointly as sixteen bands from Chandra to ALMA plus an optical
# spectrum, and fitted back.
#
# The model is not retyped here. It is imported from the same module that
# prints the listing in the paper, so the figure and the printed code cannot
# disagree.
#
# **This figure is gated.** A posterior that has not converged still produces
# a plot, and a plot is exactly the artifact nobody re-checks. So the renderer
# reads the posterior's own diagnostics first and, if they fail, writes to a
# *different filename* carrying a PROVISIONAL banner. The paper's filename is
# only ever written by a run that cleared the bar.

# %%
import sys
from pathlib import Path

HERE = Path.cwd()
while not (HERE / "paper1_figures").is_dir() and HERE.parent != HERE:
    HERE = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "paper1_figures"))

from _run import SKIPPED, repo_root, run_figure

REPO = repo_root(HERE)
sys.path.insert(0, str(REPO))
RESULTS = REPO / "analysis" / "paper1" / "results"
OUT = REPO / "paper1_figures" / "figures"
OUT.mkdir(parents=True, exist_ok=True)

TRUTH = RESULTS / "mock_joint_truth.npz"
if not TRUTH.is_file():
    print(
        f"no mock at {TRUTH}.\n"
        "The truth SED and its synthetic observation are generated by\n"
        "analysis/paper1/fig_mock_joint_infer.py, which is a separate script\n"
        "on purpose -- it runs where the stellar library is. Generate it, or\n"
        "fetch the committed copy, and re-run."
    )
    raise SystemExit(SKIPPED)

# %% [markdown]
# ## What the gate asks
#
# Three things, and a missing answer is a failure rather than a pass: no
# divergent transitions, split R-hat within 1.01, and at least 400 effective
# samples. The last is the one a kitchen-sink model at this dimensionality
# struggles with -- effective samples, not draws, so a long chain that mixes
# slowly does not get there by being long.

# %%
from analysis.paper1._posterior_gate import (
    GATE_ESS_MIN,
    GATE_MAX_DIVERGENCES,
    GATE_RHAT_MAX,
)

print(f"divergences <= {GATE_MAX_DIVERGENCES}")
print(f"split R-hat <= {GATE_RHAT_MAX}")
print(f"ESS         >= {GATE_ESS_MIN:.0f}")

# %%
# The renderer rebuilds the model to recompute derived quantities, so it needs
# the mock's stellar library. That is a missing input, not a broken figure --
# the same situation the grid notebook skips on, and it should read the same
# way rather than as a traceback.
try:
    status = run_figure("fig01_mock_joint_infer", ["--out-dir", str(OUT)])
    print(f"fig01_mock_joint_infer: {status}")
except FileNotFoundError as exc:
    print(f"{exc}\n")
    print(
        "Skipping: this figure rebuilds its model and so needs the stellar\n"
        "library above. Every grid the paper uses is a known download --\n"
        "  python -c \"import tengri; tengri.download_ssp('<name>')\"\n"
        "-- or set TENGRI_DATA_DIR to a directory that already holds it."
    )
    raise SystemExit(SKIPPED) from None

# %% [markdown]
# ## Which filename landed
#
# The provisional name is not a lesser version of the same figure; it is the
# renderer refusing to let an unconverged posterior occupy the name the paper
# includes.

# %%
# Report what is on disk, not what was expected to be. Listing the two
# filenames this notebook knew about printed "no figure was written" two lines
# after the renderer logged that it had written a third --
# fig01_mock_joint_infer_truthonly.pdf, which it uses when the mock exists but
# no posterior does. A reader believes the summary, not the log above it.
WITHHELD = {
    "fig01_mock_joint_infer_provisional.pdf": (
        "the posterior did not clear the gate, so the paper's filename was withheld"
    ),
    "fig01_mock_joint_infer_truthonly.pdf": (
        "there is no posterior on disk, so this shows the mock alone and recovers nothing"
    ),
}
PAPER_FIGURE = "fig01_mock_joint_infer.pdf"
written = sorted(p.name for p in OUT.glob("fig01_mock_joint_infer*.pdf"))
if not written:
    print("no figure was written; see the renderer's output above")
for name in written:
    if name == PAPER_FIGURE:
        print(f"ok   {name} -- the posterior cleared the gate")
    else:
        why = WITHHELD.get(name, "the renderer withheld the paper's filename")
        print(f"NOT FOR THE PAPER  {name}\n     {why}.")

# A stand-in is not this family's figure. Exiting 0 here reported success to
# regenerate.py -- whose 0 means "every family produced its figures" -- for a
# run that wrote a banner-stamped substitute and left the paper's filename
# unwritten. That is the substitution the gate exists to refuse, arriving one
# step later: in the exit code instead of in the filename.
if PAPER_FIGURE not in written:
    print(
        "\nThe paper's figure was not produced: it needs a posterior that clears\n"
        "the gate above. Reported as skipped rather than as success."
    )
    raise SystemExit(SKIPPED)
