# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
# ---

# %% [markdown]
# # The kitchen-sink mock, and its recovery
#
# One z=1 galaxy carrying nearly every block the framework implements --
# continuity star formation history, two-component dust with Draine & Li
# emission, photoionized nebular, a QSOgen accretion disc behind a SKIRTOR
# torus, a disc-corona X-ray component and star-forming plus AGN radio --
# observed jointly as sixteen bands from Chandra to ALMA plus an optical
# spectrum, and fitted back.
#
# The model is not retyped here. It is imported from the same module that
# prints the listing in the paper, so the figure and the printed code cannot
# disagree.
#
# **This figure is gated.** A posterior that has not converged still produces
# a plot, and a plot is exactly the artifact nobody re-checks. So the renderer
# reads the posterior's own diagnostics first and, if they fail, writes to a
# *different filename* carrying a PROVISIONAL banner. The paper's filename is
# only ever written by a run that cleared the bar.

# %%
import sys
from pathlib import Path

HERE = Path.cwd()
while not (HERE / "paper1_figures").is_dir() and HERE.parent != HERE:
    HERE = HERE.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "paper1_figures"))

from _run import repo_root, run_figure

REPO = repo_root(HERE)
sys.path.insert(0, str(REPO))
RESULTS = REPO / "analysis" / "paper1" / "results"
OUT = REPO / "paper1_figures" / "figures"
OUT.mkdir(parents=True, exist_ok=True)

TRUTH = RESULTS / "mock_joint_truth.npz"
if not TRUTH.is_file():
    print(
        f"no mock at {TRUTH}.\n"
        "The truth SED and its synthetic observation are generated by\n"
        "analysis/paper1/fig_mock_joint_infer.py, which is a separate script\n"
        "on purpose -- it runs where the stellar library is. Generate it, or\n"
        "fetch the committed copy, and re-run."
    )
    raise SystemExit(0)

# %% [markdown]
# ## What the gate asks
#
# Three things, and a missing answer is a failure rather than a pass: no
# divergent transitions, split R-hat within 1.01, and at least 400 effective
# samples. The last is the one a kitchen-sink model at this dimensionality
# struggles with -- effective samples, not draws, so a long chain that mixes
# slowly does not get there by being long.

# %%
from analysis.paper1._posterior_gate import (
    GATE_ESS_MIN,
    GATE_MAX_DIVERGENCES,
    GATE_RHAT_MAX,
)

print(f"divergences <= {GATE_MAX_DIVERGENCES}")
print(f"split R-hat <= {GATE_RHAT_MAX}")
print(f"ESS         >= {GATE_ESS_MIN:.0f}")

# %%
status = run_figure("fig01_mock_joint_infer", ["--out-dir", str(OUT)])
print(f"fig01_mock_joint_infer: {status}")

# %% [markdown]
# ## Which filename landed
#
# The provisional name is not a lesser version of the same figure; it is the
# renderer refusing to let an unconverged posterior occupy the name the paper
# includes.

# %%
final = OUT / "fig01_mock_joint_infer.pdf"
provisional = OUT / "fig01_mock_joint_infer_provisional.pdf"
if final.is_file():
    print("ok   fig01_mock_joint_infer.pdf -- the posterior cleared the gate")
elif provisional.is_file():
    print(
        "PROVISIONAL  fig01_mock_joint_infer_provisional.pdf\n"
        "The posterior did not clear the gate, so the paper's filename was\n"
        "withheld. The figure above is for inspection, not for inclusion."
    )
else:
    print("no figure was written; see the renderer's output above")
