"""Cross-validate tengri absolute SED normalisation against bagpipes, FSPS, and CIGALE.

This test suite checks whether tengri produces the *correct absolute luminosity*
(erg/s/Hz per Msun_formed) — not just the right spectral shape. It catches bugs in:

  - CSP trapezoidal integration weights (tengri vs FSPS, same SSP library)
  - Unit conversion pipeline (erg/s/Hz per Msun)
  - SFH parameterisation (wrong total mass formed)
  - Dust attenuation implementation (CF00 tau_bc / tau_diff mapping)
  - Metallicity convention (log10 absolute Z vs log10 Z/Zsun)

Reference SEDs are generated by scripts/generate_external_sed_reference.py
and stored in data/external_sed_reference.npz. Run that script once before
running these tests (requires bagpipes / python-fsps / pcigale installed):

    python scripts/generate_external_sed_reference.py

Default pytest runs skip this module (mark=crossval). To run:
    pytest -m crossval tests/crossval/test_full_sed_crossval.py -v

Tolerance rationale:
  tengri vs FSPS (same MILES+Chabrier SSP): ~25% optical, ~40% UV
    - Same underlying SSP grid; differences from trapezoidal quadrature and
      metallicity interpolation scheme (FSPS zcontinuous vs tengri linear-in-logZ).
  tengri vs bagpipes (BC03 vs MILES SSPs): factor of 2 at V-band
    - Different SSP libraries dominate; colour trends should still agree.
  tengri vs CIGALE (BC03 vs MILES SSPs): factor of 2 at V-band
    - Same reasoning as bagpipes; CIGALE also uses a different dust treatment.
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pytest

jax.config.update("jax_enable_x64", True)

pytestmark = pytest.mark.crossval

_DATA_DIR = Path(__file__).resolve().parents[2] / "data"
_REF_PATH = _DATA_DIR / "external_sed_reference.npz"
_SSP_PATH = _DATA_DIR / "fsps_prsc_miles_chabrier.h5"

if not _REF_PATH.is_file():
    pytest.skip(
        "External SED reference not found. Run: python scripts/generate_external_sed_reference.py",
        allow_module_level=True,
    )

if not _SSP_PATH.is_file():
    pytest.skip("SSP data not found", allow_module_level=True)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def ref() -> dict:
    return dict(np.load(str(_REF_PATH), allow_pickle=True))


@pytest.fixture(scope="module")
def ssp_data():
    from tengri.models.sps.dsps_wrapper import load_ssp_data

    return load_ssp_data(str(_SSP_PATH))


@pytest.fixture(scope="module")
def tengri_wave(ssp_data) -> np.ndarray:
    """SSP wavelength grid in Angstrom."""
    return np.asarray(ssp_data.ssp_wave)


@pytest.fixture(scope="module")
def ref_wave(ref) -> np.ndarray:
    """Common wavelength grid used by the reference generator (Angstrom)."""
    return ref["wave_grid"]


@pytest.fixture(scope="module")
def ref_wave_ir(ref) -> np.ndarray:
    """Extended IR wavelength grid (1000–3e5 Å) used for dust emission cases."""
    return ref.get(
        "wave_grid_ir",
        np.logspace(np.log10(1000.0), np.log10(3.0e5), 800),
    )


# ---------------------------------------------------------------------------
# Helper: band-averaged flux
# ---------------------------------------------------------------------------


def _band_avg(
    wave: np.ndarray, flux: np.ndarray, center: float, half_width: float = 100.0
) -> float:
    """Return mean flux in [center - half_width, center + half_width] Angstrom."""
    mask = (wave > center - half_width) & (wave < center + half_width)
    if not mask.any():
        raise ValueError(f"No wavelength coverage at {center} Å")
    return float(np.nanmean(flux[mask]))


def _build_tengri_sed(
    ssp_data,
    start_gyr: float,
    end_gyr: float,
    logzsol: float = 0.0,
    tau_bc: float = 0.0,
    tau_diff: float = 0.0,
    dust_slope: float = -0.7,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Build tengri SED and return (wave_Å, L_nu_per_Msun_erg/s/Hz, m_formed_Msun).

    Uses log_sfr=0.0 (SFR = 1 Msun/yr) so M_formed = (end-start) * 1e9 Msun.
    SED is divided by M_formed to give erg/s/Hz per Msun.
    """
    from tengri import Parameters
    from tengri.core.model import SEDModel
    from tengri.distributions import Fixed

    spec = Parameters(
        mean_sfh_type="const",
        sfh_const_log_sfr=Fixed(0.0),  # SFR = 1 Msun/yr
        sfh_const_start_gyr=Fixed(start_gyr),
        sfh_const_end_gyr=Fixed(end_gyr),
        met_logzsol=Fixed(logzsol),
        dust_tau_bc=Fixed(tau_bc),
        dust_tau_diff=Fixed(tau_diff),
        dust_slope=Fixed(dust_slope),
        redshift=0.01,
    )
    model = SEDModel(spec, ssp_data)
    params = spec.sample(jax.random.PRNGKey(0))

    # predict_rest_sed returns SEDResult(wavelength=..., sed=...) — a NamedTuple
    result = model.predict_rest_sed(params)
    wave = np.asarray(result.wavelength)  # Å
    sed_total = np.asarray(result.sed)  # erg/s/Hz (total for all stars formed)

    m_formed = (end_gyr - start_gyr) * 1.0e9  # Msun (SFR = 1 Msun/yr)
    sed_per_msun = sed_total / m_formed  # erg/s/Hz per Msun
    return wave, sed_per_msun, m_formed


# ---------------------------------------------------------------------------
# Test case 1: Star-forming (constant SFH, 3 Gyr, no dust)
# ---------------------------------------------------------------------------


class TestStarforming:
    """Tengri vs external codes: 3 Gyr constant SFH, solar Z, no dust."""

    @pytest.fixture(scope="class")
    def tengri(self, ssp_data):
        wave, sed_per_msun, m_formed = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=3.0)
        return {"wave": wave, "sed": sed_per_msun, "m_formed": m_formed}

    def test_tengri_vs_fsps_vband(self, tengri, ref, ref_wave):
        """V-band (5500 Å) luminosity per Msun within 10% of FSPS.

        Same SSP library (MILES, Chabrier), same SFH (3 Gyr const), same IMF.
        Residual from CSP trapezoidal quadrature vs FSPS internal integration.
        Tighter than 10% is expected; failure indicates a CSP weight or unit bug.
        """
        key = "fsps_stellar_starforming"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz (FSPS not installed?)")

        l_tengri = _band_avg(tengri["wave"], tengri["sed"], 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_fsps
        assert 0.90 <= ratio <= 1.10, (
            f"V-band L_nu/Msun ratio tengri/FSPS = {ratio:.3f} (expect 0.90–1.10). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun. "
            "Both use MILES+Chabrier SSPs, 3 Gyr const SFH. Failure → CSP weight bug, "
            "wrong M_formed, or unit conversion error."
        )

    def test_tengri_vs_fsps_nuv(self, tengri, ref, ref_wave):
        """NUV (2800 Å) luminosity per Msun within 20% of FSPS.

        Same SSPs. UV is more sensitive to metallicity interpolation scheme and
        TP-AGB treatment; 20% is the physically motivated target.
        """
        key = "fsps_stellar_starforming"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        l_tengri = _band_avg(tengri["wave"], tengri["sed"], 2800.0, half_width=150.0)
        l_fsps = _band_avg(ref_wave, ref[key], 2800.0, half_width=150.0)

        ratio = l_tengri / l_fsps
        assert 0.80 <= ratio <= 1.20, (
            f"NUV L_nu/Msun ratio tengri/FSPS = {ratio:.3f} (expect 0.80–1.20). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun. "
            "Failure at 20% suggests metallicity interpolation or endpoint quadrature bug."
        )

    def test_tengri_vs_bagpipes_vband_within_factor2(self, tengri, ref, ref_wave):
        """V-band agreement within factor 2 vs bagpipes (BC03 vs MILES SSPs)."""
        key = "bagpipes_stellar_starforming"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz (bagpipes not installed?)")

        l_tengri = _band_avg(tengri["wave"], tengri["sed"], 5500.0)
        l_bagpipes = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_bagpipes
        assert 0.5 <= ratio <= 2.0, (
            f"V-band L_nu/Msun ratio tengri/bagpipes = {ratio:.3f} (expect 0.5–2.0). "
            f"tengri={l_tengri:.3e}, bagpipes={l_bagpipes:.3e} erg/s/Hz/Msun. "
            "SSP library difference (MILES vs BC03) accounts for ~50%; "
            "larger deviations indicate a normalisation bug."
        )

    def test_tengri_vs_cigale_vband_within_factor2(self, tengri, ref, ref_wave):
        """V-band agreement within factor 2 vs CIGALE (BC03 vs MILES SSPs)."""
        key = "cigale_stellar_starforming"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz (CIGALE not installed?)")

        l_tengri = _band_avg(tengri["wave"], tengri["sed"], 5500.0)
        l_cigale = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_cigale
        assert 0.5 <= ratio <= 2.0, (
            f"V-band L_nu/Msun ratio tengri/CIGALE = {ratio:.3f} (expect 0.5–2.0). "
            f"tengri={l_tengri:.3e}, cigale={l_cigale:.3e} erg/s/Hz/Msun."
        )

    def test_tengri_sed_is_finite_and_positive(self, tengri):
        """SED must be finite and positive throughout the optical range."""
        wave = tengri["wave"]
        sed = tengri["sed"]
        optical = (wave > 1000.0) & (wave < 30000.0)
        assert np.all(np.isfinite(sed[optical])), "NaN or Inf in tengri SED optical range"
        assert np.all(sed[optical] >= 0.0), "Negative flux in tengri SED optical range"

    def test_m_formed_is_correct(self, tengri):
        """SFR=1 Msun/yr over 3 Gyr should give M_formed = 3e9 Msun."""
        assert abs(tengri["m_formed"] - 3.0e9) < 1e3, (
            f"Expected M_formed = 3e9 Msun, got {tengri['m_formed']:.3e}"
        )


# ---------------------------------------------------------------------------
# Test case 2: Old quenched (10 Gyr galaxy, SF ended at 5 Gyr)
# ---------------------------------------------------------------------------


class TestOldQuenched:
    """Tengri vs external codes: 10 Gyr galaxy, SF from 0–5 Gyr, then quenched."""

    @pytest.fixture(scope="class")
    def tengri(self, ssp_data):
        # tengri: start=5.0 (5 Gyr lookback), end=10.0 (10 Gyr lookback)
        # = SF from formation to 5 Gyr after formation, observed at 10 Gyr
        wave, sed_per_msun, m_formed = _build_tengri_sed(ssp_data, start_gyr=5.0, end_gyr=10.0)
        return {"wave": wave, "sed": sed_per_msun, "m_formed": m_formed}

    def test_tengri_vs_fsps_vband(self, tengri, ref, ref_wave):
        """V-band luminosity per Msun within 10% of FSPS (quenched, 5 Gyr SF, 10 Gyr obs).

        Same SSPs (MILES, Chabrier), identical SFH definition. Tight tolerance
        catches CSP time-weighting errors for old stellar populations.
        """
        key = "fsps_stellar_old_quenched"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        l_tengri = _band_avg(tengri["wave"], tengri["sed"], 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_fsps
        assert 0.90 <= ratio <= 1.10, (
            f"V-band L_nu/Msun ratio tengri/FSPS = {ratio:.3f} (old_quenched). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun. "
            "Same SSPs: 10% threshold. Failure → SFH truncation bug or CSP endpoint error."
        )

    def test_quenched_redder_than_starforming_in_tengri(self, ssp_data):
        """Old quenched galaxy should be redder (higher V/UV ratio) than star-forming.

        A quenched galaxy has no young stars, so its UV flux (relative to V) should
        be much lower than a star-forming galaxy. Failure here indicates a bug in
        the SFH truncation logic or CSP time-weighting.
        """
        _, sf_sed, _ = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=3.0)
        _, qu_sed, _ = _build_tengri_sed(ssp_data, start_gyr=5.0, end_gyr=10.0)
        wave = np.asarray(ssp_data.ssp_wave)

        # UV-to-V flux ratio (smaller = redder)
        sf_uv = _band_avg(wave, sf_sed, 2800.0, half_width=200.0)
        sf_v = _band_avg(wave, sf_sed, 5500.0)
        qu_uv = _band_avg(wave, qu_sed, 2800.0, half_width=200.0)
        qu_v = _band_avg(wave, qu_sed, 5500.0)

        sf_ratio = sf_uv / sf_v
        qu_ratio = qu_uv / qu_v

        assert qu_ratio < sf_ratio, (
            f"Quenched galaxy is NOT redder than star-forming: "
            f"quenched UV/V = {qu_ratio:.3f}, SF UV/V = {sf_ratio:.3f}. "
            "This indicates a SFH truncation bug — the quenched model "
            "may still have young stars contributing UV flux."
        )

    def test_m_formed_is_correct(self, tengri):
        """SFR=1 Msun/yr over 5 Gyr should give M_formed = 5e9 Msun."""
        assert abs(tengri["m_formed"] - 5.0e9) < 1e3, (
            f"Expected M_formed = 5e9 Msun, got {tengri['m_formed']:.3e}"
        )


# ---------------------------------------------------------------------------
# Test case 3: Dusty star-forming (same as starforming + CF00 dust)
# ---------------------------------------------------------------------------


class TestDustySFG:
    """Tengri vs external codes: 3 Gyr constant SFH + CF00 dust."""

    @pytest.fixture(scope="class")
    def tengri_clean(self, ssp_data):
        _, sed, _ = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=3.0)
        return sed

    @pytest.fixture(scope="class")
    def tengri_dusty(self, ssp_data):
        _, sed, _ = _build_tengri_sed(
            ssp_data,
            start_gyr=0.0,
            end_gyr=3.0,
            tau_bc=1.0,
            tau_diff=0.5,
            dust_slope=-0.7,
        )
        return sed

    def test_tengri_vs_fsps_vband(self, tengri_dusty, ref, ref_wave, ssp_data):
        """V-band luminosity per Msun within 15% of FSPS (dusty; tau_bc=1.0, tau_diff=0.5).

        Same SSPs + same CF00 dust parameters. 15% allows for tau→Av conversion
        rounding; tighter failure implies a CF00 dust1/dust2 mapping bug.
        """
        key = "fsps_stellar_dusty_sfg"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        wave = np.asarray(ssp_data.ssp_wave)
        l_tengri = _band_avg(wave, tengri_dusty, 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_fsps
        assert 0.85 <= ratio <= 1.15, (
            f"V-band L_nu/Msun ratio tengri/FSPS = {ratio:.3f} (dusty_sfg). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun. "
            "tau_bc=1.0→dust1=1.086, tau_diff=0.5→dust2=0.543. Check 1.086 factor."
        )

    def test_dust_attenuates_uv_more_than_optical(self, tengri_clean, tengri_dusty, ssp_data):
        """Dust should reduce UV (2800 Å) more than V-band (5500 Å).

        CF00 has a steeper attenuation law in the UV, so the UV/V ratio should
        decrease when dust is added. If UV attenuation is *less* than optical,
        the dust law slope or normalisation is implemented backwards.
        """
        wave = np.asarray(ssp_data.ssp_wave)

        uv_clean = _band_avg(wave, tengri_clean, 2800.0, half_width=150.0)
        uv_dusty = _band_avg(wave, tengri_dusty, 2800.0, half_width=150.0)
        v_clean = _band_avg(wave, tengri_clean, 5500.0)
        v_dusty = _band_avg(wave, tengri_dusty, 5500.0)

        uv_suppression = uv_dusty / uv_clean
        v_suppression = v_dusty / v_clean

        assert uv_suppression < v_suppression, (
            f"UV suppression ({uv_suppression:.3f}) is NOT stronger than "
            f"V-band suppression ({v_suppression:.3f}). "
            "CF00 dust slope bug: UV should always be more attenuated than optical."
        )

    def test_dust_reduces_vband_flux(self, tengri_clean, tengri_dusty, ssp_data):
        """Dust must reduce V-band flux (tau_diff=0.5 ↔ ~0.54 mag at V)."""
        wave = np.asarray(ssp_data.ssp_wave)
        v_clean = _band_avg(wave, tengri_clean, 5500.0)
        v_dusty = _band_avg(wave, tengri_dusty, 5500.0)

        suppression = v_dusty / v_clean
        # tau_diff=0.5: extinction = exp(-0.5) ≈ 0.61; expect 0.4–0.8
        assert 0.40 <= suppression <= 0.80, (
            f"V-band dust suppression = {suppression:.3f}; "
            f"expected 0.40–0.80 for tau_diff=0.5. "
            "Possible: wrong CF00 Av convention (Av vs tau) or wrong factor of 1.086."
        )

    def test_tengri_vs_bagpipes_vband(self, tengri_dusty, ref, ref_wave, ssp_data):
        """Dusty V-band within factor 2.5 of bagpipes (different SSPs + dust treatment)."""
        key = "bagpipes_stellar_dusty_sfg"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        wave = np.asarray(ssp_data.ssp_wave)
        l_tengri = _band_avg(wave, tengri_dusty, 5500.0)
        l_bagpipes = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_bagpipes
        # Wider tolerance: BC03 vs MILES + slightly different CF00 Av convention
        assert 0.4 <= ratio <= 2.5, (
            f"V-band L_nu/Msun ratio tengri/bagpipes = {ratio:.3f} (dusty_sfg). "
            f"tengri={l_tengri:.3e}, bagpipes={l_bagpipes:.3e} erg/s/Hz/Msun."
        )


# ---------------------------------------------------------------------------
# Cross-case sanity: colour trends
# ---------------------------------------------------------------------------


class TestColourTrends:
    """Cross-case SED shapes must obey physically expected colour trends."""

    def test_starforming_is_bluer_than_quenched(self, ssp_data):
        """UV/V ratio must be higher for star-forming than quenched galaxy.

        This is a fundamental prediction of stellar evolution. If this fails,
        the SFH implementation (constant vs truncated) is broken.
        """
        _, sf_sed, _ = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=3.0)
        _, qu_sed, _ = _build_tengri_sed(ssp_data, start_gyr=5.0, end_gyr=10.0)
        wave = np.asarray(ssp_data.ssp_wave)

        sf_color = _band_avg(wave, sf_sed, 2800.0, half_width=200.0) / _band_avg(
            wave, sf_sed, 5500.0
        )
        qu_color = _band_avg(wave, qu_sed, 2800.0, half_width=200.0) / _band_avg(
            wave, qu_sed, 5500.0
        )

        assert sf_color > qu_color, (
            f"Star-forming UV/V ({sf_color:.3f}) not higher than quenched ({qu_color:.3f}). "
            "SFH age-weighting likely incorrect."
        )

    def test_dust_reddens_galaxy(self, ssp_data):
        """Dusty SFG must be redder (lower UV/V) than clean SFG."""
        _, sf_clean, _ = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=3.0)
        _, sf_dusty, _ = _build_tengri_sed(
            ssp_data, start_gyr=0.0, end_gyr=3.0, tau_bc=1.0, tau_diff=0.5
        )
        wave = np.asarray(ssp_data.ssp_wave)

        clean_color = _band_avg(wave, sf_clean, 2800.0, half_width=200.0) / _band_avg(
            wave, sf_clean, 5500.0
        )
        dusty_color = _band_avg(wave, sf_dusty, 2800.0, half_width=200.0) / _band_avg(
            wave, sf_dusty, 5500.0
        )

        assert dusty_color < clean_color, (
            f"Dusty SFG is NOT redder than clean SFG: "
            f"dusty UV/V = {dusty_color:.3f}, clean UV/V = {clean_color:.3f}. "
            "CF00 dust is not reducing UV more than V-band — direction bug."
        )

    def test_all_codes_agree_on_colour_trend(self, ref, ref_wave):
        """bagpipes, FSPS, and CIGALE should all show starforming is bluer than quenched."""
        for code in ("bagpipes", "fsps", "cigale"):
            sf_key = f"{code}_stellar_starforming"
            qu_key = f"{code}_stellar_old_quenched"
            if sf_key not in ref or qu_key not in ref:
                continue  # skip if this code was not available

            sf_uv = _band_avg(ref_wave, ref[sf_key], 2800.0, half_width=200.0)
            sf_v = _band_avg(ref_wave, ref[sf_key], 5500.0)
            qu_uv = _band_avg(ref_wave, ref[qu_key], 2800.0, half_width=200.0)
            qu_v = _band_avg(ref_wave, ref[qu_key], 5500.0)

            sf_color = sf_uv / sf_v
            qu_color = qu_uv / qu_v

            assert sf_color > qu_color, (
                f"[{code}] Star-forming UV/V ({sf_color:.3f}) not greater than "
                f"quenched UV/V ({qu_color:.3f}). Bug in {code} reference generator."
            )


# ---------------------------------------------------------------------------
# SFR / stellar mass normalisation
# ---------------------------------------------------------------------------


def _build_tengri_sed_raw(
    ssp_data,
    sfh_type: str,
    sfh_params: dict,
    logzsol: float = 0.0,
    tau_bc: float = 0.0,
    tau_diff: float = 0.0,
    dust_slope: float = -0.7,
) -> tuple[np.ndarray, np.ndarray]:
    """Build tengri SED in absolute erg/s/Hz (not normalised by M_formed).

    sfh_params: dict of fully-prefixed ParamSpec kwargs for the given sfh_type.
    Returns (wave_Å, L_nu_erg/s/Hz).
    """
    from tengri import Parameters
    from tengri.core.model import SEDModel
    from tengri.distributions import Fixed

    kwargs: dict = {
        "mean_sfh_type": sfh_type,
        "met_logzsol": Fixed(logzsol),
        "dust_tau_bc": Fixed(tau_bc),
        "dust_tau_diff": Fixed(tau_diff),
        "dust_slope": Fixed(dust_slope),
        "redshift": 0.01,
    }
    kwargs.update({k: Fixed(v) for k, v in sfh_params.items()})

    spec = Parameters(**kwargs)
    model = SEDModel(spec, ssp_data)
    params = spec.sample(jax.random.PRNGKey(0))
    result = model.predict_rest_sed(params)
    return np.asarray(result.wavelength), np.asarray(result.sed)


class TestSFRNormalisation:
    """Verify that SED scales linearly with SFR and stellar mass.

    If SFR doubles, the SED should double at every wavelength (linear scaling
    from the CSP integral). This is a fundamental check of the normalisation
    pipeline and M_formed accounting.
    """

    def test_const_sfr_linear_scaling(self, ssp_data):
        """10x higher SFR (const SFH) should give 10x higher SED at all wavelengths.

        Uses M_star = 10^10 Msun scenario: log_sfr=1 (10 Msun/yr), duration 1 Gyr.
        Linear SFR scaling tests that tengri does not renormalise the SED
        to unity at any wavelength or apply a nonlinear mass dependence.
        """
        wave1, sed1 = _build_tengri_sed_raw(
            ssp_data,
            "const",
            {"sfh_const_log_sfr": 0.0, "sfh_const_start_gyr": 0.0, "sfh_const_end_gyr": 1.0},
        )
        _wave10, sed10 = _build_tengri_sed_raw(
            ssp_data,
            "const",
            {"sfh_const_log_sfr": 1.0, "sfh_const_start_gyr": 0.0, "sfh_const_end_gyr": 1.0},
        )
        # Pick optical wavelengths only (where flux is well-defined)
        optical = (wave1 > 3000.0) & (wave1 < 10000.0)
        # SED should scale by exactly 10x
        ratios = sed10[optical] / np.where(sed1[optical] > 0, sed1[optical], np.nan)
        ratios = ratios[np.isfinite(ratios)]
        assert len(ratios) > 100, "Too few valid pixels for ratio test"
        mean_ratio = float(np.median(ratios))
        assert abs(mean_ratio - 10.0) < 0.1, (
            f"SFR 10x scaling: median SED ratio = {mean_ratio:.4f} (expect 10.0). "
            "SED must scale linearly with SFR. If this fails, the CSP integral "
            "is applying a nonlinear normalisation or renormalising by M_formed."
        )

    def test_mass_1e10_v_band_absolute(self, ssp_data):
        """M_star ~ 10^10 Msun: V-band luminosity must be in expected physical range.

        Uses log_sfr=1.0 (10 Msun/yr), 1 Gyr duration → M_formed ≈ 10^10 Msun.
        For a galaxy of this mass, typical L_V ≈ 10^10–10^11 Lsun at V.
        In erg/s/Hz: 10^10 × Lsun/Hz ≈ 10^10 × 7e19 ≈ 7e29 erg/s/Hz.
        This checks that the absolute scale is in a physically reasonable range,
        not orders of magnitude off (which would indicate a unit conversion bug).
        """
        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "const",
            {"sfh_const_log_sfr": 1.0, "sfh_const_start_gyr": 0.0, "sfh_const_end_gyr": 1.0},
        )
        l_v = _band_avg(wave, sed, 5500.0)
        # Expected range: 10^9 Lsun ×  L_ν,sun/Lsun  to  10^11 Lsun × L_ν,sun/Lsun
        # L_ν,sun at V ≈ 7.5e18 erg/s/Hz (from SSP grid, solar 1 Gyr SSP per Msun)
        # For 1e10 Msun and M/L_V ≈ 1–10: L_V ≈ 7.5e28 – 7.5e29 erg/s/Hz
        assert 1e28 < l_v < 1e31, (
            f"V-band luminosity for M~10^10 Msun galaxy = {l_v:.3e} erg/s/Hz. "
            "Expected 10^28–10^31 erg/s/Hz for a 1e10 Msun galaxy. "
            "Check SFR unit convention (Msun/yr vs Msun/s vs Msun/Gyr)."
        )

    def test_sfr_10_vs_fsps(self, ssp_data, ref, ref_wave):
        """SFR=10 galaxy (const, 1 Gyr): V-band within 25% of FSPS after M_formed scaling."""
        key = "fsps_stellar_starforming"  # FSPS reference is per Msun, galaxy age=3 Gyr
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        # tengri: SFR=10, 1 Gyr → 10^10 Msun
        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "const",
            {"sfh_const_log_sfr": 1.0, "sfh_const_start_gyr": 0.0, "sfh_const_end_gyr": 1.0},
        )
        m_formed = 10.0 * 1e9  # 1e10 Msun
        sed_per_msun = sed / m_formed

        l_tengri = _band_avg(wave, sed_per_msun, 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)

        # Note: ages differ (tengri=1 Gyr vs FSPS ref=3 Gyr), so we allow wider tolerance
        # The key check is that per-Msun normalisation does not have a factor-of-M bug.
        ratio = l_tengri / l_fsps
        assert 0.3 <= ratio <= 3.0, (
            f"SFR=10 per-Msun V-band ratio tengri/FSPS = {ratio:.3f} "
            f"(different ages: 1 vs 3 Gyr, so wider tolerance). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun."
        )


# ---------------------------------------------------------------------------
# SFH type cross-validation: delayed tau and DPL
# ---------------------------------------------------------------------------


class TestDelayedTauSFH:
    """Cross-validate the delayed-exponential (dexp) SFH against FSPS and colour checks.

    tengri dexp: SFR(t_lb) ∝ (dt/tau) × exp(-dt/tau + 1) where dt = t_lb - start.
    Peak at dt = tau (i.e. t_lb = start + tau).
    FSPS sfh=4 (delayed tau): SFR(t_cosmic) ∝ t × exp(-t/tau).
    Peak at t_cosmic = tau after formation.

    These parameterisations are equivalent when:
      tengri start = 0 (SF starts now, lookback 0)
      tengri end = large (SF extends far into the past)
      tengri tau = tau_fsps
      FSPS tage = age of galaxy
    Both peak at tau Gyr after galaxy formation.
    """

    def test_dexp_sed_is_finite_and_positive(self, ssp_data):
        """Delayed tau SED must be finite and non-negative in the optical."""
        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "dexp",
            {
                "sfh_dexp_log_peak_sfr": 1.0,  # 10 Msun/yr peak
                "sfh_dexp_tau_gyr": 1.0,
                "sfh_dexp_start_gyr": 0.0,
            },
        )
        optical = (wave > 1000.0) & (wave < 30000.0)
        assert np.all(np.isfinite(sed[optical])), "NaN/Inf in dexp SED optical"
        assert np.all(sed[optical] >= 0.0), "Negative flux in dexp SED optical"

    def test_dexp_vs_fsps_vband(self, ssp_data, ref, ref_wave):
        """Delayed tau V-band per Msun within factor 2 of FSPS constant SFH reference.

        Direct comparison is approximate (different SFH shapes), but both are
        continuous SF histories and should agree within factor 2 at V-band per Msun.
        """
        key = "fsps_stellar_starforming"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        # tau=1 Gyr peak, SF observed at ~3 Gyr after peak
        # M_formed ≈ peak_sfr × tau × e (analytic integral of delayed tau)
        peak_sfr = 10.0  # Msun/yr (log_peak_sfr=1.0)
        tau_gyr = 1.0
        m_formed = peak_sfr * tau_gyr * 1e9 * np.e  # Msun

        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "dexp",
            {
                "sfh_dexp_log_peak_sfr": 1.0,
                "sfh_dexp_tau_gyr": tau_gyr,
                "sfh_dexp_start_gyr": 0.0,
            },
        )
        sed_per_msun = sed / m_formed

        l_tengri = _band_avg(wave, sed_per_msun, 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_fsps
        assert 0.3 <= ratio <= 3.0, (
            f"dexp V-band per-Msun ratio tengri/FSPS = {ratio:.3f} (expect 0.3–3.0). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun."
        )

    def test_dexp_bluer_than_dexp_old(self, ssp_data):
        """Short-tau (peaked early) dexp should be redder than long-tau (ongoing SF).

        Large tau = extended SF → more young stars → bluer. If this fails, the
        SFH time axis convention (lookback vs cosmic) is inverted.
        """
        _wave_short, sed_short = _build_tengri_sed_raw(
            ssp_data,
            "dexp",
            {"sfh_dexp_log_peak_sfr": 1.0, "sfh_dexp_tau_gyr": 0.3, "sfh_dexp_start_gyr": 0.0},
        )
        _wave_long, sed_long = _build_tengri_sed_raw(
            ssp_data,
            "dexp",
            {"sfh_dexp_log_peak_sfr": 1.0, "sfh_dexp_tau_gyr": 3.0, "sfh_dexp_start_gyr": 0.0},
        )
        w = np.asarray(ssp_data.ssp_wave)
        short_color = _band_avg(w, sed_short / (sed_short.max() or 1), 2800.0, 150.0) / _band_avg(
            w, sed_short / (sed_short.max() or 1), 5500.0
        )
        long_color = _band_avg(w, sed_long / (sed_long.max() or 1), 2800.0, 150.0) / _band_avg(
            w, sed_long / (sed_long.max() or 1), 5500.0
        )

        assert long_color > short_color, (
            f"Long-tau dexp (τ=3 Gyr) not bluer than short-tau (τ=0.3 Gyr): "
            f"long UV/V = {long_color:.3f}, short UV/V = {short_color:.3f}. "
            "Extended SF should produce more young stars → bluer UV."
        )


class TestDPLSFH:
    """Cross-validate the double power law (dpl) SFH.

    DPL SFH: SFR ∝ [(t/tau)^alpha + (t/tau)^(-beta)]^-1, rising as power law
    alpha, falling as power law beta, peak near tau. Flexible shape covering
    rising, flat, and falling histories.
    """

    def test_dpl_sed_is_finite_and_positive(self, ssp_data):
        """DPL SED must be finite and non-negative in the optical."""
        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "dpl",
            {
                "sfh_dpl_log_peak_sfr": 1.0,
                "sfh_dpl_alpha": 1.5,
                "sfh_dpl_beta": 5.0,
                "sfh_dpl_tau_gyr": 3.0,
            },
        )
        optical = (wave > 1000.0) & (wave < 30000.0)
        assert np.all(np.isfinite(sed[optical])), "NaN/Inf in DPL SED optical"
        assert np.all(sed[optical] >= 0.0), "Negative flux in DPL SED optical"

    def test_dpl_vs_fsps_vband_order_of_magnitude(self, ssp_data, ref, ref_wave):
        """DPL V-band within order of magnitude of FSPS constant SFH per Msun.

        DPL and constant SFH produce different SED shapes, but absolute luminosity
        per Msun should be within 10x at V-band for physically similar galaxies.
        """
        key = "fsps_stellar_starforming"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        # Rough M_formed estimate for DPL (alpha=1.5, beta=5, tau=3 Gyr, peak=10 Msun/yr):
        # Numerical integration; approximate ≈ peak_sfr × tau × B(1+1/alpha, 1+1/beta)
        # For simplicity, use tau × peak_sfr × 2 as rough estimate
        peak_sfr = 10.0
        tau_gyr = 3.0
        m_formed_approx = peak_sfr * tau_gyr * 1e9 * 2.0  # rough: 6e10 Msun

        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "dpl",
            {
                "sfh_dpl_log_peak_sfr": 1.0,
                "sfh_dpl_alpha": 1.5,
                "sfh_dpl_beta": 5.0,
                "sfh_dpl_tau_gyr": tau_gyr,
            },
        )
        sed_per_msun = sed / m_formed_approx

        l_tengri = _band_avg(wave, sed_per_msun, 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)

        ratio = l_tengri / l_fsps
        assert 0.1 <= ratio <= 10.0, (
            f"DPL V-band per-Msun ratio tengri/FSPS = {ratio:.3f} (expect 0.1–10). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun. "
            "Larger deviations indicate a DPL normalisation or M_formed accounting bug."
        )

    def test_dpl_steep_fall_is_redder_than_rising(self, ssp_data):
        """DPL with steep fall (high beta) should be redder than gently falling (low beta).

        High beta = rapid quenching after peak → fewer young stars → redder UV.
        """
        _wave_steep, sed_steep = _build_tengri_sed_raw(
            ssp_data,
            "dpl",
            {
                "sfh_dpl_log_peak_sfr": 1.0,
                "sfh_dpl_alpha": 1.5,
                "sfh_dpl_beta": 20.0,
                "sfh_dpl_tau_gyr": 3.0,
            },
        )
        _wave_gentle, sed_gentle = _build_tengri_sed_raw(
            ssp_data,
            "dpl",
            {
                "sfh_dpl_log_peak_sfr": 1.0,
                "sfh_dpl_alpha": 1.5,
                "sfh_dpl_beta": 1.5,
                "sfh_dpl_tau_gyr": 3.0,
            },
        )
        w = np.asarray(ssp_data.ssp_wave)

        def color(s):
            norm = s.max() or 1.0
            return _band_avg(w, s / norm, 2800.0, 150.0) / _band_avg(w, s / norm, 5500.0)

        assert color(sed_gentle) > color(sed_steep), (
            f"Steep-fall DPL (beta=20) not redder than gentle-fall (beta=1.5): "
            f"steep UV/V = {color(sed_steep):.3f}, gentle UV/V = {color(sed_gentle):.3f}. "
            "High beta should quench SF rapidly → redder galaxy."
        )


# ---------------------------------------------------------------------------
# Exponential SFH (tau model) — bagpipes + FSPS
# ---------------------------------------------------------------------------


class TestExpSFH:
    """Cross-validate exponential declining SFH between bagpipes and FSPS.

    Both codes natively support tau-model SFH. Discrepancies here indicate
    a difference in how total mass is normalised vs how SFR integrates over time.
    """

    def test_fsps_seds_finite_and_positive(self, ref, ref_wave):
        """All FSPS expsfh SEDs must be finite and positive in the optical."""
        for name in ("tau1gyr", "tau5gyr", "tau0p3gyr"):
            key = f"fsps_expsfh_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz — FSPS not available")
            sed = ref[key]
            optical = (ref_wave > 3000.0) & (ref_wave < 10000.0)
            assert np.all(np.isfinite(sed[optical])), f"NaN/Inf in {key}"
            assert np.all(sed[optical] >= 0.0), f"Negative flux in {key}"

    def test_bagpipes_seds_finite_and_positive(self, ref, ref_wave):
        """All bagpipes expsfh SEDs must be finite and positive in the optical."""
        for name in ("tau1gyr", "tau5gyr", "tau0p3gyr"):
            key = f"bagpipes_expsfh_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz — bagpipes not available")
            sed = ref[key]
            optical = (ref_wave > 3000.0) & (ref_wave < 10000.0)
            assert np.all(np.isfinite(sed[optical])), f"NaN/Inf in {key}"
            assert np.all(sed[optical] >= 0.0), f"Negative flux in {key}"

    def test_longer_tau_is_bluer(self, ref, ref_wave):
        """tau=5 Gyr SFH should be bluer (higher UV/V) than tau=1 Gyr.

        Longer timescale = sustained SF at observation → more young stars → bluer.
        Both bagpipes and FSPS should show this trend.
        """
        v_idx = np.argmin(np.abs(ref_wave - 5500.0))
        uv_idx = np.argmin(np.abs(ref_wave - 2800.0))
        for code in ("bagpipes", "fsps"):
            k1 = f"{code}_expsfh_tau1gyr"
            k5 = f"{code}_expsfh_tau5gyr"
            if k1 not in ref or k5 not in ref:
                continue
            color1 = ref[k1][uv_idx] / ref[k1][v_idx]
            color5 = ref[k5][uv_idx] / ref[k5][v_idx]
            assert color5 > color1, (
                f"[{code}] tau=5 Gyr not bluer than tau=1 Gyr: "
                f"tau5 UV/V = {color5:.3f}, tau1 UV/V = {color1:.3f}."
            )

    def test_fsps_bagpipes_vband_agreement(self, ref, ref_wave):
        """bagpipes and FSPS should agree within factor 2 at V-band for tau=1 Gyr.

        Both use Chabrier IMF; SSP difference (BC03 vs MILES) limits agreement.
        """
        kf = "fsps_expsfh_tau1gyr"
        kb = "bagpipes_expsfh_tau1gyr"
        if kf not in ref or kb not in ref:
            pytest.skip("Both FSPS and bagpipes needed for this test")

        l_fsps = _band_avg(ref_wave, ref[kf], 5500.0)
        l_bp = _band_avg(ref_wave, ref[kb], 5500.0)
        ratio = l_fsps / l_bp
        assert 0.5 <= ratio <= 2.0, (
            f"FSPS/bagpipes V-band ratio for tau=1 Gyr expSFH = {ratio:.3f} (expect 0.5–2.0). "
            f"FSPS={l_fsps:.3e}, bagpipes={l_bp:.3e} erg/s/Hz/Msun."
        )

    def test_tengri_expsfh_vs_fsps(self, ssp_data, ref, ref_wave):
        """tengri exponential SFH V-band agrees within 35% of FSPS reference.

        Uses dexp SFH (delayed tau); tau=1 Gyr, 5 Gyr observation age.
        M_formed estimated analytically from delayed-tau integral.
        """
        key = "fsps_expsfh_tau1gyr"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        tau_gyr = 1.0
        peak_sfr = 10.0
        m_formed = peak_sfr * tau_gyr * 1.0e9 * np.e  # analytic dexp integral

        wave, sed = _build_tengri_sed_raw(
            ssp_data,
            "dexp",
            {"sfh_dexp_log_peak_sfr": 1.0, "sfh_dexp_tau_gyr": tau_gyr, "sfh_dexp_start_gyr": 0.0},
        )
        sed_per_msun = sed / m_formed

        l_tengri = _band_avg(wave, sed_per_msun, 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)
        ratio = l_tengri / l_fsps
        assert 0.30 <= ratio <= 3.0, (
            f"tengri dexp vs FSPS tau=1 Gyr V-band ratio = {ratio:.3f} (expect 0.3–3.0). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun."
        )


# ---------------------------------------------------------------------------
# Nebular emission — bagpipes + FSPS
# ---------------------------------------------------------------------------


class TestNebularEmission:
    """Cross-validate nebular line + continuum emission.

    Both codes use CLOUDY pre-tabulated grids (bagpipes: BC03+CLOUDY; FSPS: its
    own nebular tables). Checks: lines present, logU trend, inter-code agreement.
    """

    _CASES = ("neb_young_u2", "neb_young_u35", "neb_dusty_u25")

    def test_fsps_nebular_seds_finite(self, ref, ref_wave):
        for name in self._CASES:
            key = f"fsps_nebular_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz")
            assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
            assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_bagpipes_nebular_seds_finite(self, ref, ref_wave):
        for name in self._CASES:
            key = f"bagpipes_nebular_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz")
            assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
            assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_higher_logu_means_more_uv_emission(self, ref, ref_wave):
        """Higher ionisation parameter (logU=-2 vs -3.5) should produce more UV/optical emission.

        logU controls the ionisation state — higher logU = harder radiation field
        = stronger line emission across UV and optical.
        """
        for code in ("bagpipes", "fsps"):
            ku2 = f"{code}_nebular_neb_young_u2"
            ku35 = f"{code}_nebular_neb_young_u35"
            if ku2 not in ref or ku35 not in ref:
                continue
            # Hα at ~6565 Å (strongest optical line) should be stronger at higher logU
            ha_u2 = _band_avg(ref_wave, ref[ku2], 6563.0, half_width=30.0)
            ha_u35 = _band_avg(ref_wave, ref[ku35], 6563.0, half_width=30.0)
            assert ha_u2 > ha_u35, (
                f"[{code}] logU=-2 does not have stronger Hα than logU=-3.5: "
                f"u2={ha_u2:.3e}, u35={ha_u35:.3e}. CLOUDY logU convention inverted?"
            )

    def test_fsps_bagpipes_vband_agreement(self, ref, ref_wave):
        """V-band (5500 Å) agreement within factor 3 between bagpipes and FSPS.

        Nebular continuum contribution + different CLOUDY grids allow wider tolerance.
        """
        kf = "fsps_nebular_neb_young_u2"
        kb = "bagpipes_nebular_neb_young_u2"
        if kf not in ref or kb not in ref:
            pytest.skip("Both FSPS and bagpipes nebular SEDs needed")

        l_fsps = _band_avg(ref_wave, ref[kf], 5500.0)
        l_bp = _band_avg(ref_wave, ref[kb], 5500.0)
        ratio = l_fsps / l_bp
        assert 0.33 <= ratio <= 3.0, (
            f"FSPS/bagpipes V-band ratio (neb_young_u2) = {ratio:.3f} (expect 0.33–3.0). "
            f"FSPS={l_fsps:.3e}, bagpipes={l_bp:.3e} erg/s/Hz/Msun."
        )


# ---------------------------------------------------------------------------
# Calzetti dust law — FSPS only
# ---------------------------------------------------------------------------


class TestCalzettiDust:
    """Cross-validate Calzetti (2000) dust attenuation implementation.

    tengri's `calzetti()` from attenuation.py vs FSPS dust_type=2.
    FSPS dust2 = E(B-V)_stars in Calzetti units.
    """

    _CASES = ("calzetti_ebv015", "calzetti_ebv040", "calzetti_ebv080")

    def test_fsps_calzetti_seds_finite(self, ref, ref_wave):
        for name in self._CASES:
            key = f"fsps_calzetti_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz")
            assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
            assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_higher_ebv_more_attenuated(self, ref, ref_wave):
        """Higher E(B-V) must produce lower V-band luminosity.

        Calzetti law: A(V) = R_V × E(B-V) with R_V = 4.05.
        E(B-V)=0.80 should attenuate V-band by exp(-4.05×0.80×0.92/1.086) more than E(B-V)=0.15.
        """
        k015 = "fsps_calzetti_calzetti_ebv015"
        k080 = "fsps_calzetti_calzetti_ebv080"
        if k015 not in ref or k080 not in ref:
            pytest.skip("Calzetti cases not in npz")

        v_015 = _band_avg(ref_wave, ref[k015], 5500.0)
        v_080 = _band_avg(ref_wave, ref[k080], 5500.0)
        assert v_080 < v_015, (
            f"E(B-V)=0.80 V-band ({v_080:.3e}) not less than E(B-V)=0.15 ({v_015:.3e}). "
            "Calzetti attenuation direction is wrong."
        )

    def test_calzetti_uv_more_attenuated_than_optical(self, ref, ref_wave):
        """UV (2800 Å) must be more attenuated than V-band (5500 Å) under Calzetti.

        Calzetti curve is steeper in UV: A(2800)/A(V) ≈ 2.5.
        This test compares the E(B-V)=0.40 case against E(B-V)=0.15.
        """
        k015 = "fsps_calzetti_calzetti_ebv015"
        k040 = "fsps_calzetti_calzetti_ebv040"
        if k015 not in ref or k040 not in ref:
            pytest.skip("Calzetti cases not in npz")

        uv_ratio = _band_avg(ref_wave, ref[k040], 2800.0, 150.0) / _band_avg(
            ref_wave, ref[k015], 2800.0, 150.0
        )
        v_ratio = _band_avg(ref_wave, ref[k040], 5500.0) / _band_avg(ref_wave, ref[k015], 5500.0)
        assert uv_ratio < v_ratio, (
            f"UV suppression ratio ({uv_ratio:.3f}) not less than V-band ({v_ratio:.3f}). "
            "Calzetti UV attenuation should be steeper than optical."
        )

    def test_tengri_calzetti_vs_fsps(self, ssp_data, ref, ref_wave):
        """tengri calzetti() attenuation vs FSPS dust_type=2 within 15% at V-band.

        Both implement Calzetti (2000) eq 4: k(λ) = 2.659(−2.156 + 1.509/λ − 0.198/λ² + 0.011/λ³)
        + R_V with R_V=4.05. tengri applies exp(−k(λ)×E(B-V)/1.086) per star;
        FSPS applies the same law as dust_type=2 with dust2=E(B-V).
        E(B-V)=0.40, 1 Gyr galaxy, solar Z: attenuation law dominates → 15% is achievable.
        """
        key = "fsps_calzetti_calzetti_ebv040"
        if key not in ref:
            pytest.skip(f"Reference key {key!r} not in npz")

        try:
            from tengri.models.dust.attenuation import calzetti_attenuation
        except ImportError:
            pytest.skip("calzetti_attenuation not importable")

        wave_t, sed_clean, _ = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=1.0)
        ebv = 0.40
        tau_v = calzetti_attenuation(wave_t, ebv)
        sed_dusty = sed_clean * np.exp(-tau_v)

        l_tengri = _band_avg(wave_t, sed_dusty, 5500.0)
        l_fsps = _band_avg(ref_wave, ref[key], 5500.0)
        ratio = l_tengri / l_fsps
        assert 0.85 <= ratio <= 1.15, (
            f"tengri calzetti V-band ratio vs FSPS = {ratio:.3f} (expect 0.85–1.15). "
            f"tengri={l_tengri:.3e}, fsps={l_fsps:.3e} erg/s/Hz/Msun. "
            "Same law, same E(B-V)=0.40: 15% residual → Calzetti R_V or k(λ) normalisation bug."
        )

    def test_tengri_calzetti_uv_attenuation_vs_fsps(self, ssp_data, ref, ref_wave):
        """tengri Calzetti UV (2800 Å) attenuation ratio matches FSPS within 10%.

        The ratio A(2800)/A(5500) is a model-independent quantity — it depends only
        on the dust law shape, not on SSP libraries. Should agree exactly.
        E(B-V)=0.40 vs no-dust baseline (FSPS stellar_starforming, no dust).
        """
        key_dusty = "fsps_calzetti_calzetti_ebv040"
        key_clean = "fsps_stellar_starforming"
        if key_dusty not in ref or key_clean not in ref:
            pytest.skip("Both Calzetti and clean FSPS cases needed")

        try:
            from tengri.models.dust.attenuation import calzetti_attenuation
        except ImportError:
            pytest.skip("calzetti_attenuation not importable")

        # tengri: compute ratio of dusty/clean at UV and V
        wave_t, sed_clean, _ = _build_tengri_sed(ssp_data, start_gyr=0.0, end_gyr=1.0)
        tau_v = calzetti_attenuation(wave_t, 0.40)
        sed_dusty = sed_clean * np.exp(-tau_v)

        # For fair comparison, use the same age galaxy; FSPS Calzetti ref uses 1 Gyr
        tengri_uv_ratio = _band_avg(wave_t, sed_dusty, 2800.0, 150.0) / _band_avg(
            wave_t, sed_clean, 2800.0, 150.0
        )
        fsps_uv_ratio = _band_avg(ref_wave, ref[key_dusty], 2800.0, 150.0) / _band_avg(
            ref_wave, ref[key_clean], 2800.0, 150.0
        )

        ratio = tengri_uv_ratio / fsps_uv_ratio
        assert 0.90 <= ratio <= 1.10, (
            f"UV (2800 Å) dust-fraction ratio tengri/FSPS = {ratio:.3f} (expect 0.90–1.10). "
            f"tengri UV suppression={tengri_uv_ratio:.3f}, FSPS={fsps_uv_ratio:.3f}. "
            "Shape mismatch → k(λ) formula error in calzetti_attenuation()."
        )


# ---------------------------------------------------------------------------
# Dust emission (DL07) — FSPS only, IR wavelength grid
# ---------------------------------------------------------------------------


class TestDustEmission:
    """Cross-validate DL07 dust emission SEDs from FSPS.

    FSPS generates Draine & Li (2007) IR emission when add_dust_emission=True.
    tengri's draine_li2007 uses tabulated templates from data/dl07_templates.npz.
    These tests verify the reference SEDs are physically sensible and that
    tengri reproduces FSPS within a factor of 3 in the far-IR.
    """

    _CASES = ("dustem_warm", "dustem_cold", "dustem_ulirg")
    _WAVE_MIR = 24000.0  # 24 μm — peak of warm dust emission
    _WAVE_FIR = 100000.0  # 100 μm — peak of cold dust emission

    def test_fsps_dustem_seds_finite(self, ref, ref_wave_ir):
        for name in self._CASES:
            key = f"fsps_dustem_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz — FSPS not available")
            assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
            assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_warmer_umin_shifts_peak_to_shorter_wavelengths(self, ref, ref_wave_ir):
        """Higher U_min (more intense radiation field) should shift IR peak blueward.

        Warm case: U_min=5 → hotter dust → peak at shorter λ.
        Cold case: U_min=1 → cooler dust → peak at longer λ.
        Ratio at 24 μm vs 100 μm should be higher for the warm case.
        """
        k_warm = "fsps_dustem_dustem_warm"
        k_cold = "fsps_dustem_dustem_cold"
        if k_warm not in ref or k_cold not in ref:
            pytest.skip("Both warm and cold dustem cases needed")

        mir_warm = _band_avg(ref_wave_ir, ref[k_warm], self._WAVE_MIR, half_width=2000.0)
        fir_warm = _band_avg(ref_wave_ir, ref[k_warm], self._WAVE_FIR, half_width=10000.0)
        mir_cold = _band_avg(ref_wave_ir, ref[k_cold], self._WAVE_MIR, half_width=2000.0)
        fir_cold = _band_avg(ref_wave_ir, ref[k_cold], self._WAVE_FIR, half_width=10000.0)

        ratio_warm = mir_warm / max(fir_warm, 1e-30)
        ratio_cold = mir_cold / max(fir_cold, 1e-30)
        assert ratio_warm > ratio_cold, (
            f"Warm case (U_min=5) MIR/FIR ratio ({ratio_warm:.3f}) not higher than "
            f"cold case (U_min=1) ({ratio_cold:.3f}). "
            "U_min increase should heat dust to shorter emission wavelengths."
        )

    def test_ulirg_has_strong_ir_emission(self, ref, ref_wave_ir):
        """ULIRG (tau_bc=3.0) should have much higher FIR emission than moderate-dust case.

        Strong dust attenuation at UV/optical → strong re-emission in FIR.
        ULIRG (high tau_bc + high U_min=25) vs warm case (tau_bc=1.5 + U_min=5).
        """
        k_ulirg = "fsps_dustem_dustem_ulirg"
        k_warm = "fsps_dustem_dustem_warm"
        if k_ulirg not in ref or k_warm not in ref:
            pytest.skip("ULIRG and warm dustem cases needed")

        fir_ulirg = _band_avg(ref_wave_ir, ref[k_ulirg], self._WAVE_FIR, half_width=20000.0)
        fir_warm = _band_avg(ref_wave_ir, ref[k_warm], self._WAVE_FIR, half_width=20000.0)
        assert fir_ulirg > fir_warm, (
            f"ULIRG FIR ({fir_ulirg:.3e}) not stronger than moderate-dust FIR ({fir_warm:.3e}). "
            "Higher dust optical depth (tau_bc=3.0) should produce more IR emission."
        )


# ---------------------------------------------------------------------------
# Non-parametric (tabular) SFH — FSPS only
# ---------------------------------------------------------------------------


class TestTabularSFH:
    """Cross-validate step-function non-parametric SFH from FSPS sfh=3.

    FSPS tabular SFH is the reference for tengri's continuity_sfh / dirichlet_sfh.
    Tests verify: SEDs sensible, physically expected colour trends hold.
    """

    _CASES = ("step_rising", "step_quenching", "step_bursty")

    def test_fsps_tabsfh_seds_finite(self, ref, ref_wave):
        for name in self._CASES:
            key = f"fsps_tabsfh_{name}"
            if key not in ref:
                pytest.skip(f"Key {key!r} not in npz — FSPS not available")
            assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
            assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_rising_sfh_bluer_than_quenching(self, ref, ref_wave):
        """Rising SFH (high current SFR) should be bluer than quenching SFH.

        step_rising: sfr_per_bin = [5.0, 2.0, 0.8, 0.2] Msun/yr (young → old)
          → high recent SFR → many young stars → blue UV.
        step_quenching: sfr_per_bin = [0.2, 1.0, 3.0, 5.0]
          → low recent SFR → few young stars → red UV.
        """
        k_rise = "fsps_tabsfh_step_rising"
        k_quench = "fsps_tabsfh_step_quenching"
        if k_rise not in ref or k_quench not in ref:
            pytest.skip("Both step_rising and step_quenching needed")

        v_idx = np.argmin(np.abs(ref_wave - 5500.0))
        uv_idx = np.argmin(np.abs(ref_wave - 2800.0))

        color_rise = ref[k_rise][uv_idx] / ref[k_rise][v_idx]
        color_quench = ref[k_quench][uv_idx] / ref[k_quench][v_idx]
        assert color_rise > color_quench, (
            f"Rising SFH UV/V ({color_rise:.3f}) not greater than quenching ({color_quench:.3f}). "
            "Step-function SFH assignment (searchsorted) may be inverted."
        )

    def test_bursty_sfh_has_high_uv(self, ref, ref_wave):
        """Bursty SFH with strong recent burst should have elevated UV emission.

        step_bursty: sfr_per_bin = [8.0, 0.5, 2.0, 0.3] Msun/yr — very high recent SFR.
        UV/V ratio should be at least as high as the quenching case.
        """
        k_bursty = "fsps_tabsfh_step_bursty"
        k_quench = "fsps_tabsfh_step_quenching"
        if k_bursty not in ref or k_quench not in ref:
            pytest.skip("step_bursty and step_quenching needed")

        v_idx = np.argmin(np.abs(ref_wave - 5500.0))
        uv_idx = np.argmin(np.abs(ref_wave - 2800.0))
        color_bursty = ref[k_bursty][uv_idx] / ref[k_bursty][v_idx]
        color_quench = ref[k_quench][uv_idx] / ref[k_quench][v_idx]
        assert color_bursty > color_quench, (
            f"Bursty SFH UV/V ({color_bursty:.3f}) not higher than quenching "
            f"({color_quench:.3f}). Recent burst (sfr=8 Msun/yr) should dominate UV emission."
        )

    def test_tengri_nonparametric_colour_trend(self, ssp_data):
        """tengri continuity_sfh: rising SFH should be bluer than quenching SFH.

        This checks the tengri implementation independently of FSPS.
        Uses the same SFR-per-bin values as TABSFH_CASES in the reference generator.
        """
        try:
            from tengri.models.sfh.nonparametric import continuity_sfh
        except ImportError:
            pytest.skip("continuity_sfh not importable")

        bin_edges = jnp.array([0.0, 0.1, 0.5, 2.0, 6.0])
        sfr_rising = jnp.array([5.0, 2.0, 0.8, 0.2])
        sfr_quenching = jnp.array([0.2, 1.0, 3.0, 5.0])

        wave = jnp.asarray(ssp_data.ssp_wave)

        def uv_over_v(sfr_bins):
            t_obs, sfr_t = continuity_sfh(bin_edges, sfr_bins, n_pts=200)
            # Compute CSP: approximate as sum of SSPs weighted by SFR dt
            from tengri.models.sps.dsps_wrapper import compute_csp_weights

            weights = compute_csp_weights(t_obs, sfr_t)
            sed = jnp.einsum("t,tw->w", weights, ssp_data.ssp_flux[0])  # solar Z
            v = float(jnp.mean(sed[(wave > 5400.0) & (wave < 5600.0)]))
            uv = float(jnp.mean(sed[(wave > 2700.0) & (wave < 2900.0)]))
            return uv / max(v, 1e-30)

        try:
            cr = uv_over_v(sfr_rising)
            cq = uv_over_v(sfr_quenching)
        except Exception as exc:
            pytest.skip(f"continuity_sfh computation failed: {exc}")

        assert cr > cq, (
            f"tengri rising SFH UV/V ({cr:.3f}) not greater than quenching ({cq:.3f}). "
            "Check searchsorted bin assignment in continuity_sfh."
        )


# ---------------------------------------------------------------------------
# IGM attenuation — FSPS only, high-z galaxies
# ---------------------------------------------------------------------------


class TestIGMAttenuation:
    """Cross-validate IGM attenuation (Inoue 2014) from FSPS.

    Reference pairs: `fsps_igm_{name}` (with IGM) and `fsps_igm_{name}_noigm`
    (same galaxy, IGM disabled). The difference quantifies the IGM contribution.

    tengri: `igm_transmission(wave_obs, z)` takes observed-frame wavelengths.
    """

    _CASES = ("highz_z2", "highz_z3", "highz_z5")

    def test_fsps_igm_seds_finite(self, ref, ref_wave):
        for name in self._CASES:
            for suffix in ("", "_noigm"):
                key = f"fsps_igm_{name}{suffix}"
                if key not in ref:
                    continue
                assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
                assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_igm_attenuates_uv(self, ref, ref_wave):
        """IGM must attenuate flux shortward of Lyman-alpha (1216 Å rest) by >50%.

        At z=2, Lyα is observed at 3648 Å. Blueward of Lyα, the IGM Lyman series
        absorbs strongly. The mean transmission at wavelengths 1000–3500 Å (obs)
        at z=2 should be <50% of the no-IGM case (Inoue 2014 predicts near-zero
        below Lyman limit). This is a tight check — if it fails, the IGM model
        is essentially switched off or the Lyman-series opacity is missing.
        """
        zred_map = {"highz_z2": 2.0, "highz_z3": 3.0, "highz_z5": 5.0}
        lya_rest = 1216.0

        for name, zred in zred_map.items():
            key_igm = f"fsps_igm_{name}"
            key_noigm = f"fsps_igm_{name}_noigm"
            if key_igm not in ref or key_noigm not in ref:
                continue

            lya_obs = lya_rest * (1.0 + zred)
            # Check suppression in a band clearly blueward of Lyα
            blue_of_lya = (ref_wave > 1000.0) & (ref_wave < lya_obs - 200.0)
            if not blue_of_lya.any():
                continue

            flux_igm = np.mean(ref[key_igm][blue_of_lya])
            flux_noigm = np.mean(ref[key_noigm][blue_of_lya])

            if flux_noigm < 1e-40:
                continue

            igm_transmission = flux_igm / flux_noigm
            # Inoue 2014: at z=2 the mean transmission blueward of Lyα is <50%;
            # at z=3 and z=5 it approaches zero below the Lyman limit.
            assert igm_transmission < 0.5, (
                f"[{name}] IGM transmission blueward of Lyα = {igm_transmission:.3f} "
                f"(expect <0.5). IGM absorption appears too weak or disabled."
            )

    def test_tengri_igm_vs_fsps(self, ssp_data, ref, ref_wave):
        """tengri igm_transmission (Inoue 2014) matches FSPS (also Inoue 2014) within 10%.

        Both implement the same Inoue (2014) LAF+DLA opacity table. The ratio of
        IGM-attenuated / no-IGM flux at a given observed wavelength should be
        identical between tengri and FSPS for z=2. This is a pure opacity comparison,
        independent of SSP library differences.
        """
        key_igm = "fsps_igm_highz_z2"
        key_noigm = "fsps_igm_highz_z2_noigm"
        if key_igm not in ref or key_noigm not in ref:
            pytest.skip("IGM z=2 reference pair not in npz")

        try:
            from tengri.models.igm import igm_transmission
        except ImportError:
            pytest.skip("tengri igm_transmission not importable")

        zred = 2.0
        # Compare IGM transmission at 2000 Å observed (rest 667 Å — deep in Lyman series)
        obs_band = (ref_wave > 1800.0) & (ref_wave < 2200.0)
        if not obs_band.any():
            pytest.skip("No coverage at 2000 Å observed in wave_grid")

        fsps_trans = np.mean(ref[key_igm][obs_band]) / max(
            np.mean(ref[key_noigm][obs_band]), 1e-40
        )

        # tengri: evaluate transmission at observed-frame wavelengths
        wave_obs_test = ref_wave[obs_band]
        tengri_trans_arr = np.array([float(igm_transmission(w, zred)) for w in wave_obs_test])
        tengri_trans = float(np.mean(tengri_trans_arr))

        # Both should give the same Inoue 2014 transmission; allow 10% residual
        if abs(fsps_trans) < 1e-6:
            pytest.skip("FSPS IGM reference has essentially zero transmission here — skip")

        ratio = tengri_trans / fsps_trans
        assert 0.90 <= ratio <= 1.10, (
            f"tengri/FSPS IGM transmission ratio at 2000 Å (z=2) = {ratio:.3f} "
            f"(expect 0.90–1.10). tengri T={tengri_trans:.4f}, FSPS T={fsps_trans:.4f}. "
            "Both use Inoue 2014 — discrepancy indicates LAF/DLA opacity table mismatch."
        )

    def test_higher_redshift_stronger_igm_suppression(self, ref, ref_wave):
        """Higher redshift → more IGM path length → stronger Lyman-series absorption.

        Compare z=2 vs z=3: UV suppression (normalized by no-IGM flux) should be
        stronger at z=3 (more IGM column along the line of sight).
        """
        key_z2 = "fsps_igm_highz_z2"
        key_z2_noigm = "fsps_igm_highz_z2_noigm"
        key_z3 = "fsps_igm_highz_z3"
        key_z3_noigm = "fsps_igm_highz_z3_noigm"
        if not all(k in ref for k in (key_z2, key_z2_noigm, key_z3, key_z3_noigm)):
            pytest.skip("Need both z=2 and z=3 IGM cases")

        # Compare at 2000 Å observed (rest-frame 667 Å at z=2, 500 Å at z=3 — Lyman series)
        obs_band = (ref_wave > 1800.0) & (ref_wave < 2200.0)
        if not obs_band.any():
            pytest.skip("No coverage at 2000 Å in wave_grid")

        sup_z2 = np.mean(ref[key_z2][obs_band]) / max(np.mean(ref[key_z2_noigm][obs_band]), 1e-40)
        sup_z3 = np.mean(ref[key_z3][obs_band]) / max(np.mean(ref[key_z3_noigm][obs_band]), 1e-40)

        assert sup_z3 <= sup_z2, (
            f"z=3 IGM suppression ({sup_z3:.3f}) not stronger than z=2 ({sup_z2:.3f}). "
            "Higher redshift should accumulate more IGM opacity at fixed observed wavelength."
        )


# ---------------------------------------------------------------------------
# AGN torus (Nenkova) — FSPS only
# ---------------------------------------------------------------------------


class TestAGNTorus:
    """Cross-validate AGN torus (Nenkova+2008) SEDs from FSPS.

    FSPS fagn parameter controls the AGN contribution to bolometric luminosity.
    Reference pairs: `fsps_agn_{name}` (with AGN) and `fsps_agn_{name}_noagn`.

    Note: FSPS Nenkova torus model is NOT the same as tengri's K&D 3-zone disc +
    SKIRTOR model. These tests verify the IR torus excess is present and
    monotonically increases with fagn, not exact numerical agreement.
    """

    _CASES = ("agn_frac01_tau10", "agn_frac03_tau20")

    def test_fsps_agn_seds_finite(self, ref, ref_wave):
        for name in self._CASES:
            for suffix in ("", "_noagn"):
                key = f"fsps_agn_{name}{suffix}"
                if key not in ref:
                    continue
                assert np.all(np.isfinite(ref[key])), f"NaN/Inf in {key}"
                assert np.all(ref[key] >= 0.0), f"Negative flux in {key}"

    def test_agn_adds_ir_excess(self, ref, ref_wave):
        """AGN torus must increase mid-IR flux compared to no-AGN baseline.

        Nenkova torus re-emits in the near/mid IR (1–20 μm). We check that
        the AGN model has more flux at 8000–10000 Å (near-IR, within our grid).
        """
        for name in self._CASES:
            key_agn = f"fsps_agn_{name}"
            key_noagn = f"fsps_agn_{name}_noagn"
            if key_agn not in ref or key_noagn not in ref:
                continue

            # Near-IR at ~9000 Å (within WAVE_GRID upper end)
            nir = (ref_wave > 8000.0) & (ref_wave < 11000.0)
            if not nir.any():
                continue

            l_agn = np.mean(ref[key_agn][nir])
            l_noagn = np.mean(ref[key_noagn][nir])
            assert l_agn >= l_noagn, (
                f"[{name}] AGN near-IR ({l_agn:.3e}) not greater than no-AGN ({l_noagn:.3e}). "
                "Nenkova torus should add IR emission."
            )

    def test_higher_fagn_means_more_ir(self, ref, ref_wave):
        """Higher AGN fraction (fagn=0.3 vs 0.1) should produce more near-IR emission.

        Controls: both cases have same stellar population (age=3 Gyr, solar Z).
        Only fagn differs — higher fagn = more AGN contribution = brighter IR.
        """
        k_frac01 = "fsps_agn_agn_frac01_tau10"
        k_frac03 = "fsps_agn_agn_frac03_tau20"
        if k_frac01 not in ref or k_frac03 not in ref:
            pytest.skip("Both AGN fraction cases needed")

        nir = (ref_wave > 8000.0) & (ref_wave < 11000.0)
        if not nir.any():
            pytest.skip("No near-IR coverage in wave_grid")

        l_frac01 = np.mean(ref[k_frac01][nir])
        l_frac03 = np.mean(ref[k_frac03][nir])
        assert l_frac03 >= l_frac01, (
            f"fagn=0.3 near-IR ({l_frac03:.3e}) not greater than fagn=0.1 ({l_frac01:.3e}). "
            "AGN IR excess should scale with fagn."
        )

    def test_agn_does_not_suppress_optical(self, ref, ref_wave):
        """Adding AGN torus should not significantly reduce optical stellar flux.

        The torus model adds IR emission but should not attenuate the stellar
        optical SED (FSPS handles them as additive contributions).
        """
        for name in self._CASES:
            key_agn = f"fsps_agn_{name}"
            key_noagn = f"fsps_agn_{name}_noagn"
            if key_agn not in ref or key_noagn not in ref:
                continue

            v_agn = _band_avg(ref_wave, ref[key_agn], 5500.0)
            v_noagn = _band_avg(ref_wave, ref[key_noagn], 5500.0)
            # AGN should not suppress optical by more than 10%
            ratio = v_agn / max(v_noagn, 1e-40)
            assert ratio >= 0.90, (
                f"[{name}] AGN V-band ({v_agn:.3e}) is more than 10% below "
                f"no-AGN ({v_noagn:.3e}). Nenkova torus should not attenuate stellar optical."
            )
