#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Declarative metadata for the six demonstration configurations.

Separated from `configs.py` because that module imports tengri, and so JAX, to
build models. Everything here is plain data, so a consumer that only needs to
know what a configuration claims to be -- a figure reading posterior NPZs, the
provenance audit -- can read it without paying for the import.

`configs.py` re-exports both names, so `from configs import CONFIGS` keeps
working.
"""

from __future__ import annotations

SSP_FOR_CONFIG = {
    "I": "fsps_mist_c3k_a_chabrier",
    "II": "fsps_prsc_c3k_a_chabrier",
    "III": "fsps_mist_miles_chabrier",
    "IV": "fsps_prsc_miles_chabrier",
    "V": "bpss_stars_c3k_a_chabrier",
    "VI": "fsps_mist_c3k_a_chabrier",
}

CONFIGS = {
    "I": {
        "key": "I",
        "dust_param": "dust_tau_diff",
        "name": "continuity, MIST/C3K",
        "sfh": "continuity, 7 bins",
        "sfh_type": "continuity",
        "library": "FSPS MIST/C3K",
        "attenuation": "Kriek+13, 2-comp",
        "dust_ir": "Draine+2014",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["I"],
        "n_free": None,
    },
    "II": {
        "key": "II",
        "dust_param": "dust_tau_v",
        "name": "double power law, PARSEC/C3K",
        "sfh": "double power law",
        "sfh_type": "dpl",
        "library": "FSPS PARSEC/C3K",
        "attenuation": "Calzetti, 1-comp",
        "dust_ir": "Dale+2014",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["II"],
        "n_free": None,
    },
    "III": {
        "key": "III",
        "dust_param": "dust_tau_diff",
        "name": "delayed-tau, MIST/MILES",
        "sfh": "delayed-tau",
        "sfh_type": "delayed",
        "library": "FSPS MIST/MILES",
        "attenuation": "Charlot+2000, 2-comp",
        "dust_ir": "THEMIS",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["III"],
        "n_free": None,
    },
    "IV": {
        "key": "IV",
        "dust_param": "dust_tau_diff",
        "name": "Dirichlet, PARSEC/MILES",
        "sfh": "Dirichlet, 7 bins",
        "sfh_type": "dirichlet",
        "library": "FSPS PARSEC/MILES",
        "attenuation": "Kriek+13, 2-comp",
        "dust_ir": "Casey+2012",
        "nebular": "Cloudy, free logU",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["IV"],
        "n_free": None,
    },
    "V": {
        "key": "V",
        "dust_param": "dust_tau_v",
        "name": "log-normal, BPASS",
        "sfh": "log-normal",
        "sfh_type": "lnorm",
        "library": "BPASS C3K",
        "attenuation": "SMC, 1-comp",
        "dust_ir": "Dale+2014",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["V"],
        "n_free": None,
    },
    "VI": {
        "key": "VI",
        "dust_param": "dust_tau_diff",
        "name": "continuity + AGN disc and torus",
        "sfh": "continuity, 7 bins",
        "sfh_type": "continuity",
        "library": "FSPS MIST/C3K",
        "attenuation": "Kriek+13, 2-comp",
        "dust_ir": "Draine+2014",
        "nebular": "Cue",
        "agn": True,
        "ssp_grid": SSP_FOR_CONFIG["VI"],
        "n_free": None,
    },
}

XLIKE_SSP = {
    "cigale_like": "bc03_pdva_stelib_chabrier",
    "prospector_like": "fsps_mist_miles_chabrier",
    "bagpipes_like": "bc03_pdva_stelib_chabrier",
    "beagle_like": "bc03_pdva_stelib_chabrier",
    "dense_basis_like": "fsps_mist_miles_chabrier",
}

XLIKE_KEYS = ["cigale_like", "prospector_like", "bagpipes_like", "beagle_like", "dense_basis_like"]

XLIKE_CONFIGS = {
    "cigale_like": {
        "key": "cigale_like",
        "code": "CIGALE",
        "name": "delayed-tau, BC03, leitherer02 2-comp",
        "parity_check": True,
        "dust_param": "dust_tau_diff",
        "sfh": "delayed-tau",
        "sfh_type": "delayed",
        "library": "BC03 2003 STELIB Chabrier",
        "attenuation": "Leitherer+02, 2-comp",
        "dust_ir": "Dale+2014 CIGALE",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["cigale_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Grid",
            "sfh": "Flex.",
            "ssp": "Multiple",
            "nebular": "C13",
            "dust_att": "Multiple",
            "dust_em": "Multiple",
            "agn": "Yes",
        },
        "mismatches": [
            "BC03 grid shipped with CIGALE (workshop run) vs tengri's registered BC03 (Padova 1994 tracks, STELIB, Chabrier IMF)",
            "Two-component leitherer02 screens with free tau_bc and tau_diff vs CIGALE's fixed birth-cloud/diffuse ratio (0.44 factor)",
            "Cue emulator (trained on Cloudy 17) vs CIGALE's Cloudy 13 grids",
            "Continuous metallicity prior over the grid vs CIGALE's discrete values",
            "1 Gyr age floor vs CIGALE's workshop default (unrecorded)",
        ],
        "mismatches_text": [
            "BC03 library version differences (workshop grid vs. registered Padova 1994 isochrones with STELIB spectra)",
            "Attenuation law details differ: Leitherer et al. (2002) two-screen model with free birth-cloud and diffuse optical depths versus CIGALE's fixed screen ratio",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 17.02) versus CIGALE's Cloudy 13 grids",
            "Metallicity treatment: continuous interpolation over the stellar library grid versus discrete metallicity values",
            "Minimum stellar age: 1 Gyr floor versus CIGALE workshop default (not recorded in external metadata)",
        ],
        "mismatch_sources": [
            "reproduction/cigale/01_cigale.py:24--26",
            "reproduction/cigale/01_cigale.py:126--134",
            "Pacifici et al. (2023) Table 1",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
        ],
    },
    "prospector_like": {
        "key": "prospector_like",
        "code": "Prospector",
        "name": "continuity, FSPS MIST/MILES, calzetti 2-comp",
        "parity_check": True,
        "dust_param": "dust_tau_diff",
        "sfh": "continuity, 7 bins",
        "sfh_type": "continuity",
        "library": "FSPS MIST/MILES",
        "attenuation": "Calzetti, 2-comp",
        "dust_ir": "Draine+2007",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["prospector_like"],
        "n_free": None,
        "mass_definition": "formed",
        "fiducial_table1": {
            "sampler": "Nested sam.",
            "sfh": "Non-param.",
            "ssp": "FSPS",
            "nebular": "C13",
            "dust_att": "2 comp.",
            "dust_em": "Single",
            "agn": "Yes",
        },
        "mismatches": [
            "Continuity with Student-t prior vs Prospector workshop priors (unrecorded in output)",
            "Cue emulator (trained on Cloudy 17) vs FSPS default Cloudy 13",
            "7-bin continuity SFH edges vs Prospector's parameter bins (workshop metadata unrecorded)",
            "Continuous metallicity prior over the grid vs Prospector's discrete values",
            "1 Gyr age floor vs Prospector's workshop default",
            "Energy balance excludes lambda<912 A (far-IR ~11% lower than exact integration, outside the fitted UV-to-IRAC bands)",
        ],
        "mismatches_text": [
            "Star formation history prior: Student-t distribution on continuity parameters versus Prospector's priors (not recorded in workshop outputs)",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 17.02) versus FSPS default Cloudy 13 grids",
            "Star formation history discretization: seven-bin continuity model with specific age edges versus Prospector's binning scheme (workshop metadata unavailable)",
            "Metallicity treatment: continuous interpolation over the stellar library grid versus discrete metallicity values",
            "Minimum stellar age: 1 Gyr floor versus Prospector workshop default (not recorded in external metadata)",
            "Dust--star energy balance: computed up to 912 Angstrom (excludes far-infrared, about 11 percent lower than exact integration) but outside the fitted UV-to-IRAC wavelength range",
        ],
        "mismatch_sources": [
            "analysis/paper1/configs.py:178 (_continuity_sfh)",
            "reproduction/prospector/01_prospector.py:33--38",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "reproduction/prospector/01_prospector.py:1379--1382",
        ],
    },
    "bagpipes_like": {
        "key": "bagpipes_like",
        "code": "BAGPIPES",
        "name": "double power law, BC03, calzetti 1-comp",
        "parity_check": True,
        "dust_param": "dust_tau_v",
        "sfh": "double power law",
        "sfh_type": "dpl",
        "library": "BC03 2003 STELIB Chabrier",
        "attenuation": "Calzetti, 1-comp",
        "dust_ir": "Draine+2007",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["bagpipes_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Nested sam.",
            "sfh": "Flex.",
            "ssp": "Multiple",
            "nebular": "C17",
            "dust_att": "Multiple",
            "dust_em": "Single",
            "agn": "No",
        },
        "mismatches": [
            "BAGPIPES's default stellar library, BC03 with MILES and a Kroupa IMF, against tengri's registered BC03 (Padova 1994 tracks, STELIB, Chabrier IMF)",
            "dpl priors Uniform(alpha, beta) vs BAGPIPES log-uniform convention (exact workshop priors unrecorded in output)",
            "Cue emulator (trained on Cloudy 17) vs BAGPIPES Cloudy 17 grids",
            "Continuous metallicity prior vs BAGPIPES discrete values",
            "1 Gyr age floor vs BAGPIPES workshop default",
            "Single-component Calzetti (tau_v screen) vs BAGPIPES two-component Calzetti with birth-cloud term off (physically equivalent)",
        ],
        "mismatches_text": [
            "Stellar library configuration: BC03 library version difference (MILES spectral library with Kroupa initial mass function versus Padova 1994 isochrones with STELIB and Chabrier IMF)",
            "Star formation history priors: uniform distributions on power-law slopes versus BAGPIPES log-uniform convention (exact workshop priors not recorded in external metadata)",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 17.02) matched to BAGPIPES Cloudy 17 grids",
            "Metallicity treatment: continuous interpolation over the stellar library grid versus discrete metallicity values",
            "Minimum stellar age: 1 Gyr floor versus BAGPIPES workshop default (not recorded in external metadata)",
            "Dust attenuation model: single Calzetti screen (optical depth tau_V) versus BAGPIPES two-component Calzetti with birth-cloud contribution turned off, which is physically equivalent",
        ],
        "mismatch_sources": [
            "reproduction/bagpipes/01_bagpipes.py:136--142 (bc03_miles_from_bagpipes.h5)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "reproduction/bagpipes/01_bagpipes.py:43--46",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
        ],
    },
    "beagle_like": {
        "key": "beagle_like",
        "code": "BEAGLE",
        "name": "delayed-tau, BC03(16), power law 2-comp, no dust IR",
        "parity_check": False,
        "dust_param": "dust_tau_diff",
        "sfh": "delayed-tau",
        "sfh_type": "delayed",
        "library": "BC03 2003 STELIB Chabrier",
        "attenuation": "Charlot+Fall 2000, 2-comp",
        "dust_ir": "None",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["beagle_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Nested sam.",
            "sfh": "Flex. param.",
            "ssp": "BC03(16)",
            "nebular": "C13",
            "dust_att": "2 comp.",
            "dust_em": "No",
            "agn": "No",
        },
        "mismatches": [
            "No reproduction notebook available; parity check not performed",
            "BC03 2003 (Padova 1994 tracks, STELIB, Chabrier) vs BEAGLE Table 1: BC03(16)",
            "Cue emulator (trained on Cloudy 17) vs BEAGLE's Cloudy 13 nebular grids",
            "Power law attenuation (Charlot & Fall 2000) without BEAGLE's mu/tau_V parametrization",
            "No optional burst component (BEAGLE's optional feature not included)",
            "1 Gyr age floor vs BEAGLE's workshop default",
        ],
        "mismatches_text": [
            "No reproduction notebook available; parity check against BEAGLE was not performed",
            "BC03 library version: registered BC03 (Padova 1994 isochrones, STELIB spectra, Chabrier IMF) versus BEAGLE uses BC03(16) variant",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 17.02) versus BEAGLE Cloudy 13 grids",
            "Dust attenuation parametrization: power-law form of Charlot and Fall (2000) without BEAGLE's additional mu and tau_V degrees of freedom",
            "Star formation history: no optional starburst component (BEAGLE offers this as an optional feature)",
            "Minimum stellar age: 1 Gyr floor versus BEAGLE workshop default (not recorded in external metadata)",
        ],
        "mismatch_sources": [
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "Pacifici et al. (2023) Table 1",
            "Pacifici et al. (2023) Table 1 (C13)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
        ],
    },
    "dense_basis_like": {
        "key": "dense_basis_like",
        "code": "Dense_Basis",
        "name": "dense basis, FSPS MIST/MILES, calzetti 1-comp",
        "parity_check": False,
        "dust_param": "dust_tau_v",
        "sfh": "dense basis quantiles",
        "sfh_type": "dense_basis",
        "library": "FSPS MIST/MILES",
        "attenuation": "Calzetti, 1-comp",
        "dust_ir": "Draine+2007",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["dense_basis_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Atlas",
            "sfh": "Non-param.",
            "ssp": "FSPS",
            "nebular": "C",
            "dust_att": "Multiple",
            "dust_em": "Single",
            "agn": "No",
        },
        "mismatches": [
            "No reproduction notebook available; parity check not performed",
            "Dense Basis draws the mass-time quantiles from a Dirichlet prior (concentration 5 by default); tengri draws three independent uniform fractions and sorts them, so its prior is their order statistics",
            "FSPS library isochrone and spectral library versions not recorded in external metadata",
            "Cue emulator (trained on Cloudy 17) vs FSPS default Cloudy",
        ],
        "mismatches_text": [
            "No reproduction notebook available; parity check against Dense Basis was not performed",
            "Star formation history priors: Dense Basis uses a Dirichlet prior with concentration parameter 5, while tengri uses order statistics of independent uniform fractions, yielding different prior distributions",
            "FSPS library configuration: isochrone and spectral library versions not recorded in Dense Basis external metadata",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 17.02) versus FSPS default Cloudy grids",
        ],
        "mismatch_sources": [
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "site-packages/dense_basis/priors.py:84,121; src/tengri/components/stellar/sfh/dense_basis.py:487",
            "art_sedfitting/code_outputs/header (absence of the setting)",
            "art_sedfitting/code_outputs/header (absence of the setting)",
        ],
        "notes": [
            "Age of universe set to cosmic age at redshift z (tengri's registry default is 13.47 Gyr at z=0)",
        ],
        "notes_sources": [
            "src/tengri/components/stellar/sfh/registry.py:2007",
        ],
    },
}
