#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Declarative metadata for the six demonstration configurations.

Separated from `configs.py` because that module imports tengri, and so JAX, to
build models. Everything here is plain data, so a consumer that only needs to
know what a configuration claims to be -- a figure reading posterior NPZs, the
provenance audit -- can read it without paying for the import.

`configs.py` re-exports both names, so `from configs import CONFIGS` keeps
working.
"""

from __future__ import annotations

SSP_FOR_CONFIG = {
    "I": "fsps_mist_c3k_a_chabrier",
    "II": "fsps_prsc_c3k_a_chabrier",
    "III": "fsps_mist_miles_chabrier",
    "IV": "fsps_prsc_miles_chabrier",
    "V": "bpss_stars_c3k_a_chabrier",
    "VI": "fsps_mist_c3k_a_chabrier",
}

CONFIGS = {
    "I": {
        "key": "I",
        "dust_param": "dust_tau_diff",
        "name": "continuity, MIST/C3K",
        "sfh": "continuity, 7 bins",
        "sfh_type": "continuity",
        "library": "FSPS MIST/C3K",
        "attenuation": "Kriek+13, 2-comp",
        "dust_ir": "Draine+2014",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["I"],
        "n_free": None,
    },
    "II": {
        "key": "II",
        "dust_param": "dust_tau_v",
        "name": "double power law, PARSEC/C3K",
        "sfh": "double power law",
        "sfh_type": "dpl",
        "library": "FSPS PARSEC/C3K",
        "attenuation": "Calzetti, 1-comp",
        "dust_ir": "Dale+2014",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["II"],
        "n_free": None,
    },
    "III": {
        "key": "III",
        "dust_param": "dust_tau_diff",
        "name": "delayed-tau, MIST/MILES",
        "sfh": "delayed-tau",
        "sfh_type": "delayed",
        "library": "FSPS MIST/MILES",
        "attenuation": "Charlot+2000, 2-comp",
        "dust_ir": "THEMIS",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["III"],
        "n_free": None,
    },
    "IV": {
        "key": "IV",
        "dust_param": "dust_tau_diff",
        "name": "Dirichlet, PARSEC/MILES",
        "sfh": "Dirichlet, 7 bins",
        "sfh_type": "dirichlet",
        "library": "FSPS PARSEC/MILES",
        "attenuation": "Kriek+13, 2-comp",
        "dust_ir": "Casey+2012",
        "nebular": "Cloudy, free logU",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["IV"],
        "n_free": None,
    },
    "V": {
        "key": "V",
        "dust_param": "dust_tau_v",
        "name": "log-normal, BPASS",
        "sfh": "log-normal",
        "sfh_type": "lnorm",
        "library": "BPASS C3K",
        "attenuation": "SMC, 1-comp",
        "dust_ir": "Dale+2014",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": SSP_FOR_CONFIG["V"],
        "n_free": None,
    },
    "VI": {
        "key": "VI",
        "dust_param": "dust_tau_diff",
        "name": "continuity + AGN disc and torus",
        "sfh": "continuity, 7 bins",
        "sfh_type": "continuity",
        "library": "FSPS MIST/C3K",
        "attenuation": "Kriek+13, 2-comp",
        "dust_ir": "Draine+2014",
        "nebular": "Cue",
        "agn": True,
        "ssp_grid": SSP_FOR_CONFIG["VI"],
        "n_free": None,
    },
}

XLIKE_SSP = {
    "cigale_like": "bc03_pdva_stelib_chabrier",
    "prospector_like": "fsps_mist_miles_chabrier",
    "bagpipes_like": "bc03_pdva_stelib_chabrier",
    "beagle_like": "bc03_pdva_stelib_chabrier",
    "dense_basis_like": "fsps_mist_miles_chabrier",
}

XLIKE_KEYS = ["cigale_like", "prospector_like", "bagpipes_like", "beagle_like", "dense_basis_like"]

XLIKE_CONFIGS = {
    "cigale_like": {
        "key": "cigale_like",
        "code": "CIGALE",
        "name": "delayed-tau, BC03, leitherer02 2-comp",
        "parity_check": True,
        "dust_param": "dust_tau_diff",
        "sfh": "delayed-tau",
        "sfh_type": "delayed",
        "library": "BC03 2003 STELIB Chabrier",
        "attenuation": "Leitherer+02, 2-comp",
        "dust_ir": "Dale+2014 CIGALE",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["cigale_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Grid",
            "sfh": "Flex.",
            "ssp": "Multiple",
            "nebular": "C13",
            "dust_att": "Multiple",
            "dust_em": "Multiple",
            "agn": "Yes",
        },
        "mismatches": [
            "The CIGALE-like configuration uses tengri's registered BC03 grid (Padova 1994 tracks, STELIB, Chabrier IMF) rather than the CIGALE-bundled BC03 grid used in the parity reproduction",
            "CIGALE's modified-starburst attenuation applies one Calzetti and Leitherer et al. (2002) screen to all stars, with continuum E(B-V) = 0.44 times the line E(B-V); the CIGALE-like configuration fits two screens with free birth-cloud and diffuse optical depths (the parity reproduction sets the birth-cloud depth to zero). Which attenuation module the workshop run used is not recorded",
            "CIGALE's BC03 module accepts only six metallicities (Z = 0.0001, 0.0004, 0.004, 0.008, 0.02, 0.05); the CIGALE-like configuration samples metallicity continuously within the grid",
            "Cue emulator (trained on Cloudy 22.00) vs CIGALE's Cloudy 13 grids",
            "Formation age restricted to at least 1 Gyr, the grid's convention; the workshop run's age prior is not recorded",
        ],
        "mismatches_text": [
            "The CIGALE-like configuration uses tengri's registered BC03 grid (Padova 1994 tracks, STELIB spectra, Chabrier IMF) rather than the CIGALE-bundled BC03 grid used in the parity reproduction",
            "CIGALE's modified-starburst attenuation applies one Calzetti and Leitherer et al. (2002) screen to all stars, with continuum E(B-V) = 0.44 times the line E(B-V); the CIGALE-like configuration fits two screens with free birth-cloud and diffuse optical depths (the parity reproduction sets the birth-cloud depth to zero). Which attenuation module the workshop run used is not recorded",
            "CIGALE's BC03 module accepts only six metallicities (Z = 0.0001, 0.0004, 0.004, 0.008, 0.02, 0.05); the CIGALE-like configuration samples metallicity continuously within the grid",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 22.00) versus CIGALE's Cloudy 13 grids",
            "Formation age restricted to at least 1 Gyr, the grid's convention; the workshop run's age prior is not recorded",
        ],
        "mismatch_sources": [
            "analysis/paper1/config_metadata.py (XLIKE_SSP cigale_like); reproduction/cigale/01_cigale.py:24--26",
            "pcigale/sed_modules/dustatt_modified_starburst.py:311--316; reproduction/cigale/01_cigale.py:126--134; reproduction/cigale/01_cigale.py:1241; art_sedfitting/code_outputs/header (absence of the setting)",
            "pcigale/sed_modules/bc03.py:33--38; analysis/paper1/xlike_configs.py:44",
            "Li et al. 2025, ApJ 986, 9 (arXiv:2405.04598), Section 2; Pacifici et al. (2023) Table 1",
            "analysis/paper1/configs.py:30--36; analysis/paper1/xlike_configs.py:42",
        ],
    },
    "prospector_like": {
        "key": "prospector_like",
        "code": "Prospector",
        "name": "continuity, FSPS MIST/MILES, calzetti 2-comp",
        "parity_check": True,
        "dust_param": "dust_tau_diff",
        "sfh": "continuity, 7 bins",
        "sfh_type": "continuity",
        "library": "FSPS MIST/MILES",
        "attenuation": "Calzetti, 2-comp",
        "dust_ir": "Draine+2007",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["prospector_like"],
        "n_free": None,
        "mass_definition": "formed",
        "fiducial_table1": {
            "sampler": "Nested sam.",
            "sfh": "Non-param.",
            "ssp": "FSPS",
            "nebular": "C13",
            "dust_att": "2 comp.",
            "dust_em": "Single",
            "agn": "Yes",
        },
        "mismatches": [
            "Cue emulator (trained on Cloudy 22.00) vs FSPS default Cloudy 13",
            "Energy balance excludes lambda<912 A (far-IR ~11% lower than exact integration, outside the fitted UV-to-IRAC bands)",
        ],
        "mismatches_text": [
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 22.00) versus FSPS Cloudy 13 grids via Byler et al. (2017)",
            "Dust energy balance: the absorbed luminosity excludes radiation shortward of 912 Angstrom, which lowers the far-infrared output by about 11 percent relative to exact integration; the far-infrared lies outside the fitted UV-to-IRAC wavelength range",
        ],
        "mismatch_sources": [
            "reproduction/prospector/01_prospector.py:33--38; Pacifici et al. (2023) Table 1; Li et al. 2025, ApJ 986, 9 (arXiv:2405.04598), Section 2",
            "reproduction/prospector/01_prospector.py:1379--1382; paper Section subsec:demonstration:data",
        ],
        "notes": [
            "The continuity prior on the log SFR ratios, Student-t (mean 0, scale 0.3, 2 degrees of freedom), is identical to Prospector's continuity_sfh template",
            "The workshop catalog does not record Prospector's age bins; the seven-bin continuity model uses tengri's age edges",
        ],
        "notes_sources": [
            "prospect/models/templates.py:556--559; src/tengri/components/stellar/sfh/registry.py:1543",
            "art_sedfitting/code_outputs/header (absence of the setting)",
        ],
    },
    "bagpipes_like": {
        "key": "bagpipes_like",
        "code": "BAGPIPES",
        "name": "double power law, BC03, calzetti 1-comp",
        "parity_check": True,
        "dust_param": "dust_tau_v",
        "sfh": "double power law",
        "sfh_type": "dpl",
        "library": "BC03 2003 STELIB Chabrier",
        "attenuation": "Calzetti, 1-comp",
        "dust_ir": "Draine+2007",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["bagpipes_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Nested sam.",
            "sfh": "Flex.",
            "ssp": "Multiple",
            "nebular": "C17",
            "dust_att": "Multiple",
            "dust_em": "Single",
            "agn": "No",
        },
        "mismatches": [
            "BAGPIPES's default stellar library, BC03 with MILES and a Kroupa IMF, against tengri's registered BC03 (Padova 1994 tracks, STELIB, Chabrier IMF)",
            "Table 1 lists Cloudy 17 (C17) for the workshop-era BAGPIPES; current BAGPIPES releases ship Cloudy 25 grids; tengri uses Cue, trained on Cloudy 22.00",
            "Formation age restricted to at least 1 Gyr, the grid's convention; the workshop run's age prior is not recorded",
            "Single dust screen (Calzetti et al. 2000), as in the parity reproduction, which switches the birth-cloud term off; the workshop run's dust configuration is not recorded",
        ],
        "mismatches_text": [
            "Stellar library configuration: BC03 with the MILES spectral library and a Kroupa initial mass function (BAGPIPES) versus Padova 1994 isochrones with STELIB and a Chabrier IMF (tengri)",
            "Nebular emission models: Table 1 lists Cloudy 17 (C17) for the workshop-era BAGPIPES; current BAGPIPES releases ship Cloudy 25 grids; tengri uses the Cue emulator, trained on Cloudy 22.00",
            "Formation age restricted to at least 1 Gyr, the grid's convention; the workshop run's age prior is not recorded",
            "Single dust screen (Calzetti et al. 2000), as in the parity reproduction, which switches the birth-cloud term off; the workshop run's dust configuration is not recorded",
        ],
        "mismatch_sources": [
            "reproduction/bagpipes/01_bagpipes.py:123; reproduction/bagpipes/_drivers/bagpipes_ssp_to_dsps.py:178; bagpipes/config.py:106--107",
            "Pacifici et al. (2023) Table 1; bagpipes/config.py:106--107; Li et al. 2025, ApJ 986, 9 (arXiv:2405.04598), Section 2",
            "analysis/paper1/configs.py:30--36; analysis/paper1/xlike_configs.py:148",
            "reproduction/bagpipes/01_bagpipes.py:962--964",
        ],
    },
    "beagle_like": {
        "key": "beagle_like",
        "code": "BEAGLE",
        "name": "delayed-tau, BC03(16), power law 2-comp, no dust IR",
        "parity_check": False,
        "dust_param": "dust_tau_diff",
        "sfh": "delayed-tau",
        "sfh_type": "delayed",
        "library": "BC03 2003 STELIB Chabrier",
        "attenuation": "Charlot+Fall 2000, 2-comp",
        "dust_ir": "None",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["beagle_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Nested sam.",
            "sfh": "Flex. param.",
            "ssp": "BC03(16)",
            "nebular": "C13",
            "dust_att": "2 comp.",
            "dust_em": "No",
            "agn": "No",
        },
        "mismatches": [
            "No reproduction notebook available; parity check not performed",
            "BC03 2003 (Padova 1994 tracks, STELIB, Chabrier) vs BEAGLE Table 1: BC03(16)",
            "Cue emulator (trained on Cloudy 22.00) vs BEAGLE's Cloudy 13 nebular grids",
            "Two-component Charlot and Fall (2000) attenuation parametrized by (birth-cloud, diffuse) optical depths in place of BEAGLE's (tau_V, mu)",
            "Formation age restricted to at least 1 Gyr, the grid's convention; the workshop run's age prior is not recorded",
        ],
        "mismatches_text": [
            "No reproduction notebook available; parity check against BEAGLE was not performed",
            "BC03 library: registered BC03 (Padova 1994 isochrones, STELIB spectra, Chabrier IMF) versus the BC03(16) entry of Table 1 for BEAGLE",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 22.00) versus BEAGLE Cloudy 13 grids",
            "Two-component Charlot and Fall (2000) attenuation parametrized by (birth-cloud, diffuse) optical depths in place of BEAGLE's (tau_V, mu); the number of free parameters is the same",
            "Formation age restricted to at least 1 Gyr, the grid's convention; the workshop run's age prior is not recorded",
        ],
        "mismatch_sources": [
            "analysis/paper1/config_metadata.py:264 (parity_check False)",
            "Pacifici et al. (2023) Table 1",
            "Pacifici et al. (2023) Table 1 (C13); Li et al. 2025, ApJ 986, 9 (arXiv:2405.04598), Section 2",
            "art_sedfitting/code_outputs/BEAGLE_summary_catalogue_z1.fits HDU3 columns tauV_eff, mu; analysis/paper1/xlike_configs.py:207--216",
            "analysis/paper1/configs.py:30--36; analysis/paper1/xlike_configs.py:203",
        ],
    },
    "dense_basis_like": {
        "key": "dense_basis_like",
        "code": "Dense_Basis",
        "name": "dense basis, FSPS MIST/MILES, calzetti 1-comp",
        "parity_check": False,
        "dust_param": "dust_tau_v",
        "sfh": "dense basis quantiles",
        "sfh_type": "dense_basis",
        "library": "FSPS MIST/MILES",
        "attenuation": "Calzetti, 1-comp",
        "dust_ir": "Draine+2007",
        "nebular": "Cue",
        "agn": False,
        "ssp_grid": XLIKE_SSP["dense_basis_like"],
        "n_free": None,
        "mass_definition": "surviving",
        "fiducial_table1": {
            "sampler": "Atlas",
            "sfh": "Non-param.",
            "ssp": "FSPS",
            "nebular": "C",
            "dust_att": "Multiple",
            "dust_em": "Single",
            "agn": "No",
        },
        "mismatches": [
            "No reproduction notebook available; parity check not performed",
            "Dense Basis draws the mass-time quantiles from a Dirichlet prior (concentration 5 by default); tengri draws three independent uniform fractions and sorts them, so its prior is their order statistics",
            "Cue emulator (trained on Cloudy 22.00) vs Cloudy with no version year in Pacifici et al. (2023) Table 1 (entry C)",
        ],
        "mismatches_text": [
            "No reproduction notebook available; parity check against Dense Basis was not performed",
            "Star formation history priors: Dense Basis uses a Dirichlet prior with concentration parameter 5, while tengri uses order statistics of independent uniform fractions, yielding different prior distributions",
            "Nebular emission models: Cue photoionization emulator (trained on Cloudy 22.00) versus Cloudy, for which Table 1 of Pacifici et al. (2023) lists no version year (entry C)",
        ],
        "mismatch_sources": [
            "analysis/paper1/config_metadata.py:311 (parity_check False)",
            "dense_basis/priors.py:84,121; src/tengri/components/stellar/sfh/dense_basis.py:487",
            "Pacifici et al. (2023) Table 1 (C); Li et al. 2025, ApJ 986, 9 (arXiv:2405.04598), Section 2",
        ],
        "notes": [
            "Age of universe set to cosmic age at redshift z (tengri's registry default is 13.47 Gyr at z=0)",
            "The workshop catalog does not record the FSPS isochrone and spectral library versions used by Dense Basis",
        ],
        "notes_sources": [
            "src/tengri/components/stellar/sfh/registry.py:2007",
            "art_sedfitting/code_outputs/header (absence of the setting)",
        ],
    },
}
