"""Fit the panchromatic joint mock and report recovery against known truth.

The mock is generated by :mod:`paper1.fig_mock_joint_infer` from the listing in
:mod:`paper1.verify_mock_listing`, so the model fitted here is the model printed
in the paper, not a retyped copy of it.

Two things here are easy to get wrong and are done deliberately.

**A non-detection enters as its limit, not as its noisy flux.** The generator
saves the realized flux for every band including the faint ones, because that is
what it drew. A catalog does not report that number; it reports an upper limit.
Feeding the noisy flux with a small error bar would hand the fit a precise
measurement of something nobody measured, and at the long-wavelength end -- where
the only bands are millimetre and the source is genuinely faint -- that single
choice decides whether the dust mass is constrained or invented. The censored
likelihood (``ln Phi((f_limit - m)/sigma)``) is what a limit actually means.

**Recovery is reported per parameter, against truth, in the parameter's own
units.** A summary statistic over 43 parameters hides exactly the failure this
fit exists to catch: on the UV-through-MIR filter set every parameter looked
recovered except ``xray_log_nh``, which was 2.04 dex out because no band
constrained it. An aggregate would have called that a good fit.

Usage::

    python -m paper1.fit_mock_joint                    # MAP, the fast check
    python -m paper1.fit_mock_joint --method mcmc_nuts --n-samples 300
"""

from __future__ import annotations

import argparse
import time

import jax
import numpy as np

import tengri
from tengri import Data, ForwardModel

from .fig_mock_joint_infer import DETECTION_SIGMA, RESULTS, TRUTH_NPZ
from .verify_mock_listing import MOCK_FILTERS, build_joint_observation, build_mock_model

jax.config.update("jax_enable_x64", True)

SSP_GRID = "fsps_mist_c3k_a_chabrier"

#: Censoring vocabulary from ``tengri.observation.noise``. Restated as names
#: rather than 0/1 literals because a bare ``1`` in a mask array is unreadable,
#: and a boolean array is rejected by ``Data`` precisely because it inverts.
DETECTED = 0
UPPER_LIMIT = 1


def observed_photometry(truth_npz):
    """Catalog-style photometry: fluxes where detected, limits where not.

    Returns ``(flux, sigma, censor)``. For a censored band the flux slot holds
    the ``DETECTION_SIGMA``-sigma limit, which is what the censored likelihood
    reads as ``f_upper``.
    """
    flux = np.array(truth_npz["phot_obs"], dtype=float)
    sigma = np.array(truth_npz["phot_sig"], dtype=float)
    depth = np.array(truth_npz["phot_depth"], dtype=float)
    detected = np.array(truth_npz["detected"], dtype=bool)

    censor = np.where(detected, DETECTED, UPPER_LIMIT).astype(np.int32)
    flux = np.where(detected, flux, DETECTION_SIGMA * depth)
    return flux, sigma, censor


def report(free, truth, fitted, wall, n_censored):
    """Per-parameter recovery table, worst offender last so it is visible."""
    delta = {k: float(fitted[k]) - float(truth[k]) for k in free}
    order = sorted(free, key=lambda k: abs(delta[k]))

    print(f"\nwall {wall:.1f} s, D = {len(free)}, {n_censored} censored band(s)\n")
    print(f"{'parameter':<34}{'truth':>12}{'fitted':>12}{'delta':>12}")
    print("-" * 70)
    for k in order:
        print(f"{k:<34}{float(truth[k]):12.4f}{float(fitted[k]):12.4f}{delta[k]:12.4f}")

    worst = order[-1]
    print(f"\nlargest |delta|: {worst} = {delta[worst]:+.4f}")
    if "xray_log_nh" in delta:
        print(f"xray_log_nh delta {delta['xray_log_nh']:+.4f} dex (was +2.04 with no X-ray band)")
    return delta


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--method", default="map")
    parser.add_argument("--n-warmup", type=int, default=300)
    parser.add_argument("--n-samples", type=int, default=300)
    parser.add_argument("--n-chains", type=int, default=4)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)

    if not TRUTH_NPZ.exists():
        raise FileNotFoundError(
            f"{TRUTH_NPZ} is missing. Generate it first:\n"
            f"    python -m paper1.fig_mock_joint_infer"
        )
    npz = np.load(TRUTH_NPZ, allow_pickle=True)

    free = [str(x) for x in npz["free_params"]]
    truth = dict(zip(free, [float(v) for v in npz["truth_values"]], strict=True))

    saved = [str(x) for x in npz["filters"]]
    if saved != list(MOCK_FILTERS):
        raise ValueError(
            f"the saved mock was generated with a different filter set:\n"
            f"  saved:   {saved}\n"
            f"  current: {list(MOCK_FILTERS)}\n"
            f"Regenerate it: python -m paper1.fig_mock_joint_infer"
        )

    flux, sigma, censor = observed_photometry(npz)
    spec_obs = np.array(npz["spec_obs"])
    spec_sig = np.array(npz["spec_sig"])

    # ``censor`` is per photometric band, which is the documented contract and
    # the only length ``Data.validate_against`` accepts. Extending it to the
    # concatenated joint vector is the framework's job, at the same place it
    # concatenates the fluxes -- that extension was missing until #2432, and a
    # joint fit with any censored band could not run at all.
    data = Data(
        photometry=(flux, sigma),
        spectrum=(spec_obs, spec_sig),
        censor=censor,
    )

    ssp = tengri.load_ssp(SSP_GRID)
    model = build_mock_model(ssp, build_joint_observation())

    kwargs = {}
    if args.method.startswith("mcmc"):
        kwargs = {
            "n_warmup": args.n_warmup,
            "n_samples": args.n_samples,
            "n_chains": args.n_chains,
        }

    # Inference is canonically through ForwardModel, not the SEDModel directly.
    forward = ForwardModel.build(sed=model)

    t0 = time.perf_counter()
    post = forward.fit(data, method=args.method, key=jax.random.PRNGKey(args.seed), **kwargs)
    wall = time.perf_counter() - t0

    fitted = (
        post.params
        if args.method == "map"
        else {k: float(np.median(np.asarray(post.samples[k]))) for k in free}
    )
    delta = report(free, truth, fitted, wall, int((censor == UPPER_LIMIT).sum()))

    RESULTS.mkdir(exist_ok=True)
    out = RESULTS / f"mock_joint_{args.method}.npz"
    np.savez(
        out,
        free_params=np.array(free, dtype=object),
        truth_values=np.array([truth[k] for k in free]),
        fitted_values=np.array([float(fitted[k]) for k in free]),
        delta=np.array([delta[k] for k in free]),
        wall_seconds=wall,
        method=args.method,
    )
    print(f"\nsaved {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
