"""Fit the panchromatic joint mock and report recovery against known truth.

The mock is generated by :mod:`paper1.fig_mock_joint_infer` from the listing in
:mod:`paper1.verify_mock_listing`, so the model fitted here is the model printed
in the paper, not a retyped copy of it.

Two things here are easy to get wrong and are done deliberately.

**A non-detection enters as its limit, not as its noisy flux.** The generator
saves the realized flux for every band including the faint ones, because that is
what it drew. A catalog does not report that number; it reports an upper limit.
Feeding the noisy flux with a small error bar would hand the fit a precise
measurement of something nobody measured, and at the long-wavelength end -- where
the only bands are millimeter and the source is genuinely faint -- that single
choice decides whether the dust mass is constrained or invented. The censored
likelihood (``ln Phi((f_limit - m)/sigma)``) is what a limit actually means.

**Recovery is reported per parameter, against truth, in the parameter's own
units.** A summary statistic over 43 parameters hides exactly the failure this
fit exists to catch: on the UV-through-MIR filter set every parameter looked
recovered except ``xray_log_nh``, which was 2.04 dex out because no band
constrained it. An aggregate would have called that a good fit.

Usage::

    python -m paper1.fit_mock_joint                    # MAP, the fast check
    python -m paper1.fit_mock_joint --method mcmc_nuts --n-samples 300
"""

from __future__ import annotations

import argparse
import time

import jax
import numpy as np

import tengri
from tengri import Data, ForwardModel

from .fig_mock_joint_infer import DETECTION_SIGMA, RESULTS, TRUTH_NPZ
from .verify_mock_listing import MOCK_FILTERS, build_joint_observation, build_mock_model

jax.config.update("jax_enable_x64", True)

SSP_GRID = "fsps_mist_c3k_a_chabrier"

#: Censoring vocabulary from ``tengri.observation.noise``. Restated as names
#: rather than 0/1 literals because a bare ``1`` in a mask array is unreadable,
#: and a boolean array is rejected by ``Data`` precisely because it inverts.
DETECTED = 0
UPPER_LIMIT = 1


def observed_photometry(truth_npz):
    """Catalog-style photometry: fluxes where detected, limits where not.

    Returns ``(flux, sigma, censor)``. For a censored band the flux slot holds
    the ``DETECTION_SIGMA``-sigma limit, which is what the censored likelihood
    reads as ``f_upper``.
    """
    flux = np.array(truth_npz["phot_obs"], dtype=float)
    sigma = np.array(truth_npz["phot_sig"], dtype=float)
    depth = np.array(truth_npz["phot_depth"], dtype=float)
    detected = np.array(truth_npz["detected"], dtype=bool)

    censor = np.where(detected, DETECTED, UPPER_LIMIT).astype(np.int32)
    flux = np.where(detected, flux, DETECTION_SIGMA * depth)
    return flux, sigma, censor


def chi2_against_data(model, params, npz):
    """Reduced chi2 of a parameter point, over detected bands and the spectrum.

    The recovery table cannot see non-convergence. It prints deltas against
    truth, and a stuck optimizer produces deltas that read as "partially
    recovered" -- indistinguishable from an honestly wide posterior. Chi2 is
    the independent check: the truth point of a correctly specified mock sits
    at chi2/dof ~ 1, and a converged fit lands at or below it, because the
    best-fit point chases the noise realization by construction.

    A fit whose chi2 is ABOVE truth's never reached the basin it was aimed at.
    That is exactly what a single-start L-BFGS did at D=44 here: chi2/dof 1.69
    against truth's 1.08, with photometric chi2 602 where truth gives 24.
    """
    detected = np.array(npz["detected"], dtype=bool)
    phot_obs = np.array(npz["phot_obs"])
    phot_sig = np.array(npz["phot_sig"])
    spec_obs = np.array(npz["spec_obs"])
    spec_sig = np.array(npz["spec_sig"])

    phot = np.asarray(model.predict_photometry(params))
    spec = np.asarray(model.predict(params).spectrum())
    c = float(np.sum(((phot_obs[detected] - phot[detected]) / phot_sig[detected]) ** 2))
    c += float(np.sum(((spec_obs - spec) / spec_sig) ** 2))
    n_data = int(detected.sum()) + spec_obs.size
    return c, c / (n_data - len(npz["free_params"]))


def report(free, truth, fitted, wall, n_censored):
    """Per-parameter recovery table, worst offender last so it is visible."""
    delta = {k: float(fitted[k]) - float(truth[k]) for k in free}
    order = sorted(free, key=lambda k: abs(delta[k]))

    print(f"\nwall {wall:.1f} s, D = {len(free)}, {n_censored} censored band(s)\n")
    print(f"{'parameter':<34}{'truth':>12}{'fitted':>12}{'delta':>12}")
    print("-" * 70)
    for k in order:
        print(f"{k:<34}{float(truth[k]):12.4f}{float(fitted[k]):12.4f}{delta[k]:12.4f}")

    worst = order[-1]
    print(f"\nlargest |delta|: {worst} = {delta[worst]:+.4f}")
    if "xray_log_nh" in delta:
        print(f"xray_log_nh delta {delta['xray_log_nh']:+.4f} dex (was +2.04 with no X-ray band)")
    return delta


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--method", default="map")
    parser.add_argument("--n-warmup", type=int, default=300)
    parser.add_argument("--n-samples", type=int, default=300)
    parser.add_argument("--n-chains", type=int, default=4)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--n-starts",
        type=int,
        default=4,
        help="MAP restarts from independent initializations (default: 4). One "
        "start is not enough at this dimension: a single L-BFGS reached "
        "chi2/dof 1.69 against truth's 1.08. Ignored for samplers.",
    )
    args = parser.parse_args(argv)

    if not TRUTH_NPZ.exists():
        raise FileNotFoundError(
            f"{TRUTH_NPZ} is missing. Generate it first:\n"
            f"    python -m paper1.fig_mock_joint_infer"
        )
    npz = np.load(TRUTH_NPZ, allow_pickle=True)

    free = [str(x) for x in npz["free_params"]]
    truth = dict(zip(free, [float(v) for v in npz["truth_values"]], strict=True))

    saved = [str(x) for x in npz["filters"]]
    if saved != list(MOCK_FILTERS):
        raise ValueError(
            f"the saved mock was generated with a different filter set:\n"
            f"  saved:   {saved}\n"
            f"  current: {list(MOCK_FILTERS)}\n"
            f"Regenerate it: python -m paper1.fig_mock_joint_infer"
        )

    flux, sigma, censor = observed_photometry(npz)
    spec_obs = np.array(npz["spec_obs"])
    spec_sig = np.array(npz["spec_sig"])

    # ``censor`` is per photometric band, which is the documented contract and
    # the only length ``Data.validate_against`` accepts. Extending it to the
    # concatenated joint vector is the framework's job, at the same place it
    # concatenates the fluxes -- that extension was missing until #2432, and a
    # joint fit with any censored band could not run at all.
    data = Data(
        photometry=(flux, sigma),
        spectrum=(spec_obs, spec_sig),
        censor=censor,
    )

    ssp = tengri.load_ssp(SSP_GRID)
    model = build_mock_model(ssp, build_joint_observation())

    kwargs = {}
    if args.method.startswith("mcmc"):
        kwargs = {
            "n_warmup": args.n_warmup,
            "n_samples": args.n_samples,
            "n_chains": args.n_chains,
            # Diagonal, stated rather than left to the auto-policy. At D=44 the
            # warmup memory is dominated by the mass matrix and a dense one is
            # O(D^2) -- measured at 20+ GB on problems this size, which OOMs
            # rather than slows down. A diagonal metric also produced FEWER
            # divergences than dense on a continuity SFH at D=9 (12 vs 2), so
            # this is not a memory concession that costs sampling quality.
            "dense_mass_matrix": False,
        }

    # Inference is canonically through ForwardModel, not the SEDModel directly.
    forward = ForwardModel.build(sed=model)

    t0 = time.perf_counter()
    if args.method == "map":
        # Restart from independent initializations and keep the best by chi2.
        # Selecting by agreement with truth would be circular -- it would tune
        # the answer to the thing being measured -- so the criterion is the fit
        # to the data, which a real analysis also has.
        best, best_c, chis = None, np.inf, []
        for i in range(args.n_starts):
            key = jax.random.PRNGKey(args.seed + 1000 * i)
            cand = forward.fit(data, method="map", key=key).params
            c, _ = chi2_against_data(model, cand, npz)
            chis.append(c)
            if c < best_c:
                best, best_c = cand, c
        fitted = best
        if args.n_starts > 1:
            # The spread across starts is a measurement of the landscape, not
            # noise to be hidden: it says how badly one start can mislead.
            print(
                f"{args.n_starts} starts: chi2 min {min(chis):.1f}, "
                f"median {float(np.median(chis)):.1f}, max {max(chis):.1f}"
            )
    else:
        post = forward.fit(data, method=args.method, key=jax.random.PRNGKey(args.seed), **kwargs)
        fitted = {k: float(np.median(np.asarray(post.samples[k]))) for k in free}
    wall = time.perf_counter() - t0
    delta = report(free, truth, fitted, wall, int((censor == UPPER_LIMIT).sum()))

    # Convergence check, independent of the recovery table above.
    c_truth, r_truth = chi2_against_data(model, truth, npz)
    c_fit, r_fit = chi2_against_data(model, fitted, npz)
    print(f"\nchi2/dof  truth {r_truth:.4f}   fitted {r_fit:.4f}")
    if c_fit > c_truth:
        print(
            f"NOT CONVERGED: the fit is {c_fit - c_truth:.1f} worse in chi2 than "
            f"truth, so it never reached the basin. The recovery deltas above "
            f"measure the optimizer, not the model."
        )
    else:
        print(f"converged: fits the noise realization {c_truth - c_fit:.1f} better than truth")

    RESULTS.mkdir(exist_ok=True)
    out = RESULTS / f"mock_joint_{args.method}.npz"
    np.savez(
        out,
        free_params=np.array(free, dtype=object),
        truth_values=np.array([truth[k] for k in free]),
        fitted_values=np.array([float(fitted[k]) for k in free]),
        delta=np.array([delta[k] for k in free]),
        wall_seconds=wall,
        method=args.method,
    )
    print(f"\nsaved {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
