"""Fit the panchromatic joint mock and report recovery against known truth.

The mock is generated by :mod:`paper1.fig_mock_joint_infer` from the listing in
:mod:`paper1.verify_mock_listing`, so the model fitted here is the model printed
in the paper, not a retyped copy of it.

Two things here are easy to get wrong and are done deliberately.

**A non-detection enters as its limit, not as its noisy flux.** The generator
saves the realized flux for every band including the faint ones, because that is
what it drew. A catalog does not report that number; it reports an upper limit.
Feeding the noisy flux with a small error bar would hand the fit a precise
measurement of something nobody measured, and at the long-wavelength end -- where
the only bands are millimeter and the source is genuinely faint -- that single
choice decides whether the dust mass is constrained or invented. The censored
likelihood (``ln Phi((f_limit - m)/sigma)``) is what a limit actually means.

**Recovery is reported per parameter, against truth, in the parameter's own
units.** A summary statistic over 43 parameters hides exactly the failure this
fit exists to catch: on the UV-through-MIR filter set every parameter looked
recovered except ``xray_log_nh``, which was 2.04 dex out because no band
constrained it. An aggregate would have called that a good fit.

Usage::

    python -m paper1.fit_mock_joint                    # MAP, the fast check
    python -m paper1.fit_mock_joint --method mcmc_nuts --n-samples 300
"""

from __future__ import annotations

import argparse
import json
import sys
import time

import jax
import numpy as np

import tengri
from tengri import Data, ForwardModel

from ._posterior_utils import (
    build_npz_payload,
    divergent_draw_payload,
    posterior_output_paths,
    thin_samples,
)
from ._provenance import code_provenance, provenance_line
from .fig_mock_joint_infer import DETECTION_SIGMA, RESULTS, TRUTH_NPZ
from .verify_mock_listing import MOCK_FILTERS, build_joint_observation, build_mock_model

jax.config.update("jax_enable_x64", True)

SSP_GRID = "fsps_mist_c3k_a_chabrier"

#: Censoring vocabulary from ``tengri.observation.noise``. Restated as names
#: rather than 0/1 literals because a bare ``1`` in a mask array is unreadable,
#: and a boolean array is rejected by ``Data`` precisely because it inverts.
DETECTED = 0
UPPER_LIMIT = 1

#: Draw cap for the mock's saved posterior, deliberately NOT ``fit_one``'s
#: ``MAX_SAVED_DRAWS`` (4000) and deliberately not named the same thing. The
#: grid caps because 120 cells x 4000 draws x D is a lot of disk; this is one
#: fit, and its draws are the source for the paper's joint-inference figure,
#: whose posterior predictive band and corner want every draw the sampler
#: kept. At the recipe's 4 chains x 300 samples = 1200 draws this cap does not
#: bind at all, which is the intent: thinning here would discard figure
#: resolution to save megabytes.
MOCK_MAX_SAVED_DRAWS = 10000


def observed_photometry(truth_npz):
    """Catalog-style photometry: fluxes where detected, limits where not.

    Returns ``(flux, sigma, censor)``. For a censored band the flux slot holds
    the ``DETECTION_SIGMA``-sigma limit, which is what the censored likelihood
    reads as ``f_upper``.
    """
    flux = np.array(truth_npz["phot_obs"], dtype=float)
    sigma = np.array(truth_npz["phot_sig"], dtype=float)
    depth = np.array(truth_npz["phot_depth"], dtype=float)
    detected = np.array(truth_npz["detected"], dtype=bool)

    censor = np.where(detected, DETECTED, UPPER_LIMIT).astype(np.int32)
    flux = np.where(detected, flux, DETECTION_SIGMA * depth)
    return flux, sigma, censor


def chi2_against_data(model, params, npz):
    """Reduced chi2 of a parameter point, over detected bands and the spectrum.

    The recovery table cannot see non-convergence. It prints deltas against
    truth, and a stuck optimizer produces deltas that read as "partially
    recovered" -- indistinguishable from an honestly wide posterior. Chi2 is
    the independent check: the truth point of a correctly specified mock sits
    at chi2/dof ~ 1, and a converged fit lands at or below it, because the
    best-fit point chases the noise realization by construction.

    A fit whose chi2 is ABOVE truth's never reached the basin it was aimed at.
    That is exactly what a single-start L-BFGS did at D=44 here: chi2/dof 1.69
    against truth's 1.08, with photometric chi2 602 where truth gives 24.
    """
    detected = np.array(npz["detected"], dtype=bool)
    phot_obs = np.array(npz["phot_obs"])
    phot_sig = np.array(npz["phot_sig"])
    spec_obs = np.array(npz["spec_obs"])
    spec_sig = np.array(npz["spec_sig"])

    phot = np.asarray(model.predict_photometry(params))
    spec = np.asarray(model.predict(params).spectrum())
    c = float(np.sum(((phot_obs[detected] - phot[detected]) / phot_sig[detected]) ** 2))
    c += float(np.sum(((spec_obs - spec) / spec_sig) ** 2))
    n_data = int(detected.sum()) + spec_obs.size
    return c, c / (n_data - len(npz["free_params"]))


def report(free, truth, fitted, wall, n_censored):
    """Per-parameter recovery table, worst offender last so it is visible."""
    delta = {k: float(fitted[k]) - float(truth[k]) for k in free}
    order = sorted(free, key=lambda k: abs(delta[k]))

    print(f"\nwall {wall:.1f} s, D = {len(free)}, {n_censored} censored band(s)\n")
    print(f"{'parameter':<34}{'truth':>12}{'fitted':>12}{'delta':>12}")
    print("-" * 70)
    for k in order:
        print(f"{k:<34}{float(truth[k]):12.4f}{float(fitted[k]):12.4f}{delta[k]:12.4f}")

    worst = order[-1]
    print(f"\nlargest |delta|: {worst} = {delta[worst]:+.4f}")
    if "xray_log_nh" in delta:
        print(f"xray_log_nh delta {delta['xray_log_nh']:+.4f} dex (was +2.04 with no X-ray band)")
    return delta


# Progress goes to a log through a redirect, and Python line-buffers stdout
# only to a terminal. Warnings reach stderr unbuffered while every print here
# sat in a buffer until exit, so an 8h41m run showed nothing but warnings for
# its whole life and the warm-start readout below -- the one line that says
# whether --init-from-map engaged -- would not have appeared until it no
# longer mattered. A long run that cannot be watched is a long run that has to
# be rerun to answer a question its log should already hold.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--method", default="map")
    parser.add_argument("--n-warmup", type=int, default=300)
    parser.add_argument("--n-samples", type=int, default=300)
    parser.add_argument("--n-chains", type=int, default=4)
    parser.add_argument(
        "--target-accept",
        type=float,
        default=0.85,
        help=(
            "NUTS target acceptance rate; run_nuts's own default is 0.85. "
            "Higher shortens the step and suppresses divergences at the cost "
            "of wall clock."
        ),
    )
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--init-from-map",
        type=int,
        default=0,
        metavar="N",
        help=(
            "run N multi-start MAP fits first and start the sampler from the best "
            "of them; 0 (default) keeps the cold start"
        ),
    )
    parser.add_argument(
        "--n-starts",
        type=int,
        default=1,
        help="MAP restarts, passed to the backend's n_restarts (default: 1). "
        "One L-BFGS start reaches chi2/dof 1.0487 against truth's 1.0738; an "
        "eight-start run reached 1.0474 for eight times the wall clock. "
        "Ignored for samplers.",
    )
    args = parser.parse_args(argv)

    if not TRUTH_NPZ.exists():
        raise FileNotFoundError(
            f"{TRUTH_NPZ} is missing. Generate it first:\n"
            f"    python -m paper1.fig_mock_joint_infer"
        )
    npz = np.load(TRUTH_NPZ, allow_pickle=True)

    free = [str(x) for x in npz["free_params"]]
    truth = dict(zip(free, [float(v) for v in npz["truth_values"]], strict=True))

    saved = [str(x) for x in npz["filters"]]
    if saved != list(MOCK_FILTERS):
        raise ValueError(
            f"the saved mock was generated with a different filter set:\n"
            f"  saved:   {saved}\n"
            f"  current: {list(MOCK_FILTERS)}\n"
            f"Regenerate it: python -m paper1.fig_mock_joint_infer"
        )

    flux, sigma, censor = observed_photometry(npz)
    spec_obs = np.array(npz["spec_obs"])
    spec_sig = np.array(npz["spec_sig"])

    # ``censor`` is per photometric band, which is the documented contract and
    # the only length ``Data.validate_against`` accepts. Extending it to the
    # concatenated joint vector is the framework's job, at the same place it
    # concatenates the fluxes -- that extension was missing until #2432, and a
    # joint fit with any censored band could not run at all.
    data = Data(
        photometry=(flux, sigma),
        spectrum=(spec_obs, spec_sig),
        censor=censor,
    )

    ssp = tengri.load_ssp(SSP_GRID)
    model = build_mock_model(ssp, build_joint_observation())

    kwargs = {}
    if args.method.startswith("mcmc"):
        kwargs = {
            "n_warmup": args.n_warmup,
            "n_samples": args.n_samples,
            "n_chains": args.n_chains,
            # Diagonal, stated rather than left to the auto-policy. At D=44 the
            # warmup memory is dominated by the mass matrix and a dense one is
            # O(D^2) -- measured at 20+ GB on problems this size, which OOMs
            # rather than slows down. A diagonal metric also produced FEWER
            # divergences than dense on a continuity SFH at D=9 (12 vs 2), so
            # this is not a memory concession that costs sampling quality.
            "dense_mass_matrix": False,
            # Step size, the remaining lever on divergences once the start is
            # excluded. run_nuts has taken this all along at 0.85; raising it
            # shortens the step, which is the standard remedy and costs wall
            # clock. Exposed because the 11 h run at the default warm-started
            # INSIDE the basin, at chi2/dof 1.0480 against truth's 1.0738, and
            # still ended at 1.3075 with 79 divergences against the cold run's
            # 19 -- more divergences from a better start, so initialization is
            # not the cause and geometry is what is left.
            "target_accept_rate": args.target_accept,
        }

    # Inference is canonically through ForwardModel, not the SEDModel directly.
    forward = ForwardModel.build(sed=model)

    t0 = time.perf_counter()

    def map_fit(n_restarts: int):
        """MAP by L-BFGS, through the public fit surface.

        Returns (posterior, params, chi2). The posterior is kept, not just its
        params: `init_from` is handed to `_unbounded_from_posterior` and needs
        the object.

        ``n_restarts`` is the MAP backend's own parameter. This script used to
        run its own loop of independent ``forward.fit`` calls and keep the one
        with the lowest chi2, which reimplements a documented feature, pays a
        fresh setup per start, and selects on a different quantity than the
        optimizer minimizes. The backend selects by that objective, which is
        the principled criterion -- selecting by agreement with truth would be
        circular, and chi2 against the data is one step removed from what is
        being optimized.

        One start is enough: L-BFGS reaches chi2/dof 1.0487 against truth's
        1.0738 here, indistinguishable from the 1.0474 an eight-start run
        reached for eight times the wall clock.
        """
        post = forward.fit(
            data,
            method="map",
            key=jax.random.PRNGKey(args.seed),
            optimizer="lbfgs",
            n_restarts=n_restarts,
        )
        c, _ = chi2_against_data(model, post.params, npz)
        return post, post.params, c

    post = None
    if args.method == "map":
        _, fitted, _ = map_fit(args.n_starts)
    else:
        init_post = None
        if args.init_from_map:
            # NUTS at this dimensionality does not find the basin from a cold
            # start: an 8h41m run at 1000 warmup reached chi2/dof 1.50 against
            # truth's 1.07, while multi-start MAP reaches 1.05 in seven
            # minutes. Drawing more samples from the wrong region does not fix
            # that, so start the chain where the optimizer already got to.
            # This is the idiom Fitter's own docstring shows.
            init_post, init_params, init_c = map_fit(args.init_from_map)
            _, init_r = chi2_against_data(model, init_params, npz)
            print(f"warm start from MAP: chi2/dof {init_r:.4f} (chi2 {init_c:.1f})")

        post = forward.fit(
            data,
            method=args.method,
            key=jax.random.PRNGKey(args.seed),
            **({"init_from": init_post} if init_post is not None else {}),
            **kwargs,
        )
        fitted = {k: float(np.median(np.asarray(post.samples[k]))) for k in free}
    wall = time.perf_counter() - t0
    delta = report(free, truth, fitted, wall, int((censor == UPPER_LIMIT).sum()))

    # Convergence check, independent of the recovery table above.
    c_truth, r_truth = chi2_against_data(model, truth, npz)
    c_fit, r_fit = chi2_against_data(model, fitted, npz)
    print(f"\nchi2/dof  truth {r_truth:.4f}   fitted {r_fit:.4f}")
    if c_fit > c_truth:
        print(
            f"NOT CONVERGED: the fit is {c_fit - c_truth:.1f} worse in chi2 than "
            f"truth, so it never reached the basin. The recovery deltas above "
            f"measure the optimizer, not the model."
        )
    else:
        print(f"converged: fits the noise realization {c_truth - c_fit:.1f} better than truth")

    RESULTS.mkdir(exist_ok=True)
    out, out_json = posterior_output_paths(RESULTS, args.method)

    if args.method == "map":
        # MAP: simple point estimate, no posterior draws
        np.savez(
            out,
            free_params=np.array(free, dtype=object),
            truth_values=np.array([truth[k] for k in free]),
            fitted_values=np.array([float(fitted[k]) for k in free]),
            delta=np.array([delta[k] for k in free]),
            wall_seconds=wall,
            method=args.method,
        )
        print(f"\nsaved {out}")
    else:
        # Sampler methods: save posterior draws and diagnostics
        assert post is not None, "posterior should be available for sampler methods"
        _save_sampler_results(
            post,
            out,
            out_json,
            free,
            truth,
            fitted,
            delta,
            wall,
            args.method,
            kwargs,
        )
        print(f"\nsaved {out}")
        print(f"saved {out_json}")

    return 0


def _save_sampler_results(
    posterior,
    out_npz,
    out_json,
    free,
    truth,
    fitted,
    delta,
    wall,
    method,
    sampler_kwargs,
) -> None:
    """Save sampler results: posterior draws, diagnostics to NPZ and JSON sidecar.

    Persists the full posterior for Monte Carlo methods to enable posterior-predictive
    and corner plots in the paper figures. Also writes a JSON sidecar with diagnostic
    summaries (divergences, R-hat, ESS) for quick readability.

    Args:
        posterior: Posterior object from the inference backend.
        out_npz: Path to write the NPZ file.
        out_json: Path to write the JSON diagnostic sidecar.
        free: List of free parameter names.
        truth: Dict of truth values indexed by parameter name.
        fitted: Dict of fitted (median) values indexed by parameter name.
        delta: Dict of differences (fitted - truth) indexed by parameter name.
        wall: Wall time in seconds.
        method: Inference method name.
        sampler_kwargs: Dict of sampler keyword arguments (n_warmup, n_samples,
            n_chains, dense_mass_matrix).
    """
    samples_thin = thin_samples(posterior.samples, max_draws=MOCK_MAX_SAVED_DRAWS)

    # Extract diagnostics from posterior
    diagnostics = posterior.diagnostics or {}

    # Build per-parameter diagnostics
    # posterior.rhat(), singular. The previous spelling was rhats() behind a
    # hasattr guard, and since no such method exists the guard fired every time
    # and every mock fit silently reported no R-hat at all. Call it directly:
    # if the method ever goes away that should raise, not quietly disarm the
    # only between-chain diagnostic the run produces.
    rhat_dict = posterior.rhat()
    rhat_max = max((float(v) for v in rhat_dict.values()), default=None)

    ess_dict = (
        posterior.effective_sample_size() if hasattr(posterior, "effective_sample_size") else {}
    )
    ess_min = min((float(v) for v in ess_dict.values()), default=None) if ess_dict else None

    n_divergent = diagnostics.get("n_divergent", 0)
    divergent_mask = diagnostics.get("divergent_mask")

    # Check which energy/ebfmi attributes are available
    energy = diagnostics.get("energy")
    ebfmi_per_chain = diagnostics.get("ebfmi_per_chain")
    ebfmi_min = diagnostics.get("ebfmi_min")

    # Build NPZ payload: thinned samples + diagnostics
    energy_payload = {}
    if energy is not None:
        energy_payload["energy"] = np.asarray(energy)

    npz_payload = build_npz_payload(
        samples_thin,
        energy_payload,
        divergent_draw_payload(posterior),
    )

    # Add per-parameter diagnostics as separate keys
    if rhat_dict:
        for k, v in rhat_dict.items():
            npz_payload[f"rhat_{k}"] = float(v)
    if rhat_max is not None:
        npz_payload["rhat_max"] = float(rhat_max)

    if ess_dict:
        for k, v in ess_dict.items():
            npz_payload[f"ess_{k}"] = float(v)
    if ess_min is not None:
        npz_payload["ess_min"] = float(ess_min)

    # Add sampler metadata
    npz_payload["truth_values"] = np.array([truth[k] for k in free])
    npz_payload["fitted_values"] = np.array([float(fitted[k]) for k in free])
    npz_payload["delta"] = np.array([delta[k] for k in free])
    npz_payload["free_params"] = np.array(free, dtype=object)
    npz_payload["method"] = method
    npz_payload["wall_seconds"] = wall
    npz_payload["n_chains"] = sampler_kwargs.get("n_chains")
    npz_payload["n_warmup"] = sampler_kwargs.get("n_warmup")
    npz_payload["n_samples"] = sampler_kwargs.get("n_samples")
    npz_payload["divergences_count"] = int(n_divergent)

    # Sentinel keys for unavailable energy/ebfmi
    if energy is None:
        npz_payload["_energy_unavailable"] = True
    if ebfmi_per_chain is None:
        npz_payload["_ebfmi_per_chain_unavailable"] = True
    if ebfmi_min is None:
        npz_payload["_ebfmi_min_unavailable"] = True

    np.savez(out_npz, **npz_payload)

    # Write JSON sidecar with diagnostic summary
    json_payload = {
        "divergences": int(n_divergent),
        "rhat": rhat_dict,
        "rhat_max": float(rhat_max) if rhat_max is not None else None,
        "ess": ess_dict,
        "ess_min": float(ess_min) if ess_min is not None else None,
        "wall_seconds": wall,
        "n_chains": sampler_kwargs.get("n_chains"),
        "n_warmup": sampler_kwargs.get("n_warmup"),
        "n_samples": sampler_kwargs.get("n_samples"),
        "target_accept_rate": sampler_kwargs.get("target_accept_rate"),
        "dense_mass_matrix": sampler_kwargs.get("dense_mass_matrix"),
        "method": method,
        # Which tree produced these numbers. Section 3 quotes them and the
        # paper is pinned, so a diagnostic without a commit is a diagnostic
        # nobody can check; read off the imported module rather than the
        # working directory, because on this machine a bare `python` resolves
        # `import tengri` to an unrelated checkout.
        "provenance": code_provenance(tengri),
    }

    # Add energy/ebfmi to JSON if available
    if ebfmi_per_chain is not None:
        json_payload["ebfmi_per_chain"] = [float(v) for v in ebfmi_per_chain]
    else:
        json_payload["ebfmi_per_chain"] = None

    if ebfmi_min is not None:
        json_payload["ebfmi_min"] = float(ebfmi_min)
    else:
        json_payload["ebfmi_min"] = None

    print(provenance_line(json_payload["provenance"]))

    with open(out_json, "w") as f:
        json.dump(json_payload, f, indent=2)


if __name__ == "__main__":
    raise SystemExit(main())
