# SPDX-License-Identifier: BSD-3-Clause
# Tests for the per-wavelength SSP library resolution curve wired onto the
# default Gaussian LSF path (#2518): apply_lsf's effective kernel must equal
# FSPS's own per-node library resolution, not a flat scalar, and a sigma_v
# fit must actually recover the injected velocity dispersion once it does.
#
# Expected values are FSPS's own tables (SPECTRA/MILES/miles.res,
# SPECTRA/C3K/c3k_afe+0.0.res; see
# src/tengri/data/ssp_library_resolution/PROVENANCE.md), reproduced here as
# literals so this file does not depend on an FSPS checkout being present.

import os
import warnings

import numpy as np
import pytest
from jax import numpy as jnp
from scipy.optimize import minimize_scalar

from tengri.components.stellar.sps.dsps_wrapper import (
    _resolve_ssp_resolution,
    load_ssp_data,
)
from tengri.observation.spectrum import SSP_LIBRARY_RESOLUTIONS, apply_lsf

pytestmark = pytest.mark.regression_paper

_C_KMS = 299792.458
_FWHM_TO_SIGMA_KMS = _C_KMS / (2.0 * np.sqrt(2.0 * np.log(2.0)))

# FSPS SPECTRA/MILES/miles.res, read at these SPECTRA/MILES/miles.lambda
# nodes (nearest node to each target wavelength; full source precision).
_MILES_FSPS_NODES = [
    (3530.00, 91.6009),
    (3601.83, 89.7742),
    (3999.73, 80.8432),
    (4999.89, 64.6716),
    (6000.06, 53.8913),
    (7000.23, 46.1915),
    (7490.00, 43.1711),
]

# FSPS SPECTRA/C3K/c3k_afe+0.0.res: constant sigma within each R = lambda/FWHM
# regime (SPECTRA/C3K/readme.md), read safely inside each regime (away from
# the R=3000-to-R=500 step at ~9100 A, which FSPS's table does not sign-flag
# and so is not a snap-to-nearest boundary for _resolve_ssp_resolution --
# see its docstring).
_C3K_FSPS_REGIME_NODES = [
    (2800.00, 42.4345),  # R=3000 core, near the blue edge
    (5000.00, 42.4345),  # R=3000 core, mid
    (9000.00, 42.4345),  # R=3000 core, near the red edge
    (1500.00, 254.6072),  # R=500 wing (1000-2750 A)
    (20000.00, 254.6072),  # R=500 wing (9100-24000 A)
]


def test_miles_matches_fsps_on_tracked_grid():
    """SSPData.ssp_resolution_kms reproduces FSPS's miles.res on the shipped grid.

    The shipped ``fsps_prsc_miles_chabrier.h5`` is generated by FSPS on
    ``miles.lambda`` node for node, so ``load_ssp_data`` should read
    ``miles.res`` back out unchanged.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        ssp = load_ssp_data("data/fsps_prsc_miles_chabrier.h5")
    wave = np.asarray(ssp.ssp_wave)
    sigma = np.asarray(ssp.ssp_resolution_kms)

    for wave_aa, expected_sigma_kms in _MILES_FSPS_NODES:
        idx = int(np.argmin(np.abs(wave - wave_aa)))
        assert wave[idx] == pytest.approx(wave_aa, abs=0.5)
        assert sigma[idx] == pytest.approx(expected_sigma_kms, rel=1e-5)


def test_c3k_matches_fsps_via_synthetic_curve():
    """The curve constructor reproduces FSPS's c3k_afe+0.0.res regime values.

    No C3K grid file is needed: :func:`_resolve_ssp_resolution` is called
    directly on the target wavelengths.
    """
    wave = jnp.array([w for w, _ in _C3K_FSPS_REGIME_NODES])
    sigma, _ = _resolve_ssp_resolution(wave, "c3k_a")
    for (wave_aa, expected_sigma_kms), got in zip(_C3K_FSPS_REGIME_NODES, np.asarray(sigma)):
        assert got == pytest.approx(expected_sigma_kms, rel=1e-5), wave_aa


def test_c3k_matches_fsps_source_files_when_available():
    """Cross-check the full C3K array against a local FSPS checkout, when present.

    Local-only: skips (with reason) when ``$SPS_HOME`` is unset or the
    reference files / shipped grid are absent. CI has no FSPS checkout, so
    this never runs there; it exists for anyone re-deriving the tables in
    ``src/tengri/data/ssp_library_resolution/``.
    """
    sps_home = os.environ.get("SPS_HOME")
    if not sps_home:
        pytest.skip("SPS_HOME not set; no local FSPS checkout to compare against")
    lam_path = os.path.join(sps_home, "SPECTRA", "C3K", "c3k_afe+0.0.lambda")
    res_path = os.path.join(sps_home, "SPECTRA", "C3K", "c3k_afe+0.0.res")
    if not (os.path.isfile(lam_path) and os.path.isfile(res_path)):
        pytest.skip(f"FSPS C3K reference tables not found under {sps_home}")
    grid_path = "data/fsps_prsc_c3k_a_chabrier.h5"
    if not os.path.isfile(grid_path):
        pytest.skip(f"{grid_path} not found")

    ref_wave = np.loadtxt(lam_path)
    ref_sigma_signed = np.loadtxt(res_path)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        ssp = load_ssp_data(grid_path)
    wave = np.asarray(ssp.ssp_wave)
    sigma = np.asarray(ssp.ssp_resolution_kms)

    assert wave.shape == ref_wave.shape
    np.testing.assert_allclose(wave, ref_wave, rtol=1e-5)
    np.testing.assert_allclose(sigma, np.abs(ref_sigma_signed), rtol=1e-5)


@pytest.mark.parametrize("library_key", ["miles", "c3k_a"])
@pytest.mark.parametrize("sigma_inst_kms", [50.0, 150.0])
@pytest.mark.parametrize("sigma_v_kms", [0.0, 100.0, 300.0])
def test_effective_kernel_matches_fsps_curve(library_key, sigma_inst_kms, sigma_v_kms):
    """sigma_eff = sqrt(sigma_v^2 + sigma_inst^2 - sigma_lib(lambda)^2) at FSPS's own nodes.

    Exercised at three representative wavelengths per library (the FSPS
    reference nodes above); ``sigma_lib(lambda)`` comes from
    :func:`_resolve_ssp_resolution`, the function ``load_ssp_data`` calls.
    """
    nodes = _MILES_FSPS_NODES[:1] + _MILES_FSPS_NODES[3:4] + _MILES_FSPS_NODES[6:]
    if library_key == "c3k_a":
        nodes = _C3K_FSPS_REGIME_NODES[:3]

    for wave_aa, expected_sigma_lib in nodes:
        sigma_lib, _ = _resolve_ssp_resolution(jnp.array([wave_aa]), library_key)
        sigma_lib = float(sigma_lib[0])
        assert sigma_lib == pytest.approx(expected_sigma_lib, rel=1e-5)

        expected_kernel = float(
            np.sqrt(max(sigma_inst_kms**2 - expected_sigma_lib**2, 0.0) + sigma_v_kms**2)
        )
        computed_kernel = float(
            np.sqrt(max(sigma_inst_kms**2 - sigma_lib**2, 0.0) + sigma_v_kms**2)
        )
        assert computed_kernel == pytest.approx(expected_kernel, rel=1e-5)


def test_flat_scalar_does_not_reproduce_fsps_curve():
    """SSP_LIBRARY_RESOLUTIONS["miles"] (the flat fallback) misses FSPS's own
    curve away from its crossover wavelength -- the reason #2518 exists."""
    sigma_inst_kms = 150.0
    flat_kms = SSP_LIBRARY_RESOLUTIONS["miles"]
    for wave_aa, true_sigma_lib in (_MILES_FSPS_NODES[0], _MILES_FSPS_NODES[-1]):
        true_kernel = np.sqrt(max(sigma_inst_kms**2 - true_sigma_lib**2, 0.0))
        flat_kernel = np.sqrt(max(sigma_inst_kms**2 - flat_kms**2, 0.0))
        assert flat_kernel != pytest.approx(true_kernel, rel=1e-3), wave_aa


def test_apply_lsf_reproduces_fsps_kernel_width():
    """apply_lsf's actual convolution (not just the closed-form formula) matches
    sigma_eff = sqrt(sigma_v^2 + sigma_inst^2 - sigma_lib(lambda)^2) at MILES
    ~5000 A, sigma_inst=150, sigma_v=100 km/s (#2518).

    Measures the output's velocity-space second moment (a narrow Gaussian
    probe convolves in quadrature: measured^2 = probe^2 + kernel^2) rather
    than reading apply_lsf's internal sigma_eff back at itself.
    """
    n = 8192
    wave = jnp.exp(jnp.linspace(np.log(2000.0), np.log(12000.0), n))
    center = 4999.89
    sigma_probe_kms = 15.0
    lnwave = jnp.log(wave)
    probe = jnp.exp(-0.5 * ((lnwave - jnp.log(center)) / (sigma_probe_kms / _C_KMS)) ** 2)

    sigma_inst_kms = 150.0
    sigma_v_kms = 100.0
    sigma_lib_kms, _ = _resolve_ssp_resolution(jnp.array([center]), "miles")
    sigma_lib_kms = float(sigma_lib_kms[0])
    resolution = _C_KMS / (2.3548200450309493 * sigma_inst_kms)

    out = apply_lsf(
        probe, wave, resolution=resolution, sigma_lib_kms=sigma_lib_kms, sigma_v_kms=sigma_v_kms
    )

    w = np.clip(np.asarray(out), 0.0, None)
    mean_lnwave = np.sum(w * np.asarray(lnwave)) / np.sum(w)
    var_lnwave = np.sum(w * (np.asarray(lnwave) - mean_lnwave) ** 2) / np.sum(w)
    measured_total_kms = float(np.sqrt(var_lnwave) * _C_KMS)

    expected_kernel_kms = np.sqrt(max(sigma_inst_kms**2 - sigma_lib_kms**2, 0.0) + sigma_v_kms**2)
    expected_total_kms = np.sqrt(sigma_probe_kms**2 + expected_kernel_kms**2)

    # 2% tolerance: apply_lsf's variable-sigma_lib path is the piecewise
    # n_bins=16 approximation (documented ~1% accuracy) plus the second-
    # moment measurement's own discretization error.
    assert measured_total_kms == pytest.approx(expected_total_kms, rel=2e-2)


def _absorption_template(wave_aa, line_centers):
    wave_np = np.asarray(wave_aa)
    flux = np.ones_like(wave_np)
    for lc in line_centers:
        flux -= 0.3 * np.exp(-0.5 * ((wave_np - lc) / 3.0) ** 2)
    return jnp.asarray(flux)


def _recover_sigma_v(template, wave, resolution, sigma_lib_assumed, mock):
    def objective(sigma_v):
        pred = apply_lsf(
            template,
            wave,
            resolution=resolution,
            sigma_lib_kms=sigma_lib_assumed,
            sigma_v_kms=sigma_v,
        )
        return float(jnp.sum((pred - mock) ** 2))

    result = minimize_scalar(
        objective, bounds=(0.0, 300.0), method="bounded", options={"xatol": 1e-3}
    )
    return float(result.x)


class TestSigmaVRecovery:
    """A 1-D least-squares sigma_v fit against a curve-broadened mock spectrum
    recovers the true velocity dispersion using FSPS's own curve; the flat
    scalar fallback is biased away from it (#2518)."""

    def test_miles_curve_recovers_true_sigma_v_flat_is_biased(self):
        sigma_inst_kms = 150.0
        sigma_v_true = 100.0
        resolution = _C_KMS / (2.3548200450309493 * sigma_inst_kms)

        wave = jnp.linspace(3600.0, 7300.0, 2000)
        sigma_lib_curve, _ = _resolve_ssp_resolution(wave, "miles")
        line_centers = (3934.0, 3969.0, 4102.0, 4861.0, 5175.0, 5895.0, 6563.0, 6900.0)
        template = _absorption_template(wave, line_centers)

        mock = np.asarray(
            apply_lsf(
                template,
                wave,
                resolution=resolution,
                sigma_lib_kms=sigma_lib_curve,
                sigma_v_kms=sigma_v_true,
            )
        )

        recovered_curve = _recover_sigma_v(template, wave, resolution, sigma_lib_curve, mock)
        recovered_flat = _recover_sigma_v(
            template, wave, resolution, SSP_LIBRARY_RESOLUTIONS["miles"], mock
        )

        assert recovered_curve == pytest.approx(sigma_v_true, abs=2.0)
        # The flat-70 fit cannot reproduce the wavelength-dependent
        # broadening with a single sigma_v and is measurably biased.
        assert abs(recovered_flat - sigma_v_true) > 2.0

    def test_c3k_curve_recovers_true_sigma_v(self):
        """Same recovery test on the C3K curve, using a synthetic spectrum
        (no C3K grid file required)."""
        sigma_inst_kms = 600.0  # coarser than C3K's ~42-255 km/s everywhere tested
        sigma_v_true = 100.0
        resolution = _C_KMS / (2.3548200450309493 * sigma_inst_kms)

        wave = jnp.linspace(3000.0, 9000.0, 2000)
        sigma_lib_curve, _ = _resolve_ssp_resolution(wave, "c3k_a")
        line_centers = (3934.0, 3969.0, 4102.0, 4861.0, 5175.0, 5895.0, 6563.0, 8000.0)
        template = _absorption_template(wave, line_centers)

        mock = np.asarray(
            apply_lsf(
                template,
                wave,
                resolution=resolution,
                sigma_lib_kms=sigma_lib_curve,
                sigma_v_kms=sigma_v_true,
            )
        )

        recovered_curve = _recover_sigma_v(template, wave, resolution, sigma_lib_curve, mock)
        assert recovered_curve == pytest.approx(sigma_v_true, abs=2.0)
