#!/usr/bin/env python3
"""CI guard: one paper, one reference — and no citation left marked unresolved.

Docstrings in ``src/`` are the published API reference, and the project rule is
that a formula or algorithm taken from a paper carries a full citation. Nothing
checked those citations against anything. ``check_doc_examples`` resolves
*symbols*, ``check_claude_md_paths`` resolves *paths*; a reference is prose, so
it was unverified by construction.

That is not hypothetical. The AGN NLR line template is Richardson et al. 2014,
MNRAS, 437, 2376, *"Interpreting the ionization sequence in AGN emission-line
spectra"*. The repo cited it three times, three different ways:

* ``components/agn/nlr.py`` — "Optical Spectroscopy of Post-Starburst
  Galaxies," ApJ **786, 87**
* ``components/agn/nlr_gaussian_precompute.py`` — same title, ApJ **782, 33**,
  carrying an inline ``CITATION-AUDIT NOTE: not found`` that was left in place
* ``docs/adr/0015-cigale-alignment.md`` — "Predicting the Emission Line
  Spectrum of Quasars," ApJ 786, 87

``2014ApJ...786...87`` is Brooks & Zolotov, *"Why Baryons Matter: The Kinematics
of Dwarf Spheroidal Satellites"*. Because the reference could not be resolved,
the template could not be checked against its source — so when a doublet ratio
in it disagreed with atomic physics, an atomic-physics argument looked like the
only available check, and the published data was "corrected" to satisfy a test
(#1752). A wrong citation is not a cosmetic defect; it removes the ability to
audit the thing it points at.

Three checks, all offline and all high-precision. This cannot know whether a
bibcode is *correct* — that needs the network — but it can enforce that the
repo does not disagree with itself, which is what actually happened.

1. One title, one bibcode. The same paper title must not appear against two
   different journal/volume/page triples. Fires on nlr.py vs
   nlr_gaussian_precompute.py above.
2. One bibcode, one title. The same journal/volume/page must not be claimed for
   two different papers.
3. No unresolved markers. A citation annotated "not found", "TODO", "citation
   needed" or similar is a known-bad reference someone chose to ship; it must be
   fixed or removed, not narrated.

Scope is numpydoc/rST reference entries (``.. [N] ...``), which is the form the
docstring standard mandates, so free prose that merely names an author is not
parsed and cannot produce a false positive.

Dependencies: standard library only. The ``lint`` job installs ruff and nothing
else, so this must not import ``yaml`` or ``tengri``.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Trees to scan. Docstrings in ``src`` are the API reference; ADRs and user docs
#: carry the same citations and drifted independently of them.
SCAN = (
    ("src", ("*.py",)),
    ("docs", ("*.md", "*.rst")),
)

#: ``docs/dev`` is design notes and parity audits, which legitimately quote a
#: reference as it appeared at the time, including a wrong one under discussion.
#: ``docs/dev/archive`` holds the citation audit that *recorded* these defects.
#: ``docs/auto_examples`` is generated by sphinx-gallery from ``examples/``.
EXCLUDE_DIRS = (
    "docs/dev/archive",
    "docs/auto_examples",
    "docs/_notebooks",
    "docs/_build",
)

#: A reference entry: ``.. [1] ...`` plus its indented continuation lines.
_ENTRY_START = re.compile(r"^\s*\.\.\s+\[[^\]]+\]\s")

#: A quoted paper title. Straight or curly quotes, >= 4 words, so a short quoted
#: phrase inside a sentence is not mistaken for a title.
_TITLE = re.compile(r"[\"“]([^\"”]{20,300})[\"”]")

#: Punctuation to strip from a token in the numeric run after the journal.
_PUNCT = re.compile(r"[.;:()\[\]]")

#: The journal token. The numeric run that follows it is parsed by
#: :func:`_extract_bibcode` rather than matched, because its arity varies.
_JOURNAL = re.compile(
    r"\b(?P<journal>ApJS|ApJL|ApJ|MNRAS|A&A|AJ|PASP|ARA&A|Natur|Sci|AN|JPhysA)\b[,.\s]+"
)

#: Known title drift, pinned so it cannot grow (#1785).
#:
#: Check 2 (one bibcode, one paper) currently finds 31 references cited with two
#: or more differently-worded titles — mostly paraphrase, e.g. ApJS 254, 22 is
#: written both "Prospector: Stellar Population Inference from Spectra and SEDs"
#: and "Prospector: Inferring the Star Formation Histories of Galaxies...". Each
#: needs checking against the publisher record one at a time, which is not a
#: mechanical sweep, so the backlog is recorded here rather than blocking the
#: guard that stops it from growing. Same pattern as
#: ``tools/check_zero_hiding_clamps.py``, which pins a count for the same reason.
#:
#: A bibcode may only be added to this list with the paper checked and the drift
#: judged harmless. Removing one is the goal; adding one needs justification in
#: the PR.
KNOWN_TITLE_DRIFT = frozenset(
    {
        ("a&a", "132", "389"),
        ("a&a", "470", "221"),
        ("a&a", "622", "A103"),
        ("apj", "528", "799"),
        ("apj", "533", "682"),
        ("apj", "539", "718"),
        ("apj", "650", "57"),
        ("apj", "665", "1004"),
        ("apj", "737", "67"),
        ("apj", "840", "44"),
        ("apj", "876", "3"),
        ("apj", "879", "116"),
        ("apj", "917", "3"),
        ("apj", "927", "192"),
        ("apj", "948", "55"),
        ("apj", "986", "9"),
        ("apjs", "134", "1"),
        ("apjs", "140", "303"),
        ("apjs", "178", "20"),
        ("apjs", "229", "34"),
        ("apjs", "254", "22"),
        ("apjs", "80", "109"),
        ("mnras", "238", "897"),
        ("mnras", "420", "2756"),
        ("mnras", "425", "3094"),
        ("mnras", "456", "3354"),
        ("mnras", "458", "2288"),
        ("mnras", "480", "1247"),
        ("mnras", "480", "4379"),
        ("mnras", "498", "5581"),
    }
)

#: Markers that say, in the citation itself, that the reference is not trusted.
_UNRESOLVED = re.compile(
    r"CITATION[- ]AUDIT|not found|could not (?:be )?(?:find|locate|verif)"
    r"|citation needed|TODO:?\s*(?:cite|citation|verify)|\?\?\?",
    re.I,
)


def _normalize_title(title: str) -> str:
    """Collapse whitespace, drop trailing punctuation, casefold."""
    return re.sub(r"[\s\n]+", " ", title).strip(" ,.;:").casefold()


def _same_paper(a: str, b: str) -> bool:
    """Two normalized titles naming the same paper.

    A citation legitimately abbreviates: *"Dust tori around type II active
    nuclei"* and *"Dust tori around type II active nuclei. I. Observational
    constraints..."* are one paper written two ways, and flagging that as a
    conflict is noise, not a finding. Prefix containment catches the whole
    family (series numerals, dropped subtitles) without matching unrelated
    papers, whose titles diverge in the first few words.
    """
    return a == b or a.startswith(b) or b.startswith(a)


def _canonical(title: str, known: dict[str, str]) -> str:
    """Fold a title onto an already-seen variant of the same paper.

    Keeps the shortest spelling as the key so ``A`` and ``A. I. Subtitle``
    collapse deterministically regardless of which is encountered first.
    """
    for seen in known:
        if _same_paper(title, seen):
            if len(title) < len(seen):
                known[title] = title
                for k, v in list(known.items()):
                    if v == seen:
                        known[k] = title
                return title
            return known[seen]
    known[title] = title
    return title


def _normalize_journal(journal: str) -> str:
    return journal.replace(".", "").replace(" ", "").casefold()


def _iter_files():
    """Yield ``(path, repo-relative path)`` in a fixed order on every platform.

    :func:`_canonical` folds a title onto an already-seen variant of the same
    paper, so which spelling becomes the group key depends on encounter order —
    and ``Path.rglob`` yields in filesystem order, which differs between macOS
    and Linux. That made the guard's own answer platform-dependent: it passed
    locally with 31 pinned entries and failed in CI claiming ``AJ 122, 549`` no
    longer drifts. Sorting makes the fold deterministic, so a baseline recorded
    on one machine means the same thing on another.
    """
    found = []
    for subdir, patterns in SCAN:
        base = ROOT / subdir
        if not base.is_dir():
            continue
        for pattern in patterns:
            for path in base.rglob(pattern):
                rel = path.relative_to(ROOT).as_posix()
                if any(rel.startswith(d) for d in EXCLUDE_DIRS):
                    continue
                found.append((rel, path))
    for rel, path in sorted(found):
        yield path, rel


def _is_year(token: str) -> bool:
    return token.isdigit() and 1900 <= int(token) <= 2099


def _extract_bibcode(entry: str):
    """The ``(journal, volume, page)`` of a reference entry, or None.

    Citations here put the year in three places and sometimes carry an issue
    number, so the numeric run after the journal is not a fixed shape:

    ====================================  ==================================
    written as                            means
    ====================================  ==================================
    ``ApJ, 786, 87``                      volume 786, page 87
    ``ApJS, 254, 22, 2021``               volume 254, page 22, year last
    ``MNRAS, 2014, 437, 3, 2376-2403``    year first, volume 437, issue 3
    ====================================  ==================================

    Pattern-matching a fixed arity gets one of these wrong whichever way it is
    written — reading ``ApJS, 254, 22, 2021`` as page 2021 invented a phantom
    "one paper, two references" for Prospector. So the run is parsed instead:
    strip a leading or trailing year, then take the first token as volume and
    the last as page, which discards an issue number in the middle.
    """
    m = _JOURNAL.search(entry)
    if not m:
        return None

    tail = entry[m.end() :]
    tokens = []
    for raw in re.split(r"[,\s]+", tail.strip()):
        tok = _PUNCT.sub("", raw)
        if re.fullmatch(r"[A-Z]?\d{1,6}(?:-\d{1,6})?", tok):
            tokens.append(tok.split("-")[0])
        else:
            break
    if tokens and _is_year(tokens[0]):
        tokens = tokens[1:]
    if len(tokens) > 1 and _is_year(tokens[-1]):
        tokens = tokens[:-1]
    if len(tokens) < 2:
        return None

    return (_normalize_journal(m.group("journal")), tokens[0], tokens[-1])


def _iter_entries(text: str):
    """Yield ``(line_number, entry_text)`` for each ``.. [N]`` reference block."""
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if not _ENTRY_START.match(lines[i]):
            i += 1
            continue
        start = i
        indent = len(lines[i]) - len(lines[i].lstrip())
        block = [lines[i].strip()]
        i += 1
        while i < len(lines):
            nxt = lines[i]
            if not nxt.strip() or _ENTRY_START.match(nxt):
                break
            if len(nxt) - len(nxt.lstrip()) <= indent:
                break
            block.append(nxt.strip())
            i += 1
        yield start + 1, " ".join(block)


def main() -> int:
    by_title: dict[str, set] = defaultdict(set)
    by_bibcode: dict[tuple, set] = defaultdict(set)
    where: dict[tuple, list] = defaultdict(list)
    unresolved: list[tuple[str, int, str]] = []
    canonical_titles: dict[str, str] = {}

    for path, rel in _iter_files():
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if ".. [" not in text:
            continue

        for lineno, entry in _iter_entries(text):
            if _UNRESOLVED.search(entry):
                unresolved.append((rel, lineno, entry[:160]))

            title_m = _TITLE.search(entry)
            bib = _extract_bibcode(entry)
            if not (title_m and bib):
                continue
            if len(title_m.group(1).split()) < 4:
                continue

            title = _canonical(_normalize_title(title_m.group(1)), canonical_titles)
            by_title[title].add(bib)
            by_bibcode[bib].add(title)
            where[("title", title, bib)].append(f"{rel}:{lineno}")
            where[("bib", bib, title)].append(f"{rel}:{lineno}")

    problems: list[str] = []

    for title, bibs in sorted(by_title.items()):
        if len(bibs) > 1:
            rendered = ", ".join(f"{j.upper()} {v}, {p}" for j, v, p in sorted(bibs))
            problems.append(
                f'One paper, {len(bibs)} different references:\n    "{title[:90]}"\n'
                f"    cited as: {rendered}"
            )
            for bib in sorted(bibs):
                for loc in where[("title", title, bib)]:
                    problems.append(f"      {loc}  ->  {bib[0].upper()} {bib[1]}, {bib[2]}")

    pinned_seen = set()
    for bib, titles in sorted(by_bibcode.items()):
        if len(titles) <= 1:
            continue
        if bib in KNOWN_TITLE_DRIFT:
            pinned_seen.add(bib)
            continue
        problems.append(
            f"One reference, {len(titles)} different papers: {bib[0].upper()} {bib[1]}, {bib[2]}"
        )
        for title in sorted(titles):
            for loc in where[("bib", bib, title)]:
                problems.append(f'      {loc}  ->  "{title[:80]}"')

    # A pinned entry that no longer drifts has been fixed; drop it from the set so
    # the backlog only ever shrinks and cannot quietly be re-used for a new one.
    stale = KNOWN_TITLE_DRIFT - pinned_seen
    if stale:
        problems.append(
            f"{len(stale)} pinned citation(s) no longer drift — remove from "
            f"KNOWN_TITLE_DRIFT in {Path(__file__).name}:\n    "
            + ", ".join(f"{j.upper()} {v}, {p}" for j, v, p in sorted(stale))
        )

    for rel, lineno, entry in unresolved:
        problems.append(
            f"Citation marked unresolved and shipped anyway:\n    {rel}:{lineno}\n    {entry}"
        )

    if problems:
        print(f"FAIL: {len(problems)} citation problem(s)\n")
        for p in problems:
            print(f"  {p}\n")
        print(
            "A citation the repo disagrees with itself about cannot be used to audit\n"
            "the code it justifies — that is how the Richardson+2014 NLR template was\n"
            '"corrected" against a paper nobody could look up (#1752). Fix the\n'
            "reference, or remove it if the claim is not actually sourced."
        )
        return 1

    print(
        f"OK: {len(by_title)} cited paper(s) resolve to one reference each; "
        f"none marked unresolved. ({len(pinned_seen)} pinned title-drift "
        "backlog entries, #1785.)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
