# SPDX-License-Identifier: BSD-3-Clause
"""Shared utilities: grid construction, cosmology, conversions, magnitudes."""

from tengri.utils.conversions import (
    air_to_vacuum,
    attenuation_to_tau,
    erg_per_s_to_lsun,
    flambda_to_fnu,
    fnu_to_flambda,
    fnu_to_jy,
    fnu_to_lnu,
    fnu_to_maggies,
    fnu_to_njy,
    fnu_to_ujy,
    jy_to_fnu,
    llambda_to_lnu,
    lnu_to_fnu,
    lnu_to_llambda,
    lsun_to_erg_per_s,
    maggies_to_fnu,
    njy_to_fnu,
    tau_to_attenuation,
    ujy_to_fnu,
    vacuum_to_air,
)
from tengri.utils.cosmology import (
    DEFAULT_COSMO,
    PLANCK18,
    age_at_z,
    age_at_z0,
    angular_diameter_distance,
    angular_diameter_distance_mpc,
    arcsec_per_kpc,
    comoving_distance,
    comoving_distance_mpc,
    comoving_volume_element,
    distance_modulus,
    kpc_per_arcsec,
    lookback_time,
    luminosity_distance,
    luminosity_distance_mpc,
    z_at_cosmic_time,
    z_at_lookback_time,
)
from tengri.utils.diffndhist import tw_ndhist, tw_ndhist_weighted
from tengri.utils.grid import log_age_to_age_yr, make_log_age_grid
from tengri.utils.grid_interp import (
    PreintegratedGrid,
    PreintegratedLines,
    interp_nd_triweight,
    preintegrate_grid,
    preintegrate_lines,
    slice_fixed_axes,
)
from tengri.utils.interpolation import (
    apply_grid_window,
    compute_grid_weights,
    compute_grid_window,
    edges_for_grid,
    tw_cuml_kern,
)
from tengri.utils.magnitudes import (
    AB_VEGA_OFFSETS,
    ab_mag_to_fnu,
    ab_to_vega,
    absolute_ab_mag_to_lnu,
    absolute_to_apparent,
    apparent_to_absolute,
    cosmological_dimming,
    distance_modulus_from_dl,
    distance_modulus_from_dl_mpc,
    fnu_to_ab_mag,
    lnu_to_absolute_ab_mag,
    mag_to_surface_brightness,
    surface_brightness_to_mag,
    vega_to_ab,
)
from tengri.utils.transforms import inverse_sigmoid, sigmoid

__all__ = [
    # Magnitudes
    "AB_VEGA_OFFSETS",
    # Cosmology
    "DEFAULT_COSMO",
    "PLANCK18",
    "PreintegratedGrid",
    "PreintegratedLines",
    "ab_mag_to_fnu",
    "ab_to_vega",
    "absolute_ab_mag_to_lnu",
    "absolute_to_apparent",
    "age_at_z",
    "age_at_z0",
    # Conversions
    "air_to_vacuum",
    "angular_diameter_distance",
    "angular_diameter_distance_mpc",
    "apparent_to_absolute",
    "apply_grid_window",
    "arcsec_per_kpc",
    "attenuation_to_tau",
    "comoving_distance",
    "comoving_distance_mpc",
    "comoving_volume_element",
    # Interpolation
    "compute_grid_weights",
    "compute_grid_window",
    "cosmological_dimming",
    "distance_modulus",
    "distance_modulus_from_dl",
    "distance_modulus_from_dl_mpc",
    "edges_for_grid",
    "erg_per_s_to_lsun",
    "flambda_to_fnu",
    "fnu_to_ab_mag",
    "fnu_to_flambda",
    "fnu_to_jy",
    "fnu_to_lnu",
    "fnu_to_maggies",
    "fnu_to_njy",
    "fnu_to_ujy",
    # Grid interpolation
    "interp_nd_triweight",
    # Transforms
    "inverse_sigmoid",
    "jy_to_fnu",
    "kpc_per_arcsec",
    "llambda_to_lnu",
    "lnu_to_absolute_ab_mag",
    "lnu_to_fnu",
    "lnu_to_llambda",
    # Grid
    "log_age_to_age_yr",
    "lookback_time",
    "lsun_to_erg_per_s",
    "luminosity_distance",
    "luminosity_distance_mpc",
    "mag_to_surface_brightness",
    "maggies_to_fnu",
    "make_log_age_grid",
    "njy_to_fnu",
    "preintegrate_grid",
    "preintegrate_lines",
    "sigmoid",
    "slice_fixed_axes",
    "surface_brightness_to_mag",
    "tau_to_attenuation",
    "tw_cuml_kern",
    "tw_ndhist",
    "tw_ndhist_weighted",
    "ujy_to_fnu",
    "vacuum_to_air",
    "vega_to_ab",
    "z_at_cosmic_time",
    "z_at_lookback_time",
]
