#!/usr/bin/env python3
"""Cross-validation: tengri SED consistency vs bagpipes, FSPS, CIGALE.

Loads pre-computed reference SEDs from data/external_sed_reference.npz
(generated by scripts/generate_external_sed_reference.py) and builds
tengri SEDs live from the same SSP data for an apples-to-apples comparison.

Output figures (saved to analysis/figures/):
  crossval_stellar.png        — stellar continuum + dust attenuation cases
  crossval_metallicity.png    — metallicity grid (z_neg2 → z0p2)
  crossval_sfh.png            — exp-τ, log-normal, DPL SFH shapes
  crossval_nebular.png        — nebular emission cases (FSPS vs bagpipes only)
  crossval_summary.png        — median |Δ| summary across all matched cases

Usage:
    python analysis/crossval_external_seds.py [--save-pdf] [--show]
    python analysis/crossval_external_seds.py --only stellar
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DATA_DIR, FIG_DIR

_REF_PATH = DATA_DIR / "external_sed_reference.npz"
_SSP_PATH = DATA_DIR / "fsps_prsc_miles_chabrier.h5"

# ── Colours & labels ────────────────────────────────────────────────────────
_C = {
    "tengri": "#1f77b4",
    "fsps": "#ff7f0e",
    "bagpipes": "#2ca02c",
    "cigale": "#d62728",
}
_LABEL = {
    "tengri": "tengri (MILES+Chab.)",
    "fsps": "FSPS (MILES+Chab.)",
    "bagpipes": "bagpipes (BC03+Chab.)",
    "cigale": "CIGALE (BC03+Chab.)",
}
# Expected tolerance bands for residual panels
_TOL_SAME_SSP = 0.25  # ±25 %: same SSP library (tengri vs FSPS)
_TOL_DIFF_SSP = 0.50  # ±50 %: different SSP library (tengri vs bagpipes/CIGALE)

# ── Photometric band reference lines ────────────────────────────────────────
_BANDS = {
    "FUV": 1500.0,
    "NUV": 2800.0,
    "U": 3600.0,
    "V": 5500.0,
    "R": 6600.0,
    "J": 12000.0,
}

# ── Case groups ─────────────────────────────────────────────────────────────
# Each entry: (suffix_in_npz, short_title)

_GROUP_STELLAR: list[tuple[str, str]] = [
    ("stellar_starforming", "Starforming (const 3 Gyr, no dust)"),
    ("stellar_old_quenched", "Old quenched (const 5–10 Gyr ago)"),
    ("stellar_dusty_sfg", "Dusty SFG (τ_BC=1, τ_diff=0.5)"),
    ("stellar_metal_poor", "Metal-poor (Z/Z☉=0.05)"),
    ("stellar_metal_rich", "Metal-rich (Z/Z☉=2)"),
]

_GROUP_METALLICITY: list[tuple[str, str]] = [
    ("himet_z_neg2", "logZ/Z☉ = −2.0"),
    ("himet_z_neg1", "logZ/Z☉ = −1.0"),
    ("himet_zsun", "logZ/Z☉ = 0.0 (solar)"),
    ("himet_z0p2", "logZ/Z☉ = +0.2"),
]

_GROUP_SFH: list[tuple[str, str]] = [
    ("expsfh_tau0p3gyr", "Exp-τ: τ=0.3 Gyr"),
    ("expsfh_tau1gyr", "Exp-τ: τ=1 Gyr"),
    ("expsfh_tau5gyr", "Exp-τ: τ=5 Gyr"),
    ("expsfh_tau0p5gyr_dusty", "Exp-τ: τ=0.5 Gyr, dusty"),
    ("expsfh_tau2gyr_metpoor", "Exp-τ: τ=2 Gyr, metal-poor"),
    ("lognorm_lognorm_early", "Log-normal: early"),
    ("lognorm_lognorm_recent", "Log-normal: recent"),
    ("lognorm_lognorm_broad", "Log-normal: broad"),
    ("dplsfh_dpl_alpha5_beta5", "DPL: α=5, β=5 (symmetric)"),
    ("dplsfh_dpl_alpha10_beta2", "DPL: α=10, β=2 (fast rise)"),
    ("dplsfh_dpl_alpha3_beta10_dusty", "DPL: α=3, β=10, dusty"),
]

_GROUP_NEBULAR: list[tuple[str, str]] = [
    ("nebular_neb_young_u2", "Young (10 Myr), logU=−2"),
    ("nebular_neb_young_u35", "Young (10 Myr), logU=−3.5"),
    ("nebular_neb_highion_u1", "Young (10 Myr), logU=−1 (high ionisation)"),
    ("nebular_neb_metpoor_u2", "Metal-poor (0.05 Z☉), logU=−2"),
    ("nebular_neb_dusty_u25", "Dusty (τ_BC=1), logU=−2.5"),
]

# Extinction curve comparisons — FSPS vs bagpipes only.
# tengri uses the same Pei (1992) curves (SMC/LMC) and Cardelli (CCM) but
# within a two-component Charlot & Fall geometry (τ_BC / τ_diff), not a screen
# model.  Comparing tengri directly here would conflate SSP differences with
# dust-model geometry differences.
_GROUP_DUST_LAWS: list[tuple[str, str]] = [
    ("smc_smc_av02", "SMC Gordon+2003: A_V=0.2"),
    ("smc_smc_av10", "SMC Gordon+2003: A_V=1.0"),
    ("smc_smc_av20", "SMC Gordon+2003: A_V=2.0"),
    ("lmc_lmc_av02", "LMC Gordon+2003: A_V=0.2"),
    ("lmc_lmc_av10", "LMC Gordon+2003: A_V=1.0"),
    ("lmc_lmc_av20", "LMC Gordon+2003: A_V=2.0"),
    ("ccm_ccm_av02", "CCM Cardelli+1989 (MW, R_V=3.1): A_V=0.2"),
    ("ccm_ccm_av10", "CCM Cardelli+1989 (MW, R_V=3.1): A_V=1.0"),
    ("ccm_ccm_av30", "CCM Cardelli+1989 (MW, R_V=3.1): A_V=3.0"),
]


# ---------------------------------------------------------------------------
# tengri SED builders
# ---------------------------------------------------------------------------


def _tengri_const(
    ssp_data,
    start_gyr: float,
    end_gyr: float,
    logzsol: float = 0.0,
    tau_bc: float = 0.0,
    tau_diff: float = 0.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Build tengri SED with constant SFH, return (wave_Å, L_nu per Msun_formed)."""
    import jax

    from tengri import Parameters
    from tengri.core.model import SEDModel
    from tengri.distributions import Fixed

    spec = Parameters(
        mean_sfh_type="const",
        sfh_const_log_sfr=Fixed(0.0),
        sfh_const_start_gyr=Fixed(start_gyr),
        sfh_const_end_gyr=Fixed(end_gyr),
        met_logzsol=Fixed(logzsol),
        dust_tau_bc=Fixed(tau_bc),
        dust_tau_diff=Fixed(tau_diff),
        dust_slope=Fixed(-0.7),
        redshift=0.01,
    )
    model = SEDModel(spec, ssp_data)
    params = spec.sample(jax.random.PRNGKey(0))
    result = model.predict_rest_sed(params)
    wave = np.asarray(result.wavelength)
    sed = np.asarray(result.sed)
    m_formed = (end_gyr - start_gyr) * 1.0e9  # SFR=1 Msun/yr
    return wave, sed / m_formed


def _tengri_dexp(
    ssp_data,
    tau_gyr: float,
    peak_sfr: float = 10.0,
    start_gyr: float = 0.0,
    logzsol: float = 0.0,
    tau_bc: float = 0.0,
    tau_diff: float = 0.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Build tengri SED with delayed-exponential SFH, return (wave_Å, L_nu per Msun_formed)."""
    import jax

    from tengri import Parameters
    from tengri.core.model import SEDModel
    from tengri.distributions import Fixed

    spec = Parameters(
        mean_sfh_type="dexp",
        sfh_dexp_log_peak_sfr=Fixed(np.log10(peak_sfr)),
        sfh_dexp_tau_gyr=Fixed(tau_gyr),
        sfh_dexp_start_gyr=Fixed(start_gyr),
        met_logzsol=Fixed(logzsol),
        dust_tau_bc=Fixed(tau_bc),
        dust_tau_diff=Fixed(tau_diff),
        dust_slope=Fixed(-0.7),
        redshift=0.01,
    )
    model = SEDModel(spec, ssp_data)
    params = spec.sample(jax.random.PRNGKey(0))
    result = model.predict_rest_sed(params)
    wave = np.asarray(result.wavelength)
    sed = np.asarray(result.sed)
    m_formed = peak_sfr * tau_gyr * 1.0e9 * np.e  # analytic integral of t*exp(-t/tau)
    return wave, sed / m_formed


def _tengri_dpl(
    ssp_data,
    alpha: float,
    beta: float,
    tau_gyr: float,
    peak_sfr: float = 10.0,
    logzsol: float = 0.0,
    tau_bc: float = 0.0,
    tau_diff: float = 0.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Build tengri SED with double-power-law SFH, return (wave_Å, L_nu per Msun_formed)."""
    import jax

    from tengri import Parameters
    from tengri.core.model import SEDModel
    from tengri.distributions import Fixed

    spec = Parameters(
        mean_sfh_type="dpl",
        sfh_dpl_log_peak_sfr=Fixed(np.log10(peak_sfr)),
        sfh_dpl_alpha=Fixed(alpha),
        sfh_dpl_beta=Fixed(beta),
        sfh_dpl_tau_gyr=Fixed(tau_gyr),
        met_logzsol=Fixed(logzsol),
        dust_tau_bc=Fixed(tau_bc),
        dust_tau_diff=Fixed(tau_diff),
        dust_slope=Fixed(-0.7),
        redshift=0.01,
    )
    model = SEDModel(spec, ssp_data)
    params = spec.sample(jax.random.PRNGKey(0))
    result = model.predict_rest_sed(params)
    wave = np.asarray(result.wavelength)
    sed = np.asarray(result.sed)
    # Numerical M_formed: integrate DPL from 0.001*tau to 100*tau Gyr
    t_yr = np.linspace(0.001 * tau_gyr, 100.0 * tau_gyr, 10000) * 1e9
    tau_yr = tau_gyr * 1e9
    sfr_t = peak_sfr / ((t_yr / tau_yr) ** alpha + (t_yr / tau_yr) ** (-beta))
    m_formed = float(np.trapz(sfr_t, t_yr))
    return wave, sed / m_formed


def _build_all_tengri_seds(ssp_data, ref_wave: np.ndarray) -> dict[str, np.ndarray]:
    """Build tengri SEDs for all matched cases and resample to ref_wave.

    Returns dict mapping 'tengri_{suffix}' → resampled SED per Msun (erg/s/Hz).
    Cases without a tengri implementation are silently skipped:
    - nebular: requires a separate SSP file with ionising photons
    - expsfh:  FSPS/bagpipes use a DECLINING tau model (SFR peaks at galaxy formation,
               falls toward the present — highest SFR at early cosmic times). tengri's
               SFH types use lookback-time parameterization where 'exp' and 'dexp' both
               represent SFHs that are most active in the RECENT past. There is no
               direct declining-tau equivalent in tengri's current SFH registry.
               Cross-validating expsfh would compare different physical galaxy types
               (old quenched vs. recently star-forming), not code differences.
               See docs/known_bugs.md CROSSVAL-02.
    """
    print("Building tengri SEDs live (this takes ~30–60 s for JIT compilation)...")
    seds: dict[str, np.ndarray] = {}

    def _add(suffix: str, wave: np.ndarray, sed_per_msun: np.ndarray) -> None:
        seds[f"tengri_{suffix}"] = _resample(wave, sed_per_msun, ref_wave)
        print(f"  tengri_{suffix}: OK")

    # ── Stellar cases (constant SFH) ─────────────────────────────────────
    _add("stellar_starforming", *_tengri_const(ssp_data, 0.0, 3.0))
    _add("stellar_old_quenched", *_tengri_const(ssp_data, 5.0, 10.0))
    _add("stellar_dusty_sfg", *_tengri_const(ssp_data, 0.0, 3.0, tau_bc=1.0, tau_diff=0.5))
    _add("stellar_metal_poor", *_tengri_const(ssp_data, 0.0, 5.0, logzsol=-1.0))
    _add("stellar_metal_rich", *_tengri_const(ssp_data, 0.0, 5.0, logzsol=0.2))

    # ── Metallicity cases (constant SFH) ─────────────────────────────────
    _add("himet_zsun", *_tengri_const(ssp_data, 0.0, 5.0))
    _add("himet_z0p2", *_tengri_const(ssp_data, 0.0, 5.0, logzsol=0.2))
    _add("himet_z_neg1", *_tengri_const(ssp_data, 0.0, 5.0, logzsol=-1.0))
    _add("himet_z_neg2", *_tengri_const(ssp_data, 0.0, 8.0, logzsol=-2.0))

    # ── Exp-τ cases: SKIPPED for tengri ──────────────────────────────────
    # FSPS/bagpipes use a declining tau model (SFR highest at galaxy formation,
    # declining to present in cosmic time). This corresponds to SFR INCREASING
    # with lookback time in DSPS convention — the opposite of tengri's 'exp' SFH.
    # tengri's 'dexp' (delayed tau) peaks at start+tau in lookback time, representing
    # a recently star-forming galaxy, not a galaxy formed long ago.
    # Comparing them would show SFH-shape mismatch, not code errors.
    # See CROSSVAL-02 in docs/known_bugs.md.
    # (no lines added — tengri_{expsfh_*} keys intentionally absent)

    # ── Log-normal cases (dexp approximation: matched peak lookback time) ──
    # FSPS lognorm_early: peak at 2 Gyr from BB, tage=10 Gyr → peak 8 Gyr ago
    # tengri dexp: start=7 Gyr + tau=1 Gyr → peak also 8 Gyr lookback
    _add("lognorm_lognorm_early", *_tengri_dexp(ssp_data, tau_gyr=1.0, start_gyr=7.0))
    # FSPS lognorm_recent: peak at 1 Gyr from BB, tage=5 Gyr → peak 4 Gyr ago
    _add("lognorm_lognorm_recent", *_tengri_dexp(ssp_data, tau_gyr=0.5, start_gyr=3.0))
    # FSPS lognorm_broad: peak at 3.5 Gyr from BB, tage=8 Gyr → peak 4.5 Gyr ago
    _add("lognorm_lognorm_broad", *_tengri_dexp(ssp_data, tau_gyr=2.0, start_gyr=4.0))

    # ── DPL cases ──────────────────────────────────────────────────────────
    _add(
        "dplsfh_dpl_alpha5_beta5",
        *_tengri_dpl(ssp_data, alpha=5.0, beta=5.0, tau_gyr=3.0),
    )
    _add(
        "dplsfh_dpl_alpha10_beta2",
        *_tengri_dpl(ssp_data, alpha=10.0, beta=2.0, tau_gyr=2.0),
    )
    _add(
        "dplsfh_dpl_alpha3_beta10_dusty",
        *_tengri_dpl(
            ssp_data,
            alpha=3.0,
            beta=10.0,
            tau_gyr=4.0,
            logzsol=-0.5,
            tau_bc=0.8,
            tau_diff=0.3,
        ),
    )

    # Nebular cases are intentionally skipped — tengri's nebular cross-validation
    # requires a separate SSP file with ionising photons; no direct comparison is
    # included in the test suite.
    print(f"  Built {len(seds)} tengri SEDs.")
    return seds


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resample(wave_src: np.ndarray, flux_src: np.ndarray, wave_dst: np.ndarray) -> np.ndarray:
    """Log-linear interpolation; NaN outside source range."""
    pos = flux_src > 0
    if not pos.any():
        return np.zeros(len(wave_dst))
    log_flux = np.full_like(flux_src, np.nan)
    log_flux[pos] = np.log(flux_src[pos])
    out = np.exp(
        np.interp(np.log(wave_dst), np.log(wave_src), log_flux, left=np.nan, right=np.nan)
    )
    out[(wave_dst < wave_src[0]) | (wave_dst > wave_src[-1])] = 0.0
    return out


def _median_abs_resid(
    synth: np.ndarray,
    ref: np.ndarray,
    wave: np.ndarray,
    wmin: float = 1000.0,
    wmax: float = 10000.0,
) -> float:
    """Median |synth/ref - 1| in [wmin, wmax] Å."""
    mask = (wave >= wmin) & (wave <= wmax) & (ref > 0) & np.isfinite(synth) & (synth > 0)
    if not mask.any():
        return float("nan")
    return float(np.median(np.abs(synth[mask] / ref[mask] - 1.0)))


def _plot_band_lines(ax) -> None:
    """Draw vertical reference lines at photometric band centres."""
    for band, lam in _BANDS.items():
        ax.axvline(lam, color="grey", lw=0.4, ls="--", alpha=0.35, zorder=0)
        ylims = ax.get_ylim()
        if ylims[0] > 0 and ylims[1] > 0:
            ax.text(lam, ylims[0] * 1.15, band, fontsize=4.5, ha="center", color="grey", alpha=0.7)


# ---------------------------------------------------------------------------
# Per-case SED + residual panel pair
# ---------------------------------------------------------------------------


def _fill_case_row(
    ax_sed,
    ax_res,
    wave: np.ndarray,
    ref: dict,
    suffix: str,
    title: str,
) -> dict[str, float]:
    """Plot SED and fractional residual for one case. Returns median |Δ| per code."""
    tengri_key = f"tengri_{suffix}"
    fsps_key = f"fsps_{suffix}"
    bagpipes_key = f"bagpipes_{suffix}"
    cigale_key = f"cigale_{suffix}"

    # ── SED panel ──────────────────────────────────────────────────
    ax_sed.set_title(title, fontsize=7.5, pad=3)
    ax_sed.set_xlabel("Wavelength (Å)", fontsize=7)
    ax_sed.set_ylabel(r"$L_\nu$ [erg s$^{-1}$ Hz$^{-1}$ $M_\odot^{-1}$]", fontsize=6.5)

    plotted: list[str] = []
    for code, key, lw, zo in [
        ("fsps", fsps_key, 1.2, 2),
        ("bagpipes", bagpipes_key, 1.2, 2),
        ("cigale", cigale_key, 1.2, 2),
        ("tengri", tengri_key, 1.8, 5),
    ]:
        if key not in ref:
            continue
        sed = ref[key]
        pos = (sed > 0) & np.isfinite(sed)
        if not pos.any():
            continue
        ax_sed.semilogy(
            wave[pos], sed[pos], color=_C[code], lw=lw, alpha=0.85, label=_LABEL[code], zorder=zo
        )
        plotted.append(code)

    if plotted:
        ax_sed.set_xlim(1000, 12000)
        ax_sed.legend(fontsize=5, loc="upper right", handlelength=1.2)

    # ── Residual panel ─────────────────────────────────────────────
    ax_res.set_xlabel("Wavelength (Å)", fontsize=7)
    ax_res.set_ylabel(r"$L_\nu / L_\nu^{\rm FSPS} - 1$", fontsize=6.5)
    ax_res.axhline(0.0, color="k", lw=0.8)
    ax_res.axhspan(
        -_TOL_SAME_SSP,
        _TOL_SAME_SSP,
        color="#1f77b4",
        alpha=0.06,
        label=f"±{int(_TOL_SAME_SSP * 100)}%",
    )
    ax_res.axhspan(
        -_TOL_DIFF_SSP,
        _TOL_DIFF_SSP,
        color="grey",
        alpha=0.06,
        label=f"±{int(_TOL_DIFF_SSP * 100)}%",
    )

    stats: dict[str, float] = {}
    if fsps_key not in ref or not (ref[fsps_key] > 0).any():
        ax_res.text(
            0.5,
            0.5,
            "FSPS ref\nnot available",
            ha="center",
            va="center",
            transform=ax_res.transAxes,
            fontsize=8,
        )
        return stats

    fsps_sed = ref[fsps_key]
    fsps_safe = (fsps_sed > 0) & np.isfinite(fsps_sed)

    for code, key, lw in [
        ("bagpipes", bagpipes_key, 1.0),
        ("cigale", cigale_key, 1.0),
        ("tengri", tengri_key, 1.8),
    ]:
        if key not in ref:
            continue
        code_sed = ref[key]
        mask = fsps_safe & (code_sed > 0) & np.isfinite(code_sed)
        if not mask.any():
            continue
        resid = code_sed[mask] / fsps_sed[mask] - 1.0
        zo = 5 if code == "tengri" else 2
        ax_res.plot(
            wave[mask], resid, color=_C[code], lw=lw, alpha=0.80, label=_LABEL[code], zorder=zo
        )
        stats[code] = _median_abs_resid(code_sed, fsps_sed, wave)

    ax_res.set_xlim(1000, 12000)
    ax_res.set_ylim(-1.5, 1.5)
    ax_res.legend(fontsize=5, loc="upper right", handlelength=1.2)
    return stats


# ---------------------------------------------------------------------------
# Figure builders
# ---------------------------------------------------------------------------


def _make_group_figure(
    wave: np.ndarray,
    ref: dict,
    cases: list[tuple[str, str]],
    fig_title: str,
    figsize: tuple[float, float] | None = None,
) -> tuple:
    """Build a figure with one row per case, two columns (SED | residual)."""
    import matplotlib.pyplot as plt

    n = len(cases)
    fs = figsize or (13, 3.2 * n)
    fig, axes = plt.subplots(n, 2, figsize=fs, squeeze=False)
    fig.suptitle(fig_title, fontsize=11, y=1.002, fontweight="bold")

    all_stats: dict[str, dict[str, float]] = {}
    for row, (suffix, title) in enumerate(cases):
        stats = _fill_case_row(axes[row, 0], axes[row, 1], wave, ref, suffix, title)
        all_stats[suffix] = stats

    fig.tight_layout(h_pad=2.0, w_pad=2.5)
    return fig, all_stats


def _make_summary_figure(
    all_stats: dict[str, dict[str, dict[str, float]]],
    figsize: tuple[float, float] = (14, 6),
):
    """Bar chart of median |Δ| vs FSPS for tengri and bagpipes across all matched cases."""
    import matplotlib.pyplot as plt

    # Flatten: {suffix: {code: median_resid}}
    flat: dict[str, dict[str, float]] = {}
    for group_stats in all_stats.values():
        flat.update(group_stats)

    suffixes = [s for s in flat if "tengri" in flat[s]]
    if not suffixes:
        fig, ax = plt.subplots(figsize=figsize)
        ax.text(0.5, 0.5, "No matched cases", ha="center", va="center", transform=ax.transAxes)
        return fig

    x = np.arange(len(suffixes))
    w = 0.30

    tengri_vals = [flat[s].get("tengri", float("nan")) for s in suffixes]
    bags_vals = [flat[s].get("bagpipes", float("nan")) for s in suffixes]

    fig, ax = plt.subplots(figsize=figsize)
    ax.bar(x - w / 2, tengri_vals, width=w, color=_C["tengri"], alpha=0.85, label=_LABEL["tengri"])
    ax.bar(
        x + w / 2, bags_vals, width=w, color=_C["bagpipes"], alpha=0.85, label=_LABEL["bagpipes"]
    )

    # Reference tolerance lines
    ax.axhline(
        _TOL_SAME_SSP,
        color=_C["tengri"],
        lw=1.0,
        ls="--",
        alpha=0.6,
        label=f"±{int(_TOL_SAME_SSP * 100)}% (same SSP)",
    )
    ax.axhline(
        _TOL_DIFF_SSP,
        color="grey",
        lw=1.0,
        ls="--",
        alpha=0.6,
        label=f"±{int(_TOL_DIFF_SSP * 100)}% (diff. SSP)",
    )

    # Colour bar backgrounds by group
    _group_spans = [
        ("Stellar", 0, 5, "#d4e6f1"),
        ("Metallicity", 5, 9, "#d5f5e3"),
        ("Exp-τ SFH", 9, 14, "#fdebd0"),
        ("Log-normal SFH", 14, 17, "#f9ebea"),
        ("DPL SFH", 17, 20, "#f5eef8"),
    ]
    for label, i0, i1, col in _group_spans:
        if i0 >= len(suffixes):
            break
        i1 = min(i1, len(suffixes))
        ax.axvspan(i0 - 0.5, i1 - 0.5, color=col, alpha=0.35, zorder=0)
        ylim_top = ax.get_ylim()[1] if ax.get_ylim()[1] > 0 else 0.95
        ax.text(
            (i0 + i1) / 2 - 0.5,
            ylim_top * 0.95,
            label,
            ha="center",
            va="top",
            fontsize=7,
            color="black",
            alpha=0.7,
        )

    ax.set_xticks(x)
    short_labels = [
        s.replace("stellar_", "")
        .replace("expsfh_", "")
        .replace("himet_", "")
        .replace("lognorm_", "")
        .replace("dplsfh_", "")
        .replace("nebular_", "")
        for s in suffixes
    ]
    ax.set_xticklabels(short_labels, rotation=45, ha="right", fontsize=6.5)
    ax.set_ylabel("Median |Δ| = median |L_ν/L_ν^FSPS − 1|", fontsize=9)
    ax.set_title(
        "Cross-validation summary: tengri vs external codes\n"
        r"(1000–10000 Å; FSPS baseline; same MILES+Chabrier SSP ⟹ expect <25% for tengri)",
        fontsize=10,
    )
    ax.legend(fontsize=8, loc="upper left")
    ax.set_ylim(bottom=0.0)
    fig.tight_layout()
    return fig


# ---------------------------------------------------------------------------
# Console report
# ---------------------------------------------------------------------------


def _print_consistency_report(ref: dict, wave: np.ndarray) -> None:
    """Print table of median |Δ| for every tengri↔code pair."""
    print()
    print("=" * 72)
    print(f"{'Case':<38} {'tengri/FSPS':>12} {'bags/FSPS':>12} {'cig/FSPS':>10}")
    print("=" * 72)

    all_cases = [
        s
        for _, cases in [
            ("stellar", _GROUP_STELLAR),
            ("metallicity", _GROUP_METALLICITY),
            ("sfh", _GROUP_SFH),
            ("nebular", _GROUP_NEBULAR),
            ("dust_laws", _GROUP_DUST_LAWS),
        ]
        for s, _ in cases
    ]

    for suffix in all_cases:
        fsps_key = f"fsps_{suffix}"
        tengri_key = f"tengri_{suffix}"
        bags_key = f"bagpipes_{suffix}"
        cig_key = f"cigale_{suffix}"
        if fsps_key not in ref:
            continue
        fsps = ref[fsps_key]
        t_str = (
            f"{_median_abs_resid(ref[tengri_key], fsps, wave):.3f}"
            if tengri_key in ref
            else "  n/a"
        )
        b_str = (
            f"{_median_abs_resid(ref[bags_key], fsps, wave):.3f}" if bags_key in ref else "  n/a"
        )
        c_str = f"{_median_abs_resid(ref[cig_key], fsps, wave):.3f}" if cig_key in ref else "  n/a"
        # Flag large tengri deviations
        flag = ""
        if tengri_key in ref:
            v = _median_abs_resid(ref[tengri_key], fsps, wave)
            flag = " ⚠" if not np.isnan(v) and v > _TOL_SAME_SSP else ""
        print(f"{suffix:<38} {t_str:>12} {b_str:>12} {c_str:>10}{flag}")

    print("=" * 72)
    print("  ⚠ = tengri median |Δ| > 25% (same-SSP tolerance)")
    print("  n/a = tengri comparison not available for this case:")
    print("    - expsfh_*: FSPS/bagpipes use declining tau (SFR peaks at galaxy formation).")
    print("      tengri has no declining-tau SFH type; its 'exp'/'dexp' peak in the")
    print("      recent past. Comparing them would show SFH shape mismatch, not code errors.")
    print("      See docs/known_bugs.md CROSSVAL-02.")
    print("    - nebular_*: requires separate SSP with ionising-photon table.")
    print("    - smc_*/lmc_*/ccm_*: FSPS/bagpipes use a single-component screen model.")
    print("      tengri uses the same Pei (1992) / Cardelli (1989) extinction curves but")
    print("      within a two-component Charlot & Fall geometry (τ_BC/τ_diff), so a")
    print("      direct screen-model comparison would conflate code vs. geometry differences.")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Crossval visualizations: tengri vs external codes."
    )
    parser.add_argument("--save-pdf", action="store_true", help="Also save PDF alongside PNG")
    parser.add_argument("--show", action="store_true", help="Show interactive plots")
    parser.add_argument(
        "--only",
        choices=["stellar", "metallicity", "sfh", "nebular", "dust_laws", "summary"],
        default=None,
        help="Produce only one figure group",
    )
    parser.add_argument(
        "--no-tengri",
        action="store_true",
        help="Skip building tengri SEDs (show external codes only)",
    )
    args = parser.parse_args()

    import matplotlib

    if not args.show:
        matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if not _REF_PATH.is_file():
        print(f"ERROR: Reference file not found: {_REF_PATH}")
        print("Run: python scripts/generate_external_sed_reference.py")
        sys.exit(1)

    ref = dict(np.load(str(_REF_PATH), allow_pickle=True))
    wave = ref["wave_grid"]
    n_keys = len([k for k in ref if not k.startswith("wave")])
    print(f"Loaded reference: {_REF_PATH}  ({n_keys} SED arrays)")

    # Build tengri SEDs live and inject into ref dict
    if not args.no_tengri:
        if not _SSP_PATH.is_file():
            print(f"WARNING: SSP file not found: {_SSP_PATH}")
            print("  Proceeding without tengri SEDs (pass --no-tengri to suppress this warning).")
        else:
            import jax

            jax.config.update("jax_enable_x64", True)
            from tengri.models.sps.dsps_wrapper import load_ssp_data

            ssp_data = load_ssp_data(str(_SSP_PATH))
            tengri_seds = _build_all_tengri_seds(ssp_data, wave)
            ref.update(tengri_seds)
            print(f"  Injected {len(tengri_seds)} tengri SEDs into reference dict.")

    # Print quick numerical summary before plotting
    _print_consistency_report(ref, wave)

    FIG_DIR.mkdir(parents=True, exist_ok=True)

    figures: dict = {}
    all_group_stats: dict[str, dict[str, dict[str, float]]] = {}

    def _maybe_make(group_id: str, cases, title, fs=None):
        if args.only is not None and args.only != group_id:
            return
        fig, stats = _make_group_figure(wave, ref, cases, title, figsize=fs)
        figures[group_id] = fig
        all_group_stats[group_id] = stats

    _maybe_make(
        "stellar",
        _GROUP_STELLAR,
        "Stellar & dust attenuation — tengri vs FSPS / bagpipes",
        fs=(13, 16),
    )
    _maybe_make(
        "metallicity",
        _GROUP_METALLICITY,
        "Metallicity grid — tengri vs FSPS / bagpipes",
        fs=(13, 13),
    )
    _maybe_make(
        "sfh",
        _GROUP_SFH,
        "SFH shapes (exp-τ, log-normal, DPL) — tengri vs FSPS / bagpipes",
        fs=(13, 35),
    )
    _maybe_make(
        "nebular",
        _GROUP_NEBULAR,
        "Nebular emission — FSPS vs bagpipes (BakedIn) [tengri nebular crossval pending]",
        fs=(13, 16),
    )
    _maybe_make(
        "dust_laws",
        _GROUP_DUST_LAWS,
        "Extinction laws: SMC / LMC (Gordon+2003) and CCM (Cardelli+1989) — FSPS vs bagpipes",
        fs=(13, 29),
    )

    # Summary figure
    if args.only is None or args.only == "summary":
        fig_sum = _make_summary_figure(all_group_stats)
        figures["summary"] = fig_sum

    # ── Save ──────────────────────────────────────────────────────────────
    for name, fig in figures.items():
        out_png = FIG_DIR / f"crossval_{name}.png"
        fig.savefig(out_png, bbox_inches="tight", dpi=150)
        print(f"Saved: {out_png}")
        if args.save_pdf:
            out_pdf = FIG_DIR / f"crossval_{name}.pdf"
            fig.savefig(out_pdf, bbox_inches="tight", dpi=150)
            print(f"Saved: {out_pdf}")

    if args.show:
        plt.show()

    for fig in figures.values():
        plt.close(fig)


if __name__ == "__main__":
    main()
